use sezgi_core::component::*;
use sezgi_core::problem::Population;
use sezgi_core::space::{BlockValues, Genotype};
use sezgi_core::state::StateReq;

/// Gravitational Search Algorithm (Rashedi, E., Nezamabadi-pour, H. & Saryazdi,
/// S. 2009, "GSA: A Gravitational Search Algorithm", *Information Sciences*
/// 179(13), 2232-2248, DOI 10.1016/j.ins.2009.03.004) -- a **labeled metaphor
/// preset**: faithful to the primary source's own reference MATLAB
/// implementation's update equations and loop structure, with a pinned
/// deterministic draw order and property tests, but NOT validated against
/// the paper's (or any other publication's) reported benchmark numbers. No
/// established equivalence critique of the ITOR-six-algorithm kind is cited
/// here (GWO/MFO/WOA/FA/BA/ALO's critique does not cover GSA) -- primary
/// only.
///
/// **This is the wave's LAST stateful/blackboard algorithm**: the per-agent
/// velocity `v` is a genuine persisted memory (blackboard `gsa/velocity`),
/// exactly matching `pso.rs`'s and `ba.rs`'s own precedent -- owned entirely
/// by [`GsaGenerator`] itself (reads it, updates it, writes it back, no
/// separate adapter -- same self-owning shape as `pso.rs`/`ba.rs`).
///
/// ## Provenance (PROVENANCE-FIRST protocol)
///
/// **Primary artifact used (governs):** Esmat Rashedi's own MATLAB source
/// for MATLAB Central File Exchange submission **#27756** ("Gravitational
/// Search Algorithm (GSA)"): `GSA.m`, `Gconstant.m`, `massCalculation.m`,
/// `Gfield.m` and `move.m`. The File Exchange page itself did not yield
/// fetchable raw source text through the tools available to this task
/// (unlike several earlier tasks' File Exchange preview-mirror routes), so
/// the five files were instead obtained from a GitHub mirror
/// (`SajadAHMAD1/CPSOCGSA-for-Engineering-Design-Optimization`) that carries
/// them verbatim -- `GSA.m`'s own header there reads, unedited: *"GSA code
/// v1.1. Generated by Esmat Rashedi, 2010."* followed by the exact citation
/// to the 2009 *Information Sciences* paper above, which is how this is
/// identified as the **author's own** code (not a third-party
/// reimplementation) despite the indirect fetch route. **Secondary
/// corroboration only, not governing:** `himanshuRepo/Gravitational-Search-
/// Algorithm` (Saraswat, Mittal & Pal), a literal, line-for-line Python port
/// of the SAME five files under the SAME names (`gConstant.py`,
/// `massCalculation.py`, `gField.py`, `move.py`, `GSA.py`), whose own header
/// cites the same 2009 paper and states the template is "the matlab version
/// of GSA at mathworks" -- cross-checked and found to agree with the
/// governing MATLAB source in every particular below; consulted only to
/// corroborate the reading of the MATLAB source, never to override it.
///
/// **Extracted equations / loop structure (from `GSA.m`/`Gconstant.m`/
/// `massCalculation.m`/`Gfield.m`/`move.m`, quoted/paraphrased from the
/// fetched sources, per-iteration order):**
///
/// ```text
/// GSA.m (per iteration, min_flag=1 minimization, Rnorm=2, pinned defaults
/// ElitistCheck=1, Rpower=1 -- both verified as the source's own demo
/// defaults, corroborated by the Python port's `GSA.py`: "ElitistCheck=1;
/// Rpower=1"):
///   X = space_bound(X, up, down)          -- boundary clamp
///   fitness = evaluateF(X)                -- evaluate
///   Fbest/Lbest updated IF fitness improved -- PURE REPORTING, see below
///   M = massCalculation(fitness, min_flag)
///   G = Gconstant(iteration, Max_Iteration)
///   a = Gfield(M, X, G, Rnorm, Rpower, ElitistCheck, iteration, Max_Iteration)
///   [X, V] = move(X, a, V)
/// ```
///
/// - **`Fbest`/`Lbest` -- VERIFIED to be pure reporting bookkeeping, never
///   fed back into the mechanism:** `GSA.m` updates a persisted best-ever
///   `Fbest`/`Lbest` purely to build `BestChart` (the convergence curve
///   returned to the caller); it is **never read** by `massCalculation`,
///   `Gconstant`, `Gfield`, or `move` -- the entire mechanism (masses,
///   gravitational constant, Kbest selection, force, acceleration, velocity,
///   position) is a function of the CURRENT iteration's population alone.
///   **This directly CONFIRMS the controller's current-pop-convention
///   ruling**, exactly as anticipated ("likely literal source semantics
///   here") -- no attractor/best-so-far blackboard state is needed at all
///   (unlike `ba.rs`'s/`ssa.rs`'s current-pop `best` selections, which at
///   least feed the move itself); `RunResult::best_f`/`best_x` are already
///   sourced from `Evaluator`'s own best-tracking (updated inside
///   `Evaluator::evaluate` itself, the sole gateway every charged evaluation
///   passes through -- see `sezgi_core::problem::Evaluator`'s own doc), so
///   this generator needs ONLY the persisted velocity state.
/// - **Mass computation (`massCalculation.m`, eq. 14-20), VERIFIED against
///   the sketch, no delta:** `Fmax=max(fit)`, `Fmin=min(fit)`; for
///   minimization (`min_flag==1`): `best=Fmin`, `worst=Fmax` (eq. 17-18).
///   Raw mass `m_i = (fit_i - worst)/(best - worst)` (eq. 15) -- the best
///   individual (`fit_i==Fmin==best`) gets raw mass exactly `1`, the worst
///   (`fit_i==Fmax==worst`) gets raw mass exactly `0`. **Degenerate guard,
///   settling the brief's flagged VERIFY:** `if Fmax==Fmin: M=ones(N,1)` --
///   every raw mass set to `1`, NOT an error and NOT "mass 0". Normalization
///   `M_i = m_i / sum(m)` (eq. 16) is applied UNCONDITIONALLY, in BOTH
///   branches, AFTER the if/else -- so the degenerate case does not end up
///   "all mass 1" but "all mass exactly `1/N`" (uniform), same as the
///   normal branch's own always-applied final division. See
///   [`gsa_mass`].
/// - **Gravitational constant (`Gconstant.m`, eq. 28), VERIFIED, no delta:**
///   `G = G0 * exp(-alpha * iteration / Max_Iteration)`, `alpha=20`,
///   `G0=100` -- matching the sketch exactly. In sezgi's progress
///   convention (`progress = ctx.eval.used()/ctx.eval.budget()`, clamped
///   `[0,1]`, the SAME wave-wide convention `mfo.rs`/`ssa.rs` already use,
///   not a new decision for this task): `G = G0 * exp(-alpha * progress)`.
///   See [`gsa_g`].
/// - **Kbest schedule (`Gfield.m`'s `ElitistCheck==1` branch, eq. 21),
///   VERIFIED, settling the brief's flagged VERIFY:** `final_per = 2`
///   (percent, a literal constant, NOT the plan sketch's guessed "linear
///   N->1"); `kbest_percent = final_per + (1 - iteration/Max_Iteration) *
///   (100 - final_per)`; `kbest_count = round(N * kbest_percent / 100)`. In
///   sezgi's progress convention: `kbest_percent = final_per + (1 -
///   progress) * (100 - final_per)`. At `progress=0`: `kbest_percent=100`,
///   `kbest_count=N` (every agent). At `progress=1`: `kbest_percent=2`,
///   `kbest_count=round(0.02*N)` (e.g. `1` for `N=30`). **VERIFIED: NOT
///   clamped to a minimum of `1`** -- for small `N` near the end of a run
///   this can round to exactly `0` (no agent contributes force that
///   generation; the reference code has no floor here, and sezgi reproduces
///   that faithfully rather than adding an undocumented guard). Which
///   agents count as "best": `ds = sort(M, 'descend')` -- indices sorted by
///   MASS descending (a stable sort; ties keep the original agent order,
///   the same "stable sort, ties preserve input order" idiom `mfo.rs`'s
///   merge-sort-truncate already established for this wave), then the
///   `Kbest_count` FIRST indices of `ds` form the elite set. See
///   [`gsa_kbest_count`] / [`gsa_kbest_order`].
/// - **The force loop (`Gfield.m`), THE wave's flagged loop-structure trap,
///   VERIFIED and settled in favor of the FINER-grained reading:** for each
///   target agent `i` (outer loop), for each `ii` in `0..kbest` with source
///   `j = ds[ii]` (middle loop), SKIPPED entirely when `j==i` (no draw, no
///   distance computed): `R = ||X_i - X_j||_2` (Euclidean, `Rnorm=2`,
///   computed ONCE per `(i,j)` pair, hardcoded in `GSA.m` -- not a tunable
///   norm); then for each dimension `k` (innermost loop): **ONE INDEPENDENT
///   `rand` draw PER `(i, j, k)`** -- `Force[i,k] += rand * M[j] *
///   (X[j,k]-X[i,k]) / (R^Rpower + eps)`. The brief's flagged VERIFY ("per
///   (i,j) scalar or per (i,j,d)?") is settled: it is **per `(i,j,d)`**, a
///   fresh independent draw for every dimension of every contributing
///   neighbor -- NOT a single shared scalar weight per `(i,j)` pair applied
///   uniformly across all dimensions. `Rpower=1` (the verified demo
///   default) makes `R^Rpower == R` exactly; sezgi hardcodes this as a
///   direct `R` term (not `R.powf(1.0)`) for the same "pinned-exponent,
///   don't round-trip through the general form" reason `mfo.rs` hardcodes
///   its own `b=1.0`. `eps` is MATLAB's/`numpy.finfo(float).eps` machine
///   epsilon, `2.220446049250313e-16` -- IDENTICAL to Rust's
///   `f64::EPSILON`, used directly.
/// - **A second, structural VERIFIED delta from the plan's sketch -- no
///   `M_i` anywhere in the force or acceleration terms:** `Gfield.m`'s own
///   comment states this explicitly, TWICE: `%note that Mp(i)/Mi(i)=1`. The
///   paper's `M_a=M_p=M_i=M` assumption (all three "mass" roles are the
///   SAME per-agent scalar) means the passive/inertial mass ratio in
///   `a_i=F_i/M_i` is IDENTICALLY `1` and the source code never computes it
///   at all -- there is no intermediate `Force` array multiplied by `M_i`
///   and then divided by `M_i` again; `Force[i,k]` (as shown above) already
///   omits `M_i` entirely, and `acc = Force .* G` is the FINAL acceleration
///   with no further division. The plan's sketch (`F_d +=
///   draw·G·M_i·M_j·(...)`; `accel = F/M_i`) is NUMERICALLY equivalent
///   (the `M_i` factors cancel algebraically either way) but
///   STRUCTURALLY wrong against the verified source -- sezgi implements the
///   verified, simpler, `M_i`-free form directly (see [`gsa_force_term`]),
///   not a re-derived algebraic equivalent.
/// - **`move.m` (eq. 11-12), VERIFIED, no delta, and a SEPARATE loop after
///   `Gfield.m` fully completes:** `move()` is called only AFTER `Gfield()`
///   has returned the COMPLETE acceleration array -- its own per-`(i,d)`
///   `rand` draws happen in a loop that runs entirely AFTER every one of
///   `Gfield`'s per-`(i,j,d)` draws, not interleaved agent-by-agent. Per
///   `(i,d)`: `v[i,d] = rand * v[i,d] + a[i,d]` (eq. 11 -- ONE independent
///   `rand` draw per `(i,d)`, MULTIPLYING the OLD velocity, not
///   additive-only like `ba.rs`'s velocity term); `x[i,d] = x[i,d] +
///   v[i,d]` (eq. 12). See [`gsa_velocity_step`].
///
/// ## Blackboard state
///
/// - `gsa/velocity`: `Vec<Vec<f64>>`, length `pop_size`, each row `dim`
///   entries -- bootstrapped to zeros the first time this preset's
///   blackboard sees it (`GSA.m`'s own `V=zeros(dim,N)` at the top of the
///   run), owned entirely by [`GsaGenerator`] (read, updated, written back
///   below -- no separate adapter, same self-owning shape as `pso.rs`'s
///   `PsoGenerator` and `ba.rs`'s `BaGenerator`).
///
/// The per-agent/per-dimension math is factored into [`gsa_mass`],
/// [`gsa_g`], [`gsa_kbest_count`], [`gsa_kbest_order`], [`gsa_force_term`]
/// and [`gsa_velocity_step`] so each can be unit-tested directly without
/// needing to fake `Ctx`/`RngStream`.
///
/// `min_pop = 2`: with fewer than 2 agents there is no distinct `j != i` for
/// the force loop to ever contribute (same rationale as `ba.rs`'s/`cs.rs`'s
/// `min_pop = 2`).
///
/// Boundary handling and replacement are NOT part of this generator:
/// `presets::gsa` reuses `boundary/clamp` (`GSA.m`'s own `space_bound` call,
/// same as every other preset in this crate) and `replace/generational`
/// (`move()` overwrites every agent's position UNCONDITIONALLY -- no
/// per-agent fitness-improvement test anywhere in the source, same
/// rationale as `gwo.rs`/`woa.rs`/`sca.rs`/`ssa.rs`).
pub const GSA_G0: f64 = 100.0;
pub const GSA_ALPHA: f64 = 20.0;
pub const GSA_FINAL_PERCENT: f64 = 2.0;

/// Mass computation, VERIFIED against `massCalculation.m` (eq. 14-20):
/// `best=Fmin`, `worst=Fmax` for minimization (eq. 17-18); raw `m_i =
/// (fit_i-worst)/(best-worst)` (eq. 15), EXCEPT when `Fmax==Fmin` (every
/// fitness identical), in which case every raw mass is `1` (the source's own
/// degenerate guard -- NOT zero, NOT an error). Normalization `M_i =
/// m_i/sum(m)` (eq. 16) is applied UNCONDITIONALLY in both branches, so the
/// degenerate case yields uniform `1/N` masses, not "all mass 1". `Σ M_i ==
/// 1` always (barring floating rounding).
pub fn gsa_mass(fit: &[f64]) -> Vec<f64> {
    let n = fit.len();
    let fmax = fit.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let fmin = fit.iter().cloned().fold(f64::INFINITY, f64::min);
    let mut m: Vec<f64> = if fmax == fmin {
        vec![1.0_f64; n]
    } else {
        let best = fmin;
        let worst = fmax;
        fit.iter().map(|&f| (f - worst) / (best - worst)).collect()
    };
    let sum: f64 = m.iter().sum();
    for v in m.iter_mut() {
        *v /= sum;
    }
    m
}

/// Gravitational constant, VERIFIED against `Gconstant.m` (eq. 28):
/// `G0 * exp(-alpha * progress)`, `G0=100`, `alpha=20`. `progress=0` ->
/// exactly `G0=100.0`; `progress=1` -> `G0*exp(-alpha)`, a very small
/// positive number (`~2.061e-7`).
pub fn gsa_g(progress: f64) -> f64 {
    GSA_G0 * (-GSA_ALPHA * progress).exp()
}

/// Kbest COUNT, VERIFIED against `Gfield.m`'s `ElitistCheck==1` branch (eq.
/// 21): `kbest_percent = final_per + (1-progress)*(100-final_per)`,
/// `final_per=2`; `kbest_count = round(N * kbest_percent / 100)`.
/// `progress=0` -> `N` (all agents); `progress=1` -> `round(0.02*N)`.
/// **NOT clamped to a minimum of 1** -- can round to exactly `0` for small
/// `N` near the end of a run, VERIFIED (no floor in the source).
pub fn gsa_kbest_count(n: usize, progress: f64) -> usize {
    let percent = GSA_FINAL_PERCENT + (1.0 - progress) * (100.0 - GSA_FINAL_PERCENT);
    let raw = (n as f64) * percent / 100.0;
    raw.round() as usize
}

/// Agent indices sorted by mass DESCENDING, VERIFIED against `Gfield.m`'s
/// `[Ms,ds]=sort(M,'descend')`: a STABLE sort, ties keep the original agent
/// order (same "stable sort, ties preserve input order" idiom `mfo.rs`'s
/// merge-sort-truncate already established for this wave). The first
/// `kbest_count` entries of the returned order are the elite set.
pub fn gsa_kbest_order(mass: &[f64]) -> Vec<usize> {
    let mut idx: Vec<usize> = (0..mass.len()).collect();
    idx.sort_by(|&a, &b| mass[b].total_cmp(&mass[a]));
    idx
}

/// One dimension's force-accumulation TERM (a single `(i,j,d)` contribution,
/// summed by the caller across all `j` in the Kbest set), VERIFIED against
/// `Gfield.m`: `rand * M_j * (x_j_d - x_i_d) / (R_ij + eps)`. Note there is
/// NO `M_i` factor anywhere -- see the module doc's "no `M_i`" delta note.
/// `R_ij + f64::EPSILON` guards the (probability-zero but structurally
/// possible) `R_ij==0` coincident-position case, matching the source's own
/// `+eps` guard. `Rpower=1` (the verified pinned default) makes `R^Rpower`
/// exactly `R`, hardcoded directly (not via `powf`) per the module doc's
/// pinned-exponent rationale.
pub fn gsa_force_term(rand: f64, mass_j: f64, xj_d: f64, xi_d: f64, r_dist: f64) -> f64 {
    rand * mass_j * (xj_d - xi_d) / (r_dist + f64::EPSILON)
}

/// Euclidean distance (`Rnorm=2`, hardcoded in `GSA.m`, not a tunable norm).
fn euclidean(a: &[f64], b: &[f64]) -> f64 {
    a.iter().zip(b.iter()).map(|(x, y)| (x - y).powi(2)).sum::<f64>().sqrt()
}

/// One dimension's velocity update, VERIFIED against `move.m` (eq. 11):
/// `v_new = rand * v_old + accel` -- the random factor MULTIPLIES the OLD
/// velocity (unlike `ba.rs`'s purely-additive `v += (...)`), then (eq. 12,
/// applied by the caller) `x_new = x_old + v_new`.
pub fn gsa_velocity_step(v_d: f64, accel_d: f64, r1: f64) -> f64 {
    r1 * v_d + accel_d
}

fn floats(g: &Genotype) -> &Vec<f64> {
    match &g.blocks[0] { BlockValues::Float(x) => x, _ => unreachable!() }
}

pub struct GsaGenerator;

impl GsaGenerator {
    pub fn from_params(_p: &serde_json::Value) -> Result<Self, ComponentError> {
        // No tunable parameters (G0/alpha/final_percent/Rpower/Rnorm are the
        // pinned verified defaults/constants; ElitistCheck is pinned to 1 --
        // the Kbest elite shrink this wave's task explicitly names).
        Ok(Self)
    }
}

impl Generator for GsaGenerator {
    fn generate(&self, pop: &Population, ctx: &mut Ctx) -> Vec<Genotype> {
        assert!(pop.len() >= 2, "gen/gsa requires a population of at least 2 (pop_size={})", pop.len());
        let n = pop.len();
        let dim = floats(&pop.individuals[0]).len();

        // Persisted velocity: real blackboard state (GSA.m's own
        // `V=zeros(dim,N)` at t=0), bootstrapped to zeros the first time
        // this preset's blackboard sees it -- mirrors pso.rs's/ba.rs's
        // lazy-init-when-absent pattern. Owned entirely by this generator
        // (read, updated, written back below) -- no separate adapter.
        if !ctx.bb.contains("gsa/velocity") {
            ctx.bb.insert("gsa/velocity", vec![vec![0.0_f64; dim]; n]);
        }
        let mut velocity = ctx.bb.get::<Vec<Vec<f64>>>("gsa/velocity").unwrap().clone();

        let positions: Vec<&Vec<f64>> = (0..n).map(|i| floats(&pop.individuals[i])).collect();

        // No persisted best-so-far/attractor is used anywhere below -- see
        // the module doc's "Fbest/Lbest" delta note: the mechanism is a
        // pure function of the CURRENT population's fitness and positions.
        let mass = gsa_mass(&pop.fitness);

        let used = ctx.eval.used() as f64;
        let budget = ctx.eval.budget() as f64;
        let progress = if budget > 0.0 { (used / budget).clamp(0.0, 1.0) } else { 0.0 };
        let g = gsa_g(progress);
        let kbest = gsa_kbest_count(n, progress);
        let order = gsa_kbest_order(&mass);

        // Gfield.m: ALL per-(i,j,d) force draws happen first, completing the
        // WHOLE acceleration array, BEFORE move.m's per-(i,d) draws start
        // (see module doc's "SEPARATE loop" note) -- i outer / kbest-slot
        // middle / dim inner, matching the verified source's loop nesting.
        let mut accel = vec![vec![0.0_f64; dim]; n];
        #[allow(clippy::needless_range_loop)]
        for i in 0..n {
            let mut force_i = vec![0.0_f64; dim];
            for ii in 0..kbest {
                let j = order[ii];
                if j == i { continue; }
                let r_dist = euclidean(positions[i], positions[j]);
                for d in 0..dim {
                    let rnd = ctx.rng.next_f64();
                    force_i[d] += gsa_force_term(rnd, mass[j], positions[j][d], positions[i][d], r_dist);
                }
            }
            for d in 0..dim {
                accel[i][d] = g * force_i[d];
            }
        }

        // move.m: velocity + position update, a SEPARATE loop after Gfield
        // fully completes -- i outer / dim inner.
        let mut offspring: Vec<Genotype> = Vec::with_capacity(n);
        for i in 0..n {
            let x = positions[i];
            let xs: Vec<f64> = (0..dim).map(|d| {
                let r1 = ctx.rng.next_f64();
                let v_new = gsa_velocity_step(velocity[i][d], accel[i][d], r1);
                velocity[i][d] = v_new;
                x[d] + v_new
            }).collect();
            offspring.push(Genotype { blocks: vec![BlockValues::Float(xs)] });
        }

        ctx.bb.insert("gsa/velocity", velocity);
        offspring
    }

    fn meta(&self) -> ComponentMeta {
        ComponentMeta::new("gen/gsa", SupportedBlocks::Only(vec!["float"]))
            .with_provides(vec![StateReq::of::<Vec<Vec<f64>>>("gsa/velocity")])
            .with_min_pop(2)
    }
}

pub fn register(reg: &mut Registry) {
    reg.register_generator("gen/gsa", |p| Ok(Box::new(GsaGenerator::from_params(p)?)));
}

#[cfg(test)]
mod tests {
    use super::*;
    use sezgi_core::problem::{Problem, SphereShifted, Evaluator};
    use sezgi_core::rng::RngStream;
    use sezgi_core::state::Blackboard;

    fn g(xs: Vec<f64>) -> Genotype { Genotype { blocks: vec![BlockValues::Float(xs)] } }

    fn pop_nd(n: usize, dim: usize) -> Population {
        // Distinct fitness so mass ranking is unambiguous.
        Population {
            individuals: (0..n).map(|i| g((0..dim).map(|d| (i * dim + d) as f64 * 0.37 - 1.0).collect())).collect(),
            fitness: (0..n).map(|i| (n - i) as f64).collect(), // higher index = better (lower fitness)
        }
    }

    // ---- gsa_mass: normalization, best-gets-max-mass, degenerate guard ----

    #[test]
    fn mass_sums_to_one() {
        let m = gsa_mass(&[5.0, 1.0, 3.0, 9.0]);
        let sum: f64 = m.iter().sum();
        assert!((sum - 1.0).abs() < 1e-12, "masses must sum to 1, got {sum}");
    }

    #[test]
    fn best_fitness_gets_max_mass() {
        // Minimization: fitness 1.0 is best (lowest), 9.0 is worst (highest).
        let m = gsa_mass(&[5.0, 1.0, 3.0, 9.0]);
        let best_idx = m.iter().enumerate().max_by(|a, b| a.1.total_cmp(b.1)).unwrap().0;
        assert_eq!(best_idx, 1, "the lowest-fitness agent must receive the maximum mass");
        // worst (index 3, fitness 9.0) must receive the minimum (raw 0, so
        // exactly 0 after normalization too).
        assert_eq!(m[3], 0.0, "the highest-fitness (worst) agent must receive exactly zero mass");
    }

    #[test]
    fn sole_distinct_best_captures_the_entire_unit_mass_when_the_rest_tie_at_worst() {
        // Three agents tied at the worst fitness (9.0), one distinct best
        // (1.0): raw m = [(9-9)/(1-9), (1-9)/(1-9), (9-9)/(1-9), (9-9)/(1-9)]
        //             = [0.0, 1.0, 0.0, 0.0], sum=1.0 -> normalization is a
        // no-op here, so the sole best agent's mass is EXACTLY 1.0 and every
        // tied-worst agent's mass is EXACTLY 0.0.
        let m = gsa_mass(&[9.0, 1.0, 9.0, 9.0]);
        assert_eq!(m, vec![0.0, 1.0, 0.0, 0.0]);
    }

    #[test]
    fn degenerate_equal_fitness_gives_uniform_masses() {
        // Fmax==Fmin: the source's own guard sets every raw mass to 1, THEN
        // normalizes -- so every agent ends up with exactly 1/N, not "mass
        // 1" and not zero/an error.
        let m = gsa_mass(&[7.0, 7.0, 7.0, 7.0]);
        for &v in &m {
            assert!((v - 0.25).abs() < 1e-12, "degenerate equal-fitness case must give uniform 1/N masses, got {v}");
        }
    }

    #[test]
    fn single_agent_mass_is_one() {
        let m = gsa_mass(&[42.0]);
        assert_eq!(m, vec![1.0]);
    }

    // ---- gsa_g: eq. 28 schedule endpoints ----

    #[test]
    fn g_schedule_endpoints() {
        assert_eq!(gsa_g(0.0), 100.0, "progress=0 must give exactly G0=100.0");
        let expected_end = 100.0 * (-20.0_f64).exp();
        assert_eq!(gsa_g(1.0), expected_end);
        assert!(gsa_g(1.0) < 1e-6, "progress=1 must give a very small G, got {}", gsa_g(1.0));
        assert!(gsa_g(1.0) > 0.0, "G must remain strictly positive even at progress=1");
    }

    #[test]
    fn g_is_monotonically_decreasing() {
        let g0 = gsa_g(0.0);
        let g_mid = gsa_g(0.5);
        let g1 = gsa_g(1.0);
        assert!(g0 > g_mid && g_mid > g1, "G must strictly decrease as progress increases");
    }

    // ---- gsa_kbest_count: eq. 21 schedule endpoints ----

    #[test]
    fn kbest_count_schedule_endpoints() {
        assert_eq!(gsa_kbest_count(30, 0.0), 30, "progress=0 must select ALL agents");
        // percent = 2 + (1-1)*98 = 2; count = round(30*2/100) = round(0.6) = 1.
        assert_eq!(gsa_kbest_count(30, 1.0), 1, "progress=1 must collapse to the final 2 percent");
    }

    #[test]
    fn kbest_count_can_round_to_zero_for_small_n_no_floor() {
        // VERIFIED against Gfield.m: no minimum-1 clamp. n=2, progress=1:
        // percent=2, count=round(2*0.02)=round(0.04)=0.
        assert_eq!(gsa_kbest_count(2, 1.0), 0,
            "the source has no floor on kbest_count -- it can legitimately reach 0");
    }

    #[test]
    fn kbest_count_intermediate() {
        // n=10, progress=0.5: percent = 2 + 0.5*98 = 51; count = round(10*51/100) = round(5.1) = 5.
        assert_eq!(gsa_kbest_count(10, 0.5), 5);
    }

    // ---- gsa_kbest_order: descending mass, stable ties ----

    #[test]
    fn kbest_order_descending_by_mass() {
        let order = gsa_kbest_order(&[0.1, 0.5, 0.2, 0.9]);
        assert_eq!(order, vec![3, 1, 2, 0]);
    }

    #[test]
    fn kbest_order_ties_keep_original_order() {
        // indices 0 and 2 tie at mass 0.5 -- stable sort must keep 0 before 2.
        let order = gsa_kbest_order(&[0.5, 0.1, 0.5, 0.9]);
        assert_eq!(order, vec![3, 0, 2, 1]);
    }

    // ---- gsa_force_term: hand-derived arithmetic ----

    #[test]
    fn force_term_hand_derived() {
        // rand=0.5, mass_j=0.8, xj_d=10.0, xi_d=2.0, r_dist=8.0:
        // 0.5 * 0.8 * (10.0-2.0) / (8.0+eps) = 0.4*8.0/(8.0+eps) ~= 0.4
        // (extremely close to 0.4 but not bit-exact due to the +eps guard).
        let v = gsa_force_term(0.5, 0.8, 10.0, 2.0, 8.0);
        let expected = 0.5 * 0.8 * 8.0 / (8.0 + f64::EPSILON);
        assert_eq!(v, expected);
        assert!((v - 0.4).abs() < 1e-14);
    }

    #[test]
    fn force_term_is_exactly_zero_when_source_mass_is_zero() {
        // No M_i in the formula, but a ZERO M_j always kills the term
        // exactly, regardless of the rand draw or the distance.
        for rand in [0.0, 0.3, 0.999999] {
            assert_eq!(gsa_force_term(rand, 0.0, 100.0, -100.0, 3.0), 0.0);
        }
    }

    // ---- gsa_velocity_step: multiplicative-decay-then-additive-accel ----

    #[test]
    fn velocity_step_hand_derived() {
        // v_old=4.0, accel=1.5, r1=0.25 -> v_new = 0.25*4.0 + 1.5 = 1.0+1.5 = 2.5.
        assert_eq!(gsa_velocity_step(4.0, 1.5, 0.25), 2.5);
        // v_old=0.0 (bootstrap case) -> v_new = accel exactly, regardless of r1.
        assert_eq!(gsa_velocity_step(0.0, 7.0, 0.9), 7.0);
        assert_eq!(gsa_velocity_step(0.0, 7.0, 0.0), 7.0);
    }

    // ---- GsaGenerator: force antisymmetry-ish sanity, 2-agent 1-D, full arithmetic ----

    #[test]
    fn zero_mass_agent_exerts_zero_force_and_does_not_move_the_better_agent() {
        // n=2, dim=1. agent 0: x=0.0, fitness=10.0 (worse). agent 1: x=5.0,
        // fitness=1.0 (better). Mass: Fmax=10, Fmin=1, best=1, worst=10 ->
        // raw m0=(10-10)/(1-10)=0/-9=0.0; raw m1=(1-10)/(1-10)=1.0. sum=1.0
        // exactly (no floating error) -> M0=0.0, M1=1.0 EXACTLY.
        //
        // ds = order by mass descending = [1, 0]. progress=0 (fresh
        // evaluator, used=0) -> kbest_percent=100 -> kbest_count=2 (both).
        //
        // Force on agent 0 (i=0): ii=0 -> j=ds[0]=1 != 0 -> R=|0-5|=5.0,
        //   1 draw (dim=1): force0 = rand0 * M[1] * (5.0-0.0)/(5.0+eps)
        //                          = rand0 * 1.0 * 5.0/(5.0+eps).
        //   ii=1 -> j=ds[1]=0 == 0 -> SKIPPED (no draw).
        // Force on agent 1 (i=1): ii=0 -> j=ds[0]=1 == 1 -> SKIPPED.
        //   ii=1 -> j=ds[1]=0 != 1 -> R=|5-0|=5.0, 1 draw (dim=1):
        //     force1 = rand1 * M[0] * (0.0-5.0)/(5.0+eps) = rand1 * 0.0 * (...) = 0.0
        //     EXACTLY, regardless of rand1's value, because M[0]=0.0 kills the term.
        // accel1 = G * 0.0 = 0.0 exactly.
        //
        // move.m (separate loop, after Gfield fully completes): velocity
        // bootstraps to [[0.0],[0.0]]. v1_new = r1_move_1*0.0 + 0.0 = 0.0
        // exactly -> x1_new = 5.0 + 0.0 = 5.0 EXACTLY: the heavier/better
        // agent does not move this generation, regardless of ANY random draw.
        let dim = 1;
        let p = SphereShifted::new(vec![0.0; dim], -1000.0, 1000.0);
        let space = p.space();
        let mut evaluator = Evaluator::new(&p, 100_000);
        let mut rng = RngStream::from_master(11, &[]);
        let mut bb = Blackboard::new();
        let pop = Population {
            individuals: vec![g(vec![0.0]), g(vec![5.0])],
            fitness: vec![10.0, 1.0],
        };

        let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 0 };
        let off = GsaGenerator.generate(&pop, &mut ctx);

        assert_eq!(floats(&off[1])[0], 5.0,
            "agent 1 (mass 1.0, only neighbor has mass 0.0) must not move at all this generation");
        // agent 0 DID move (accel0 is nonzero with overwhelming probability
        // -- rand0 is continuous on [0,1), so rand0==0 has probability 0).
        assert_ne!(floats(&off[0])[0], 0.0,
            "agent 0 (mass 0.0, pulled by agent 1's mass 1.0) must have moved");
    }

    #[test]
    fn zero_mass_agent_exact_displacement_matches_hand_traced_replay() {
        // Same 2-agent fixture as above, but replaying the EXACT draw
        // sequence via a twin stream to confirm agent 0's exact landing
        // position (full arithmetic, not just the sign/nonzero sanity
        // above). Draw order: Gfield's draws first (i=0's single draw,
        // since i=1's is skipped... wait: i=0 draws once (j=1), i=1 draws
        // once too (j=0) -- both agents DO consume exactly one draw each in
        // Gfield, it is only agent 1's CONTRIBUTION that is exactly zero
        // (multiplied by M[0]=0.0), not the draw itself. THEN move's draws
        // (one per agent, dim=1).
        let dim = 1;
        let p = SphereShifted::new(vec![0.0; dim], -1000.0, 1000.0);
        let space = p.space();
        let mut evaluator = Evaluator::new(&p, 100_000);
        let mut rng = RngStream::from_master(11, &[]);
        let rng_before = rng.clone();
        let mut bb = Blackboard::new();
        let pop = Population {
            individuals: vec![g(vec![0.0]), g(vec![5.0])],
            fitness: vec![10.0, 1.0],
        };

        let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 0 };
        let off = GsaGenerator.generate(&pop, &mut ctx);

        let mut twin = rng_before;
        // Gfield: i=0 (j=1 != 0) draws rand0; i=1 (j=0 != 1) draws rand1.
        let rand0 = twin.next_f64();
        let _rand1 = twin.next_f64();
        let g0 = gsa_g(0.0);
        let force0 = gsa_force_term(rand0, 1.0, 5.0, 0.0, 5.0);
        let accel0 = g0 * force0;
        // move: i=0 draws r1_move_0 first, then i=1 draws r1_move_1.
        let r1_move_0 = twin.next_f64();
        let v0_new = gsa_velocity_step(0.0, accel0, r1_move_0);
        let x0_new = 0.0 + v0_new;

        assert_eq!(floats(&off[0])[0], x0_new,
            "agent 0's exact landing position must match the hand-traced replay");
    }

    // ---- twin-stream draw count, crafted (n, dim), progress=0 (kbest=n) ----

    #[test]
    fn draw_count_at_progress_zero_is_n_squared_times_dim() {
        // At progress=0, kbest_count == n (ALL agents), so for every target
        // agent i, exactly one of the n slots in `order` equals i (skipped,
        // no draw) and the other (n-1) each consume `dim` draws in Gfield --
        // n*(n-1)*dim total, REGARDLESS of the mass ranking (order is just
        // some permutation of 0..n). Then move.m consumes n*dim more draws.
        // Total = n*(n-1)*dim + n*dim = n^2*dim.
        let n = 5; let dim = 3;
        let p = SphereShifted::new(vec![0.0; dim], -5.0, 5.0);
        let space = p.space();
        let pop = pop_nd(n, dim);

        let mut rng = RngStream::from_master(7, &[]);
        let rng_before = rng.clone();
        let mut evaluator = Evaluator::new(&p, 1000); // fresh: used()=0 -> progress=0
        let mut bb = Blackboard::new();
        {
            let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 0 };
            let off = GsaGenerator.generate(&pop, &mut ctx);
            assert_eq!(off.len(), n);
        }

        let expected_draws = n * n * dim;
        let mut twin = rng_before;
        for _ in 0..expected_draws { twin.next_f64(); }
        assert_eq!(rng.next_f64(), twin.next_f64(),
            "gen/gsa at progress=0 must consume exactly n^2*dim draws (n={n}, dim={dim}): n*(n-1)*dim in Gfield + n*dim in move");
    }

    // ---- determinism ----

    #[test]
    fn determinism_same_seed_bit_identical() {
        let n = 6; let dim = 4;
        let p = SphereShifted::new(vec![0.0; dim], -5.0, 5.0);
        let space = p.space();
        let pop = pop_nd(n, dim);

        let run = || {
            let mut evaluator = Evaluator::new(&p, 1000);
            let mut rng = RngStream::from_master(42, &[]);
            let mut bb = Blackboard::new();
            let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 0 };
            GsaGenerator.generate(&pop, &mut ctx)
        };

        let a = run();
        let b = run();
        for (ga, gb) in a.iter().zip(b.iter()) {
            assert_eq!(floats(ga), floats(gb), "same seed must produce bit-identical offspring");
        }
    }

    // ---- min_pop ----

    #[test]
    fn min_pop_below_2_panics() {
        let n = 1; let dim = 2;
        let p = SphereShifted::new(vec![0.0; dim], -5.0, 5.0);
        let space = p.space();
        let pop = pop_nd(n, dim);
        let mut evaluator = Evaluator::new(&p, 100);
        let mut rng = RngStream::from_master(1, &[]);
        let mut bb = Blackboard::new();
        let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 0 };
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            GsaGenerator.generate(&pop, &mut ctx)
        }));
        assert!(result.is_err(), "gen/gsa must reject pop_size < 2 at runtime as a backstop");
    }

    // ---- bootstrap ----

    #[test]
    fn bootstrap_seeds_velocity_to_zeros_when_absent() {
        let n = 4; let dim = 3;
        let p = SphereShifted::new(vec![0.0; dim], -5.0, 5.0);
        let space = p.space();
        let pop = pop_nd(n, dim);
        let mut evaluator = Evaluator::new(&p, 1000);
        let mut rng = RngStream::from_master(1, &[]);
        let mut bb = Blackboard::new();
        assert!(!bb.contains("gsa/velocity"));

        let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 0 };
        GsaGenerator.generate(&pop, &mut ctx);

        let velocity = ctx.bb.get::<Vec<Vec<f64>>>("gsa/velocity").unwrap();
        assert_eq!(velocity.len(), n);
        for row in velocity { assert_eq!(row.len(), dim); }
    }

    // ---- velocity blackboard round-trip across 2 generations, hand-traced ----

    #[test]
    fn velocity_state_round_trips_and_accumulates_across_two_generations() {
        // n=2, dim=1, same fixture shape as the force-sanity test above.
        // Generation 0: v_old=[0,0] (bootstrap) -> gen0's v is EXACTLY the
        // gen0 acceleration (r1*0 + accel = accel, for ANY r1). Generation
        // 1: v_old is gen0's PERSISTED (nonzero, for agent 0 at least)
        // velocity -- gen1's v genuinely depends on it (r1_gen1 * v_gen0 +
        // accel_gen1), a real accumulation, not a reset.
        let dim = 1;
        let p = SphereShifted::new(vec![0.0; dim], -1000.0, 1000.0);
        let space = p.space();
        let mut evaluator = Evaluator::new(&p, 100_000);
        let mut rng = RngStream::from_master(3, &[]);
        let mut bb = Blackboard::new();

        let mut pop = Population {
            individuals: vec![g(vec![0.0]), g(vec![5.0])],
            fitness: vec![10.0, 1.0],
        };

        // Generation 0.
        let rng_before_gen0 = rng.clone();
        let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 0 };
        let off0 = GsaGenerator.generate(&pop, &mut ctx);
        let velocity_after_gen0 = ctx.bb.get::<Vec<Vec<f64>>>("gsa/velocity").unwrap().clone();

        // Hand-trace generation 0 (mass, order, g, kbest are identical to
        // the force-sanity test above: M=[0.0,1.0], order=[1,0], kbest=2,
        // G=gsa_g(0.0)=100.0).
        let mut twin = rng_before_gen0;
        let rand0_gen0 = twin.next_f64(); // Gfield i=0 (j=1)
        let rand1_gen0 = twin.next_f64(); // Gfield i=1 (j=0)
        let g0 = gsa_g(0.0);
        let accel0_gen0 = g0 * gsa_force_term(rand0_gen0, 1.0, 5.0, 0.0, 5.0);
        let accel1_gen0 = g0 * gsa_force_term(rand1_gen0, 0.0, 0.0, 5.0, 5.0);
        assert_eq!(accel1_gen0, 0.0);
        let r1_move_0_gen0 = twin.next_f64();
        let r1_move_1_gen0 = twin.next_f64();
        let v0_gen0 = gsa_velocity_step(0.0, accel0_gen0, r1_move_0_gen0);
        let v1_gen0 = gsa_velocity_step(0.0, accel1_gen0, r1_move_1_gen0);
        assert_eq!(v1_gen0, 0.0, "v_old=0 * anything + accel(0.0) = 0.0 exactly");

        assert_eq!(velocity_after_gen0, vec![vec![v0_gen0], vec![v1_gen0]],
            "velocity after generation 0 must be exactly (r1*0 + accel) per agent");
        assert_eq!(floats(&off0[0])[0], 0.0 + v0_gen0);
        assert_eq!(floats(&off0[1])[0], 5.0 + v1_gen0);

        // replace/generational (hand-applied): pop <- off0, with made-up
        // fresh fitness (bat 1 still best) to drive generation 1's masses.
        pop.individuals = off0;
        pop.fitness = vec![7.0, 0.5];

        // Generation 1: velocity must be READ BACK (not re-bootstrapped)
        // and used as v_old in gsa_velocity_step -- genuinely different
        // from a fresh-zero run since v0_gen0 != 0.0 (overwhelmingly, since
        // rand0_gen0 is continuous).
        assert_ne!(v0_gen0, 0.0, "sanity: agent 0's gen-0 velocity must be nonzero for this test to be meaningful");
        let rng_before_gen1 = rng.clone();
        let mut ctx = Ctx { space, rng: &mut rng, eval: &mut evaluator, bb: &mut bb, iteration: 1 };
        let off1 = GsaGenerator.generate(&pop, &mut ctx);
        let velocity_after_gen1 = ctx.bb.get::<Vec<Vec<f64>>>("gsa/velocity").unwrap().clone();

        // Re-derive generation 1's mass/order/G/kbest from the NEW fitness
        // [7.0, 0.5] (agent 1, x=off0[1], still best) and NEW positions
        // (off0[0], off0[1]).
        let x1_0 = floats(&pop.individuals[0])[0];
        let x1_1 = floats(&pop.individuals[1])[0];
        // mass: Fmax=7.0, Fmin=0.5, best=0.5, worst=7.0.
        // raw m0=(7.0-7.0)/(0.5-7.0)=0.0; raw m1=(0.5-7.0)/(0.5-7.0)=1.0. sum=1.0.
        let mut twin1 = rng_before_gen1;
        let rand0_gen1 = twin1.next_f64();
        let rand1_gen1 = twin1.next_f64();
        let g1_val = gsa_g(0.0); // progress still 0 (this fresh Evaluator's used() is untouched by hand tracing)
        let r_dist1 = (x1_1 - x1_0).abs();
        let accel0_gen1 = g1_val * gsa_force_term(rand0_gen1, 1.0, x1_1, x1_0, r_dist1);
        let accel1_gen1 = g1_val * gsa_force_term(rand1_gen1, 0.0, x1_0, x1_1, r_dist1);
        assert_eq!(accel1_gen1, 0.0);
        let r1_move_0_gen1 = twin1.next_f64();
        let r1_move_1_gen1 = twin1.next_f64();
        // MUST use v0_gen0 as v_old (accumulated), not reset to 0.
        let v0_gen1 = gsa_velocity_step(v0_gen0, accel0_gen1, r1_move_0_gen1);
        let v1_gen1 = gsa_velocity_step(v1_gen0, accel1_gen1, r1_move_1_gen1);

        assert_eq!(velocity_after_gen1, vec![vec![v0_gen1], vec![v1_gen1]],
            "generation 1's velocity must ACCUMULATE on top of generation 0's persisted state");
        assert_eq!(floats(&off1[0])[0], x1_0 + v0_gen1);
        assert_eq!(floats(&off1[1])[0], x1_1 + v1_gen1);
        assert_ne!(velocity_after_gen1[0][0], v0_gen0,
            "sanity: velocity must actually have changed across the two generations (not silently frozen)");
    }
}
