# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib sezgi, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_sezgi__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_sezgi__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Version of the underlying sezgi Rust core.
#'
#' @returns A character scalar with the crate version string.
#' @export
`sezgi_version` <- function() {
  .Call(savvy_sezgi_version__impl)
}

#' Builds one `sezgi_stats::PaperPackage` PER DISTINCT BUDGET present in a
#' `sz_run_experiment()` data.frame's columns, in ascending budget order --
#' see `sezgi_bench::reporting::per_budget_packages`. Per Piotrowski et al.
#' (2025), algorithm rankings can flip across budgets, so this makes
#' multi-budget reporting the default rather than a single, arbitrarily
#' chosen budget's report.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults is the hand-written wrapper `sz_per_budget_packages()`
#' in `R/experiment.R`, which extracts these columns from a data.frame and
#' calls this function.
#'
#' @param algo Character vector (the `algo` column).
#' @param fid,dim,instance,seed,budget_col,best_f,f_opt,evals Numeric
#'   vectors (the correspondingly-named columns).
#' @param rope Region of practical equivalence half-width (>= 0) for the
#'   Bayesian signed-rank test, forwarded to every budget's package.
#' @param samples Number of Monte Carlo samples per pair (double, cast to
#'   `u64`).
#' @param seed Master RNG seed (double, cast to `u64`), forwarded to every
#'   budget's package.
#' @param aggregate `"mean"` or `"median"`.
#' @returns A named list, one entry per distinct budget in ascending order,
#'   named by the budget (as a string); each value has exactly the shape
#'   `sz_stats_paper_package_raw()` returns.
`sz_per_budget_packages_raw` <- function(`algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `rope`, `samples`, `master_seed`, `aggregate`) {
  .Call(savvy_sz_per_budget_packages_raw__impl, `algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `rope`, `samples`, `master_seed`, `aggregate`)
}

#' Builds a (mu/mu_w,lambda)-CMA-ES algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (lambda).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cmaes` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_cmaes__impl, `pop_size`, `budget`)
}

#' Builds a CMA-ES with IPOP-style stagnation restarts algorithm spec as
#' JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (determines the initial population size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cmaes_ipop` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_cmaes_ipop__impl, `dim`, `budget`)
}

#' Builds a DE/best/1/bin algorithm spec (uniform init, clamp boundary,
#' one-to-one-greedy replacement) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_de_best_1` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_de_best_1__impl, `pop_size`, `budget`)
}

#' Builds a DE/rand/1/bin algorithm spec (uniform init, clamp boundary,
#' one-to-one-greedy replacement) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_de_rand_1` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_de_rand_1__impl, `pop_size`, `budget`)
}

#' Builds a (mu/mu_w,lambda)-ES algorithm spec (mutation step drawn from
#' `dist`) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL`/string default in the generated signature).
#' The public R entry point with R-native defaults is the hand-written
#' wrapper `sz_preset_es_mu_plus_lambda()` in `R/presets.R`, which calls this
#' function -- same raw/wrapper pattern as `sz_run_experiment()` /
#' `sz_run_experiment_raw()` and `sz_stats_bayesian_signed_rank()` /
#' `sz_stats_bayesian_signed_rank_raw()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @param dist Mutation distribution: one of `"uniform"`, `"gaussian"`,
#'   `"cauchy"`, `"levy"`, `"student_t"`, `"laplace"`.
#' @param mean Gaussian mean (used only when `dist = "gaussian"`).
#' @param sigma Gaussian std-dev (used only when `dist = "gaussian"`).
#' @param loc Cauchy/Laplace location (used only when `dist` is `"cauchy"`
#'   or `"laplace"`).
#' @param scale Cauchy/Laplace scale (used only when `dist` is `"cauchy"`
#'   or `"laplace"`).
#' @param alpha Levy stability parameter (used only when `dist = "levy"`).
#' @param nu Student-t degrees of freedom (used only when `dist =
#'   "student_t"`).
#' @returns A character scalar with the algorithm spec as JSON.
`sz_preset_es_mu_plus_lambda_raw` <- function(`pop_size`, `budget`, `dist`, `mean`, `sigma`, `loc`, `scale`, `alpha`, `nu`) {
  .Call(savvy_sz_preset_es_mu_plus_lambda_raw__impl, `pop_size`, `budget`, `dist`, `mean`, `sigma`, `loc`, `scale`, `alpha`, `nu`)
}

#' Builds a real-coded GA (SBX crossover, polynomial mutation) algorithm spec
#' as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_ga_real` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_ga_real__impl, `pop_size`, `budget`)
}

#' Builds a jDE algorithm spec (self-adaptive F/CR DE) as JSON, ready to pass
#' to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_jde` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_jde__impl, `pop_size`, `budget`)
}

#' Builds an L-SHADE algorithm spec (population linearly reduced from
#' `18 * dim`) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (determines the initial population size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_lshade` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_lshade__impl, `dim`, `budget`)
}

#' Builds a Nelder-Mead simplex algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (population size is fixed to `dim + 1`).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_nelder_mead` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_nelder_mead__impl, `dim`, `budget`)
}

#' Builds a PSO (Clerc-Kennedy constriction) algorithm spec as JSON, ready to
#' pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (swarm size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_pso` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_pso__impl, `pop_size`, `budget`)
}

#' Builds a random search algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (resampled uniformly each generation).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_random_search` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_random_search__impl, `pop_size`, `budget`)
}

#' Builds a simulated annealing (Metropolis, geometric cooling) algorithm
#' spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_sa` <- function(`budget`) {
  .Call(savvy_sz_preset_sa__impl, `budget`)
}

#' Builds a SHADE algorithm spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_shade` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_shade__impl, `pop_size`, `budget`)
}

#' Builds a `sezgi_stats`-shaped results matrix for one `budget` from a
#' `sz_run_experiment()` data.frame's columns -- see
#' `sezgi_bench::reporting::results_matrix`.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults is the hand-written wrapper `sz_results_matrix()` in
#' `R/experiment.R`, which extracts these columns from a data.frame and
#' calls this function.
#'
#' @param algo Character vector (the `algo` column).
#' @param fid,dim,instance,seed,budget_col,best_f,f_opt,evals Numeric
#'   vectors (the correspondingly-named columns; `budget_col` avoids a name
#'   clash with the scalar `budget` argument below).
#' @param budget Only rows with this budget are used.
#' @param aggregate `"mean"` or `"median"`.
#' @returns A named list with `algo_names` (character vector),
#'   `problem_labels` (character vector, `f{fid}d{dim}i{instance}`), and
#'   `matrix` (numeric matrix, rows = problems, columns = algorithms).
`sz_results_matrix_raw` <- function(`algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `budget`, `aggregate`) {
  .Call(savvy_sz_results_matrix_raw__impl, `algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `budget`, `aggregate`)
}

#' Runs an [`ExperimentSpec`] (parsed from `spec_toml`) and returns its
#' `RunRecord`s as a data.frame. This mirrors py-sezgi's `run_experiment`
#' exactly (see `py-sezgi/src/lib.rs`): `journal=None` runs via
#' `run_experiment_parallel`/`run_experiment_sequential` (chosen by
#' `parallel`); `journal=Some(path)` runs via `run_experiment_with_checkpoint`,
#' which resumes from -- and appends to -- an existing journal file at
#' `path`.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults (`parallel = TRUE`) is the hand-written wrapper
#' `sz_run_experiment()` in `R/experiment.R`, which calls this function.
#'
#' @param spec_toml Experiment spec as TOML.
#' @param parallel Whether to run in parallel via rayon.
#' @param journal Optional path to a checkpoint journal file.
#' @param threads Optional rayon thread-pool size. `usize` is not a
#'   supported savvy scalar arg type, so this comes in as `i32` and is cast;
#'   negative values are rejected explicitly (savvy has no unsigned integer
#'   scalar type to enforce this at the signature level).
#' @returns A data.frame with one row per run.
`sz_run_experiment_raw` <- function(`spec_toml`, `parallel`, `journal` = NULL, `threads` = NULL) {
  .Call(savvy_sz_run_experiment_raw__impl, `spec_toml`, `parallel`, `journal`, `threads`)
}

#' Runs an algorithm spec on a BBOB problem and returns the result.
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_de_rand_1()`).
#' @param fid BBOB function id (>= 1).
#' @param dim Problem dimension (>= 1).
#' @param instance BBOB instance id (>= 1).
#' @param master_seed Master RNG seed.
#' @param run_id Run id (mixed into the seed for independent replicate streams).
#' @returns A named list with `best_f` (double), `evals` (double), and
#'   `best_x` (double vector).
#' @export
`sz_solve_bbob` <- function(`spec_json`, `fid`, `dim`, `instance`, `master_seed`, `run_id`) {
  .Call(savvy_sz_solve_bbob__impl, `spec_json`, `fid`, `dim`, `instance`, `master_seed`, `run_id`)
}

#' Bayesian signed-rank test with a region of practical equivalence (ROPE)
#' (Dirichlet-weighted Monte Carlo; see `sezgi_stats::bayesian_signed_rank`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults is
#' the hand-written wrapper `sz_stats_bayesian_signed_rank()` in
#' `R/stats.R`, which calls this function.
#'
#' @param a Numeric vector.
#' @param b Numeric vector, same length as `a`.
#' @param rope Region of practical equivalence half-width (>= 0).
#' @param samples Number of Monte Carlo samples. Passed to R as a double
#'   (savvy has no unsigned integer scalar arg type) and cast to `u64`
#'   after checking it is non-negative and finite.
#' @param seed Master RNG seed, passed through unchanged (`u64` via `f64`
#'   cast) — the same `(a, b, rope, samples, seed)` always produces a
#'   bit-identical result, since R calls the exact same seeded Rust core as
#'   Python and Rust.
#' @returns A named list with `p_left`, `p_rope`, `p_right` (mirrors
#'   py-sezgi's `stats_bayesian_signed_rank()` dict keys exactly).
`sz_stats_bayesian_signed_rank_raw` <- function(`a`, `b`, `rope`, `samples`, `seed`) {
  .Call(savvy_sz_stats_bayesian_signed_rank_raw__impl, `a`, `b`, `rope`, `samples`, `seed`)
}

#' Cliff's delta effect size for two independent (unpaired) samples.
#'
#' @param a Numeric vector.
#' @param b Numeric vector.
#' @returns A numeric scalar in `[-1, 1]`.
#' @export
`sz_stats_cliffs_delta` <- function(`a`, `b`) {
  .Call(savvy_sz_stats_cliffs_delta__impl, `a`, `b`)
}

#' Qualitative magnitude label for a Cliff's delta value (Romano et al. 2006
#' thresholds).
#'
#' @param delta A Cliff's delta value (as returned by
#'   `sz_stats_cliffs_delta()`).
#' @returns A character scalar: one of `"negligible"`, `"small"`,
#'   `"medium"`, `"large"`.
#' @export
`sz_stats_cliffs_magnitude` <- function(`delta`) {
  .Call(savvy_sz_stats_cliffs_magnitude__impl, `delta`)
}

#' Runs the Friedman test on a results matrix.
#'
#' @param m A numeric matrix, rows = problems, columns = algorithms, lower
#'   is better (e.g. built with `rbind()` or `matrix()`).
#' @returns A named list with `statistic`, `p_value`, `mean_ranks` (mirrors
#'   py-sezgi's `stats_friedman()` dict keys exactly).
#' @export
`sz_stats_friedman` <- function(`m`) {
  .Call(savvy_sz_stats_friedman__impl, `m`)
}

#' Computes a comprehensive statistical analysis package for algorithm
#' comparison (Friedman, Nemenyi CD, pairwise Wilcoxon+Holm, Cliff's delta,
#' Bayesian signed-rank, Plackett-Luce, and LaTeX tables; see
#' `sezgi_stats::paper_package`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults is
#' the hand-written wrapper `sz_stats_paper_package()` in `R/stats.R`, which
#' calls this function.
#'
#' @param algo_names Character vector of algorithm names.
#' @param problem_names Character vector of problem names.
#' @param m A numeric matrix, rows = problems (`length(problem_names)`),
#'   columns = algorithms (`length(algo_names)`), lower is better.
#' @param rope Region of practical equivalence half-width (>= 0) for the
#'   Bayesian signed-rank test.
#' @param samples Number of Monte Carlo samples per pair for the Bayesian
#'   signed-rank test (double, cast to `u64`; see
#'   `sz_stats_bayesian_signed_rank_raw()`).
#' @param seed Master RNG seed (double, cast to `u64`); per-pair seeds are
#'   `seed + pair_index` (wrapping), matching `sezgi_stats::paper_package`.
#' @returns A named list with `friedman` (nested list: `statistic`,
#'   `p_value`, `mean_ranks`), `nemenyi_cd`, `pairwise_wilcoxon_holm` (list
#'   of length-3 numeric vectors `c(i, j, adjusted_p)`, 0-based algorithm
#'   indices, i < j), `cliffs` (list of length-3 numeric vectors `c(i, j,
#'   delta)`), `bayes` (list of 3-element lists `list(i, j, bayes_result)`
#'   where `bayes_result` has `p_left`/`p_rope`/`p_right`),
#'   `plackett_luce` (nested list: `worths`, `p_best`, `iterations`),
#'   `latex_summary`, `latex_tests` (mirrors py-sezgi's
#'   `stats_paper_package()` dict keys exactly).
`sz_stats_paper_package_raw` <- function(`algo_names`, `problem_names`, `m`, `rope`, `samples`, `seed`) {
  .Call(savvy_sz_stats_paper_package_raw__impl, `algo_names`, `problem_names`, `m`, `rope`, `samples`, `seed`)
}

#' Plackett-Luce maximum-likelihood ranking (Hunter 2004 MM algorithm; see
#' `sezgi_stats::plackett_luce`).
#'
#' @param rankings A `list` of integer (or integer-valued numeric) vectors,
#'   each a full ranking of the same `k` items as **1-based item ids**
#'   (R's natural indexing; e.g. `list(c(1, 2, 3), c(2, 1, 3))` for k = 3
#'   items, best first). Converted to 0-based indices before calling the
#'   Rust core, which expects a permutation of `0..k`.
#' @returns A named list with `worths`, `p_best`, `iterations` (mirrors
#'   py-sezgi's `stats_plackett_luce()` dict keys exactly).
#' @export
`sz_stats_plackett_luce` <- function(`rankings`) {
  .Call(savvy_sz_stats_plackett_luce__impl, `rankings`)
}

#' Wilcoxon signed-rank test for two paired samples (Pratt zero-handling and
#' tie correction; see `sezgi_stats::wilcoxon_signed_rank`).
#'
#' @param a Numeric vector.
#' @param b Numeric vector, same length as `a`.
#' @returns A named list with `w_statistic`, `z`, `p_value`, `n_effective`,
#'   `method` (`"exact"` or `"normal_approx"`; mirrors py-sezgi's
#'   `stats_wilcoxon()` dict keys exactly). `"exact"` is used when
#'   `n_effective <= 25` and there are no zero differences or tied `|d|`
#'   ranks; see `sezgi_stats::wilcoxon_signed_rank`'s doc comment for the
#'   full eligibility rule (the exact p-value formula is semver-pinned).
#' @export
`sz_stats_wilcoxon` <- function(`a`, `b`) {
  .Call(savvy_sz_stats_wilcoxon__impl, `a`, `b`)
}


