# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib sezgi, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_sezgi__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_sezgi__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Version of the underlying sezgi Rust core.
#'
#' @returns A character scalar with the crate version string.
#' @export
`sezgi_version` <- function() {
  .Call(savvy_sezgi_version__impl)
}

#' Bayesian Plackett-Luce posterior via Gibbs sampling (Caron & Doucet
#' 2012 latent exponential-race augmentation; see
#' `sezgi_stats::bayesian_plackett_luce`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has
#' no way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults
#' is the hand-written wrapper `sz_bayesian_plackett_luce()` in
#' `R/stats.R`, which calls this function -- same raw/wrapper pattern as
#' `sz_stats_bayesian_signed_rank()` / `sz_stats_bayesian_signed_rank_raw()`.
#'
#' @param rankings A `list` of integer (or integer-valued numeric)
#'   vectors, each a full ranking of the same `k` items as **1-based item
#'   ids** (same convention as `sz_stats_plackett_luce()`; converted via
#'   the SAME `rankings_from_list()` helper). Best (rank 1) first.
#' @param samples Number of post-burn-in Gibbs iterations to record
#'   (double, cast to `u64`).
#' @param burn_in Number of initial Gibbs iterations to discard (double,
#'   cast to `u64`).
#' @param seed Master RNG seed, passed through unchanged (`u64` via `f64`
#'   cast) -- the same `(rankings, samples, burn_in, seed)` always
#'   produces a bit-identical result, since R calls the exact same seeded
#'   Rust core as Python and Rust.
#' @returns A named list with `mean_worths`, `ci_low`, `ci_high`,
#'   `p_best`, `samples` (mirrors py-sezgi's
#'   `stats_bayesian_plackett_luce()` dict keys exactly).
#' @noRd
`sz_bayesian_plackett_luce_raw` <- function(`rankings`, `samples`, `burn_in`, `seed`) {
  .Call(savvy_sz_bayesian_plackett_luce_raw__impl, `rankings`, `samples`, `burn_in`, `seed`)
}

#' Central-bias scan: run `spec_json` on paired centered/shifted BBOB
#' conditions and test whether its performance gap differs between them --
#' see [`sezgi_bias::central::central_bias_scan`].
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults (`fids = NULL`, `instances_shifted = NULL`,
#' `runs_per = 20`, `seed = 0`) is the hand-written wrapper
#' `sz_bias_central()` in `R/bias.R`, which calls this function. `fids`/
#' `instances_shifted` are the trailing `Option<RealSexp>` args (savvy
#' requires optional args to come last in a raw signature); `NULL` falls
#' back to `sezgi_bias::report`'s own `DEFAULT_CENTRAL_FIDS`/
#' `DEFAULT_CENTRAL_INSTANCES` (`[1, 4, 13]`/`[1, 2]`), same as py-sezgi's
#' `bias_central`.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim Problem dimension (BBOB requires >= 2, double, cast to `usize`).
#' @param budget Per-run evaluation budget (double, cast to `u64`).
#' @param runs_per Independent runs per `(fid, instance)` pair (double,
#'   cast to `u32`).
#' @param seed Master RNG seed, shared by both conditions (double, cast to
#'   `u64`).
#' @param fids Optional numeric vector of BBOB function ids; `NULL` uses
#'   the verified defaults `c(1, 4, 13)`. Every entry must be
#'   translation-invariant -- fids 5, 6, 20, 24 are rejected.
#' @param instances_shifted Optional numeric vector of BBOB instance
#'   numbers; `NULL` uses the verified defaults `c(1, 2)`.
#' @returns A named list with `gap_centered`, `gap_shifted`, `wilcoxon`,
#'   `effect`, `verdict`, `detail` (mirrors py-sezgi's
#'   `sezgi.bias.central()` dict keys exactly).
#'
#' # Errors
#' A savvy error for every [`sezgi_bias::BiasError`] case, including a fid
#' in `{5, 6, 20, 24}` (not translation-invariant).
#' @noRd
`sz_bias_central_raw` <- function(`spec_json`, `dim`, `budget`, `runs_per`, `seed`, `fids` = NULL, `instances_shifted` = NULL) {
  .Call(savvy_sz_bias_central_raw__impl, `spec_json`, `dim`, `budget`, `runs_per`, `seed`, `fids`, `instances_shifted`)
}

#' One-call bias report: runs both the structural and central bias scans
#' on `spec_json` and assembles a single report -- see
#' [`sezgi_bias::report::bias_report`].
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults (every optional knob `NULL`) is the hand-written
#' wrapper `sz_bias_report()` in `R/bias.R`, which calls this function.
#' Every `NULL` knob falls back to [`BiasReportConfig::new`]'s own
#' documented verified-method default (`structural_runs` -> 30,
#' `central_fids` -> `[1, 4, 13]`, `central_instances` -> `[1, 2]`,
#' `central_runs_per` -> 20), same as py-sezgi's `bias_report`.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim Shared dimensionality for both scans (double, cast to `usize`).
#' @param budget Shared per-run evaluation budget (double, cast to `u64`).
#' @param seed Shared master RNG seed (double, cast to `u64`).
#' @param structural_runs Optional double, cast to `u32`; `NULL` uses 30.
#' @param central_runs_per Optional double, cast to `u32`; `NULL` uses 20.
#' @param central_fids Optional numeric vector; `NULL` uses `c(1, 4, 13)`.
#' @param central_instances Optional numeric vector; `NULL` uses `c(1, 2)`.
#' @returns A named list with `structural`, `central`, `signature` (`NULL`
#'   today, since T6 is deferred and `BiasReport::signature` is always
#'   `None` -- see this module's own doc; when non-`NULL`, a two-element
#'   list `list(verdict = ..., detail = ...)`, same shape as `structural`'s/
#'   `central`'s own `verdict`/`detail`), `latex_summary` (never contains
#'   the literal `"NaN"`), `plot_data` (mirrors py-sezgi's
#'   `sezgi.bias.report()` dict keys exactly).
#' @noRd
`sz_bias_report_raw` <- function(`spec_json`, `dim`, `budget`, `seed`, `structural_runs` = NULL, `central_runs_per` = NULL, `central_fids` = NULL, `central_instances` = NULL) {
  .Call(savvy_sz_bias_report_raw__impl, `spec_json`, `dim`, `budget`, `seed`, `structural_runs`, `central_runs_per`, `central_fids`, `central_instances`)
}

#' Structural-bias scan: run `spec_json` repeatedly on the f0
#' random-function null problem and test its final positions for departure
#' from uniformity -- see [`sezgi_bias::structural::structural_bias_scan`].
#'
#' This is the raw savvy-generated binding (required args only; savvy has
#' no way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults
#' (`runs = 30`, `seed = 0`) is the hand-written wrapper
#' `sz_bias_structural()` in `R/bias.R`, which calls this function -- same
#' raw/wrapper pattern as `sz_stats_bayesian_signed_rank()` /
#' `sz_stats_bayesian_signed_rank_raw()`.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim f0's domain dimensionality (>= 1, double, cast to `usize`).
#' @param budget Per-run evaluation budget (double, cast to `u64`).
#' @param runs Number of independent runs (double, cast to `u32`).
#' @param seed Master RNG seed (double, cast to `u64`).
#' @returns A named list with `per_dim_ks`, `per_dim_ad`,
#'   `holm_rejections_ks`, `holm_rejections_ad`, `verdict`, `detail`,
#'   `final_positions` (mirrors py-sezgi's `sezgi.bias.structural()` dict
#'   keys exactly).
#' @noRd
`sz_bias_structural_raw` <- function(`spec_json`, `dim`, `budget`, `runs`, `seed`) {
  .Call(savvy_sz_bias_structural_raw__impl, `spec_json`, `dim`, `budget`, `runs`, `seed`)
}

#' Exports the IOH archive at `log_root` as a COCO/BBOB "old format"
#' archive rooted at `out_dir` -- see `sezgi_bench::coco_export`. Returns
#' the list of written file paths (as strings), sorted for determinism.
#'
#' @param log_root Path to the IOH archive directory (as passed to
#'   `sz_run_experiment(..., log_dir = ...)`).
#' @param out_dir Directory to write the COCO/BBOB archive under.
#' @returns A character vector of written file paths, sorted.
#' @export
`sz_coco_export` <- function(`log_root`, `out_dir`) {
  .Call(savvy_sz_coco_export__impl, `log_root`, `out_dir`)
}

#' ECDF/anytime curve(s) over the IOH archive at `log_root` -- see
#' `sezgi_bench::ecdf`/`sezgi_bench::ecdf_per_algo`.
#'
#' This is the raw savvy-generated binding (required args only; savvy has
#' no way to express a non-`NULL` default for a required argument in the
#' generated signature -- same raw/wrapper pattern as
#' `sz_run_experiment()`). The public R entry point with R-native defaults
#' (`per_algo = TRUE`) is the hand-written wrapper `sz_ecdf()` in
#' `R/anytime.R`, which calls this function.
#'
#' @param log_root Path to the IOH archive directory (as passed to
#'   `sz_run_experiment(..., log_dir = ...)`).
#' @param per_algo `TRUE` returns a named list, one `list(evals=,
#'   proportion=)` entry per distinct algo in the archive, named by algo
#'   (first-appearance order); `FALSE` returns a single pooled
#'   `list(evals=, proportion=)` over every scenario.
#' @param targets Optional numeric vector of precision targets; `NULL`
#'   uses `sezgi_bench::default_targets` (the COCO-convention 51-value
#'   set).
#' @returns A named list (see `per_algo`).
#' @noRd
`sz_ecdf_raw` <- function(`log_root`, `per_algo`, `targets` = NULL) {
  .Call(savvy_sz_ecdf_raw__impl, `log_root`, `per_algo`, `targets`)
}

#' Exact 2-objective hypervolume (Zitzler & Thiele 1999 S-metric,
#' reference-point variant; minimization) -- binds
#' [`sezgi_stats::hypervolume_2d`] exactly. See that function's doc for the
#' pinned definition.
#'
#' @param front A numeric matrix, rows = points, 2 columns (`f1`, `f2`) --
#'   R-idiomatic (unlike py-sezgi's `list[[f1,f2],...]`); see this module's
#'   own doc, "Container-idiom decisions". Build with `rbind()`/`matrix()`.
#' @param ref_point A 2-element numeric vector.
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error if `ref_point` does not have exactly 2 values, if `front`
#' is not a matrix, or for any [`sezgi_stats::StatsError`] (empty front, a
#' non-2-objective row, or a non-finite value).
#' @export
`sz_mo_hypervolume_2d` <- function(`front`, `ref_point`) {
  .Call(savvy_sz_mo_hypervolume_2d__impl, `front`, `ref_point`)
}

#' Inverted Generational Distance (Ishibuchi et al. 2015, eq. 12, `p = 1`)
#' -- binds [`sezgi_stats::igd`] exactly. Any (equal, consistent) number of
#' objectives across both `front` and `reference_front`.
#'
#' @param front A numeric matrix, rows = points -- see this module's own
#'   doc, "Container-idiom decisions".
#' @param reference_front A numeric matrix, rows = points, same column
#'   count as `front`.
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error if either argument is not a matrix, or for any
#' [`sezgi_stats::StatsError`] (an empty `front`/`reference_front`, a
#' dimension mismatch, or a non-finite value).
#' @export
`sz_mo_igd` <- function(`front`, `reference_front`) {
  .Call(savvy_sz_mo_igd__impl, `front`, `reference_front`)
}

#' A deterministic `n`-point sample of the analytic Pareto front in
#' OBJECTIVE space, if known -- binds [`sezgi_core::mo::MoProblem::pareto_front`].
#' Same `problem`/`m` mapping as `sz_nsga2_raw` (see this module's own doc).
#'
#' This is the raw savvy-generated binding (required args only, `m`
#' trailing since it is optional). The public R entry point with R-native
#' defaults (`m = NULL`) is the hand-written wrapper `sz_mo_pareto_front()`
#' in `R/mo.R`, which calls this function -- same raw/wrapper pattern as
#' `sz_nsga2()` / `sz_nsga2_raw()`.
#'
#' @param problem Same mapping as `sz_nsga2_raw`.
#' @param dim Decision-space dimensionality (double, cast to `usize`).
#' @param n Number of front points to sample (double, cast to `usize`).
#' @param m Optional number of objectives (double, cast to `usize`).
#'   REQUIRED for dtlz, must be `NULL` for zdt -- same rule as
#'   `sz_nsga2_raw`.
#' @returns A `list` of `n` numeric vectors (see this module's own doc,
#'   "Container-idiom decisions"), or `NULL` when the problem has no known
#'   analytic front sample at this `m` (verified case: DTLZ5/DTLZ6 with
#'   `m > 3`) -- mirrors py-sezgi's `sezgi.mo.pareto_front()` return
#'   exactly.
#'
#' # Errors
#' Same as `sz_nsga2_raw`'s problem-construction errors.
#' @noRd
`sz_mo_pareto_front_raw` <- function(`problem`, `dim`, `n`, `m` = NULL) {
  .Call(savvy_sz_mo_pareto_front_raw__impl, `problem`, `dim`, `n`, `m`)
}

#' NSGA-II run (Deb, Pratap, Agarwal & Meyarivan 2002) -- binds
#' [`sezgi_components::nsga2::nsga2_run`]. See this module's own doc for the
#' `problem`/`m` mapping.
#'
#' This is the raw savvy-generated binding (required args only, optional
#' args -- `m`/`p_m` -- trailing; savvy has no way to express a non-`NULL`
#' default for a required argument in the generated signature, and requires
#' optional args last). The public R entry point with R-native defaults
#' (`m = NULL`, `seed = 0`, `eta_c = 20.0`, `eta_m = 20.0`, `p_c = 0.9`,
#' `p_m = NULL`) is the hand-written wrapper `sz_nsga2()` in `R/mo.R`, which
#' calls this function -- same raw/wrapper pattern as `sz_bias_structural()`
#' / `sz_bias_structural_raw()`.
#'
#' @param problem One of `"zdt1"`, `"zdt2"`, `"zdt3"`, `"zdt4"`, `"zdt6"`,
#'   or `"dtlz1"`..`"dtlz7"`.
#' @param dim Decision-space dimensionality (double, cast to `usize`).
#' @param pop_size Population size (double, cast to `usize`). Must be
#'   `>= 4` and a multiple of 4 (KanGAL's double-permutation tournament
#'   pairing requires it -- NOT merely "even, >= 4").
#' @param budget Total evaluation budget (double, cast to `u64`).
#' @param seed Master RNG seed (double, cast to `u64`).
#' @param eta_c SBX distribution index. Paper default: `20.0`.
#' @param eta_m Polynomial-mutation distribution index. Paper default:
#'   `20.0`.
#' @param p_c SBX crossover probability. Paper default: `0.9`.
#' @param m Optional number of objectives (double, cast to `usize`).
#'   REQUIRED for dtlz problems; must be `NULL` for zdt problems.
#' @param p_m Optional per-variable mutation probability. `NULL` resolves
#'   on the Rust side to `1 / n_variables` (the paper's own default), never
#'   re-derived here.
#' @returns A named list with `individuals`, `objectives`, `front0`,
#'   `evals_used` -- see this module's own doc.
#'
#' # Errors
#' A savvy error for an unrecognized `problem` string, an `m` given for a
#' zdt problem, a missing `m` for a dtlz problem, or any
#' [`sezgi_components::nsga2::Nsga2Error`] (including `pop_size` failing
#' the `>= 4 && pop_size % 4 == 0` check).
#' @noRd
`sz_nsga2_raw` <- function(`problem`, `dim`, `pop_size`, `budget`, `seed`, `eta_c`, `eta_m`, `p_c`, `m` = NULL, `p_m` = NULL) {
  .Call(savvy_sz_nsga2_raw__impl, `problem`, `dim`, `pop_size`, `budget`, `seed`, `eta_c`, `eta_m`, `p_c`, `m`, `p_m`)
}

#' Builds one `sezgi_stats::PaperPackage` PER DISTINCT BUDGET present in a
#' `sz_run_experiment()` data.frame's columns, in ascending budget order --
#' see `sezgi_bench::reporting::per_budget_packages`. Per Piotrowski et al.
#' (2025), algorithm rankings can flip across budgets, so this makes
#' multi-budget reporting the default rather than a single, arbitrarily
#' chosen budget's report.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults is the hand-written wrapper `sz_per_budget_packages()`
#' in `R/experiment.R`, which extracts these columns from a data.frame and
#' calls this function.
#'
#' @param algo Character vector (the `algo` column).
#' @param fid,dim,instance,seed,budget_col,best_f,f_opt,evals Numeric
#'   vectors (the correspondingly-named columns).
#' @param rope Region of practical equivalence half-width (>= 0) for the
#'   Bayesian signed-rank test, forwarded to every budget's package.
#' @param samples Number of Monte Carlo samples per pair (double, cast to
#'   `u64`).
#' @param seed Master RNG seed (double, cast to `u64`), forwarded to every
#'   budget's package.
#' @param aggregate `"mean"` or `"median"`.
#' @returns A named list, one entry per distinct budget in ascending order,
#'   named by the budget (as a string); each value has exactly the shape
#'   `sz_stats_paper_package_raw()` returns.
#' @noRd
`sz_per_budget_packages_raw` <- function(`algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `rope`, `samples`, `master_seed`, `aggregate`) {
  .Call(savvy_sz_per_budget_packages_raw__impl, `algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `rope`, `samples`, `master_seed`, `aggregate`)
}

#' Builds an Artificial Bee Colony spec (Karaboga 2005, TR-06 / Karaboga &
#' Basturk 2007, Journal of Global Optimization -- a labeled metaphor
#' preset; see `crates/components/src/abc.rs`'s module doc for the full
#' provenance extraction against the author's own `ABCorig.m` plus the
#' official `Python_ABC` port, the pop<->food-source convention
#' resolution, the fitness-transform monotonicity proof, and the
#' phase-design adjudication -- a SINGLE stage, not two symmetric stages
#' like `tlbo`: `gen/abc-employed` + the new `replace/abc-trial-greedy`,
#' plus the new `adapter/abc-onlooker-scout` folding the onlooker AND
#' scout phases together) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (food-source count `SN`, NOT Karaboga's
#'   colony size `NP=2*SN`). Canonical is 20.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_abc` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_abc__impl, `pop_size`, `budget`)
}

#' Builds an Ant Lion Optimizer spec (Mirjalili 2015, Advances in
#' Engineering Software -- a labeled metaphor preset; see
#' `crates/components/src/alo.rs`'s module doc for the full provenance
#' extraction against the author's own `ALO.m`/`Random_walk_around_
#' antlion.m`/`RouletteWheelSelection.m`, the faithful-full-walk cost
#' decision, and the elitism design adjudication -- the antlion population
#' itself is the persisted memory via `replace/mu-plus-lambda`, no
#' blackboard state needed) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (ant/antlion count). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_alo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_alo__impl, `pop_size`, `budget`)
}

#' Builds a Bat Algorithm spec (Yang, X.-S. 2010, NICSO -- a labeled
#' metaphor preset, see `crates/components/src/ba.rs`'s module doc for the
#' tier note, citation, the verified `bat_algorithm.m` loop structure, the
#' verified fixed-loudness/pulse-rate finding, the two composing
#' sign-inversion deltas in the frequency draw and velocity term, and the
#' design adjudication for the new `replace/bat-loudness-greedy`
#' acceptance-coupled replacer) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of bats). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_bat` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_bat__impl, `pop_size`, `budget`)
}

#' Builds a (mu/mu_w,lambda)-CMA-ES algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (lambda).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cmaes` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_cmaes__impl, `pop_size`, `budget`)
}

#' Builds a CMA-ES with IPOP-style stagnation restarts algorithm spec as
#' JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (determines the initial population size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cmaes_ipop` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_cmaes_ipop__impl, `dim`, `budget`)
}

#' Builds a Cuckoo Search algorithm spec (Yang & Deb 2009 -- a labeled
#' metaphor preset, see `crates/components/src/cs.rs`'s module doc for the
#' tier note, citation and pinned draw order) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (nest count). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cuckoo_search` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_cuckoo_search__impl, `pop_size`, `budget`)
}

#' Builds a DE/best/1/bin algorithm spec (uniform init, clamp boundary,
#' one-to-one-greedy replacement) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_de_best_1` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_de_best_1__impl, `pop_size`, `budget`)
}

#' Builds a DE/rand/1/bin algorithm spec (uniform init, clamp boundary,
#' one-to-one-greedy replacement) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_de_rand_1` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_de_rand_1__impl, `pop_size`, `budget`)
}

#' Builds a (mu/mu_w,lambda)-ES algorithm spec (mutation step drawn from
#' `dist`) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL`/string default in the generated signature).
#' The public R entry point with R-native defaults is the hand-written
#' wrapper `sz_preset_es_mu_plus_lambda()` in `R/presets.R`, which calls this
#' function -- same raw/wrapper pattern as `sz_run_experiment()` /
#' `sz_run_experiment_raw()` and `sz_stats_bayesian_signed_rank()` /
#' `sz_stats_bayesian_signed_rank_raw()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @param dist Mutation distribution: one of `"uniform"`, `"gaussian"`,
#'   `"cauchy"`, `"levy"`, `"student_t"`, `"laplace"`.
#' @param mean Gaussian mean (used only when `dist = "gaussian"`).
#' @param sigma Gaussian std-dev (used only when `dist = "gaussian"`).
#' @param loc Cauchy/Laplace location (used only when `dist` is `"cauchy"`
#'   or `"laplace"`).
#' @param scale Cauchy/Laplace scale (used only when `dist` is `"cauchy"`
#'   or `"laplace"`).
#' @param alpha Levy stability parameter (used only when `dist = "levy"`).
#' @param nu Student-t degrees of freedom (used only when `dist =
#'   "student_t"`).
#' @returns A character scalar with the algorithm spec as JSON.
#' @noRd
`sz_preset_es_mu_plus_lambda_raw` <- function(`pop_size`, `budget`, `dist`, `mean`, `sigma`, `loc`, `scale`, `alpha`, `nu`) {
  .Call(savvy_sz_preset_es_mu_plus_lambda_raw__impl, `pop_size`, `budget`, `dist`, `mean`, `sigma`, `loc`, `scale`, `alpha`, `nu`)
}

#' Builds a Firefly Algorithm (Yang, X.-S., *Nature-Inspired Metaheuristic
#' Algorithms*, 2nd ed., Luniver Press, 2010 -- a labeled metaphor preset,
#' see `crates/components/src/fa.rs`'s module doc for the tier note,
#' citation, the verified `fa_ndim.m`/`ffa_move.m` loop structure, the
#' floored attractiveness formula, the closed-form `alpha` decay, and the
#' hybrid in-place-self/live-distance/frozen-target double-loop semantics)
#' spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of fireflies). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_firefly` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_firefly__impl, `pop_size`, `budget`)
}

#' Builds a Flower Pollination Algorithm spec (Yang, X.-S. 2012, UCNC -- a
#' labeled metaphor preset, see `crates/components/src/fpa.rs`'s module doc
#' for the tier note, citation, the verified `fpa_demo.m` loop structure,
#' the switch-branch orientation delta, the global-step sign delta reusing
#' `cs.rs`'s `cs_dim_step` verbatim, the local-step self-selection-not-
#' excluded finding, and the min_pop adjustment from 3 down to 2) as JSON,
#' ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of flowers). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_fpa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_fpa__impl, `pop_size`, `budget`)
}

#' Builds a real-coded GA (SBX crossover, polynomial mutation) algorithm spec
#' as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_ga_real` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_ga_real__impl, `pop_size`, `budget`)
}

#' Builds a Grasshopper Optimisation Algorithm spec (Saremi, Mirjalili &
#' Lewis 2017 -- a labeled metaphor preset, see
#' `crates/components/src/goa.rs`'s module doc for the tier note, citation,
#' the IMPLEMENTER-VERIFY distance-normalization resolution and the
#' zero-RNG-draw arithmetic-order pin) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (swarm size). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_goa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_goa__impl, `pop_size`, `budget`)
}

#' Builds a Gravitational Search Algorithm spec (Rashedi, Nezamabadi-pour &
#' Saryazdi 2009, Information Sciences -- a labeled metaphor preset, and the
#' wave's LAST stateful/blackboard algorithm; see
#' `crates/components/src/gsa.rs`'s module doc for the full provenance
#' extraction against the author's own `GSA.m`/`Gconstant.m`/
#' `massCalculation.m`/`Gfield.m`/`move.m`, the verified `M_i`-free force
#' delta, and the confirmation that GSA's own `Fbest`/`Lbest` never feed
#' back into the mechanism) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (agent count). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_gsa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_gsa__impl, `pop_size`, `budget`)
}

#' Builds a Grey Wolf Optimizer algorithm spec (Mirjalili, Mirjalili & Lewis
#' 2014 -- a labeled metaphor preset, see `crates/components/src/gwo.rs`'s
#' module doc for the tier note and citations) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (pack size). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_gwo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_gwo__impl, `pop_size`, `budget`)
}

#' Builds a Harmony Search algorithm spec (Geem, Kim & Loganathan 2001 -- a
#' labeled metaphor preset, see `crates/components/src/hs.rs`'s module doc
#' for the tier note and citations) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (Harmony Memory Size, HMS). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_harmony_search` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_harmony_search__impl, `pop_size`, `budget`)
}

#' Builds a Harris Hawks Optimization spec (Heidari, Mirjalili, Faris,
#' Aljarah, Mafarja & Chen 2019, Future Generation Computer Systems -- a
#' labeled metaphor preset, and the wave's most structurally complex one: a
#' multi-branch escape-energy tree whose progressive rapid-dive
#' sub-branches evaluate mid-`generate()`. See
#' `crates/components/src/hho.rs`'s module doc for the full provenance
#' extraction against the paper author's own `HHO.m`, the hard/soft
#' besiege mapping delta, the mean(X)/random-hawk in-place semantics, and
#' the prominent in-generator-evaluation eval-accounting design decision)
#' as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (hawk count). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_hho` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_hho__impl, `pop_size`, `budget`)
}

#' Builds a JAYA spec (Rao 2016 -- a labeled metaphor preset, see
#' `crates/components/src/jaya.rs`'s module doc for the tier note,
#' citation, the primary-paper-verified worked-example reproduction, the
#' shared-per-dimension-per-generation `r1`/`r2` draw finding and the
#' greedy-replacement delta vs mealpy's misleadingly-named `OriginalJA`) as
#' JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (candidate count). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_jaya` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_jaya__impl, `pop_size`, `budget`)
}

#' Builds a jDE algorithm spec (self-adaptive F/CR DE) as JSON, ready to pass
#' to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_jde` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_jde__impl, `pop_size`, `budget`)
}

#' Builds an L-SHADE algorithm spec (population linearly reduced from
#' `18 * dim`) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (determines the initial population size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_lshade` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_lshade__impl, `dim`, `budget`)
}

#' Builds an MFO (Moth-Flame Optimization; Mirjalili 2015 -- a labeled
#' metaphor preset, see `crates/components/src/mfo.rs`'s module doc for the
#' tier note, citation, the verified `MFO.m` loop structure, the two subtle
#' draw/index deltas found vs the plan's sketch, and the blackboard
#' flame-memory design) spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of search agents). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_mfo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_mfo__impl, `pop_size`, `budget`)
}

#' Builds a Nelder-Mead simplex algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (population size is fixed to `dim + 1`).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_nelder_mead` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_nelder_mead__impl, `dim`, `budget`)
}

#' Builds a PSO (Clerc-Kennedy constriction) algorithm spec as JSON, ready to
#' pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (swarm size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_pso` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_pso__impl, `pop_size`, `budget`)
}

#' Builds a random search algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (resampled uniformly each generation).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_random_search` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_random_search__impl, `pop_size`, `budget`)
}

#' Builds a simulated annealing (Metropolis, geometric cooling) algorithm
#' spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_sa` <- function(`budget`) {
  .Call(savvy_sz_preset_sa__impl, `budget`)
}

#' Builds a Sine Cosine Algorithm spec (Mirjalili 2016 -- a labeled
#' metaphor preset, see `crates/components/src/sca.rs`'s module doc for the
#' tier note, citation, the `SCA.m`-verified pinned draw order and the
#' mealpy-`OriginalSCA` replacer delta) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of search agents). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_sca` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_sca__impl, `pop_size`, `budget`)
}

#' Builds a SHADE algorithm spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_shade` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_shade__impl, `pop_size`, `budget`)
}

#' Builds an SSA (Salp Swarm Algorithm; Mirjalili et al. 2017 -- a labeled
#' metaphor preset, see `crates/components/src/ssa.rs`'s module doc for the
#' tier note, citation, the verified `SSA.m` half-population leader/follower
#' split, the leader sign-branch pin, the verified in-place follower-chain
#' semantics, and the persisted-food-vs-current-pop-best delta) spec as
#' JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of salps). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_ssa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_ssa__impl, `pop_size`, `budget`)
}

#' Builds a Teaching-Learning-Based Optimization spec (Rao, Savsani &
#' Vakharia 2011, Computer-Aided Design -- a labeled metaphor preset, and
#' sezgi's FIRST multi-stage preset: two `[[stages]]` (teacher, then
#' learner) run in sequence every generation. See
#' `crates/components/src/tlbo.rs`'s module doc for the full provenance
#' extraction against Yarpiz's `tlbo.m` -- explicitly labeled third-party,
#' not Rao's own code -- the per-learner teaching-factor finding, the
#' unconditionally-distinct partner-selection finding, the min_pop
#' adjustment from 3 down to 2, and the "parameter-free" framing's
#' Črepinšek/Liu/Mernik (2012) counterpoint) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (class size). Canonical is 30.
#' @param budget Evaluation budget. A full generation costs `2 * pop_size`
#'   evaluations (both stages evaluate).
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_tlbo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_tlbo__impl, `pop_size`, `budget`)
}

#' Builds a Whale Optimization Algorithm spec (Mirjalili & Lewis 2016 -- a
#' labeled metaphor preset, see `crates/components/src/woa.rs`'s module doc
#' for the tier note and citations) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (school size). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_woa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_woa__impl, `pop_size`, `budget`)
}

#' Reconstructs `RunRecord`s from an on-disk IOH archive at `log_root` (as
#' written by `sz_run_experiment(..., log_dir = ...)`), one record per
#' `(run, budget)` pair -- see `sezgi_bench::ioh_records`'s doc comment for
#' the exact `best_f`/`evals_used` semantics and the curtailed-view-vs-
#' independent-run distinction for budgets smaller than a run's logged
#' budget.
#'
#' Returns the SAME data.frame shape `sz_run_experiment()` returns (via
#' [`records_to_data_frame`]), so `sz_results_matrix()`/
#' `sz_per_budget_packages()` accept it unchanged.
#'
#' @param log_root Path to the IOH archive directory (as passed to
#'   `sz_run_experiment(..., log_dir = ...)`).
#' @param budgets Numeric vector of evaluation budgets to reconstruct
#'   records at.
#' @returns A data.frame with the same columns as `sz_run_experiment()`.
#' @export
`sz_read_ioh_records` <- function(`log_root`, `budgets`) {
  .Call(savvy_sz_read_ioh_records__impl, `log_root`, `budgets`)
}

#' Builds a `sezgi_stats`-shaped results matrix for one `budget` from a
#' `sz_run_experiment()` data.frame's columns -- see
#' `sezgi_bench::reporting::results_matrix`.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults is the hand-written wrapper `sz_results_matrix()` in
#' `R/experiment.R`, which extracts these columns from a data.frame and
#' calls this function.
#'
#' @param algo Character vector (the `algo` column).
#' @param fid,dim,instance,seed,budget_col,best_f,f_opt,evals Numeric
#'   vectors (the correspondingly-named columns; `budget_col` avoids a name
#'   clash with the scalar `budget` argument below).
#' @param budget Only rows with this budget are used.
#' @param aggregate `"mean"` or `"median"`.
#' @returns A named list with `algo_names` (character vector),
#'   `problem_labels` (character vector, `f{fid}d{dim}i{instance}`), and
#'   `matrix` (numeric matrix, rows = problems, columns = algorithms).
#' @noRd
`sz_results_matrix_raw` <- function(`algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `budget`, `aggregate`) {
  .Call(savvy_sz_results_matrix_raw__impl, `algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `best_f`, `f_opt`, `evals`, `budget`, `aggregate`)
}

#' Runs an [`ExperimentSpec`] (parsed from `spec_toml`) and returns its
#' `RunRecord`s as a data.frame. This mirrors py-sezgi's `run_experiment`
#' exactly (see `py-sezgi/src/lib.rs`): `journal=None` runs via
#' `run_experiment_parallel`/`run_experiment_sequential` (chosen by
#' `parallel`); `journal=Some(path)` runs via `run_experiment_with_checkpoint`,
#' which resumes from -- and appends to -- an existing journal file at
#' `path`.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults (`parallel = TRUE`) is the hand-written wrapper
#' `sz_run_experiment()` in `R/experiment.R`, which calls this function.
#'
#' @param spec_toml Experiment spec as TOML.
#' @param parallel Whether to run in parallel via rayon.
#' @param journal Optional path to a checkpoint journal file.
#' @param threads Optional rayon thread-pool size. `usize` is not a
#'   supported savvy scalar arg type, so this comes in as `i32` and is cast;
#'   negative values are rejected explicitly (savvy has no unsigned integer
#'   scalar type to enforce this at the signature level).
#' @param log_dir Optional directory to log every run this call actually
#'   EXECUTES in IOH-profiler format (via `run_experiment_logged` when
#'   there is no `journal`, or via `run_experiment_with_checkpoint`'s own
#'   `log_dir` pass-through when there is -- see that function's doc
#'   comment: a run resumed from the journal was executed in a PRIOR
#'   process and is never re-logged).
#' @returns A data.frame with one row per run.
#'
#' The journal's spec hash is computed by `run_experiment_with_checkpoint`
#' from `spec` (the already-parsed `ExperimentSpec`), not from the raw
#' `spec_toml` text, so whitespace/comment-only edits to `spec_toml` never
#' invalidate a journal -- see `crates/bench/src/checkpoint.rs`.
#'
#' @noRd
`sz_run_experiment_raw` <- function(`spec_toml`, `parallel`, `journal` = NULL, `threads` = NULL, `log_dir` = NULL) {
  .Call(savvy_sz_run_experiment_raw__impl, `spec_toml`, `parallel`, `journal`, `threads`, `log_dir`)
}

#' Runs an algorithm spec on a BBOB problem and returns the result.
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_de_rand_1()`).
#' @param fid BBOB function id (>= 1).
#' @param dim Problem dimension (>= 1).
#' @param instance BBOB instance id (>= 1).
#' @param master_seed Master RNG seed.
#' @param run_id Run id (mixed into the seed for independent replicate streams).
#' @returns A named list with `best_f` (double), `evals` (double), and
#'   `best_x` (double vector) -- the best EVALUATED point (paired with
#'   `best_f`). For most algorithms this always lies within the declared
#'   domain. It is not guaranteed to for every algorithm: some (e.g. HHO)
#'   charge raw, pre-boundary-repair trial points against the budget before
#'   boundary repair, and such a point can become the reported best if it
#'   happens to be the run's own minimum.
#' @export
`sz_solve_bbob` <- function(`spec_json`, `fid`, `dim`, `instance`, `master_seed`, `run_id`) {
  .Call(savvy_sz_solve_bbob__impl, `spec_json`, `fid`, `dim`, `instance`, `master_seed`, `run_id`)
}

#' Bayesian signed-rank test with a region of practical equivalence (ROPE)
#' (Dirichlet-weighted Monte Carlo; see `sezgi_stats::bayesian_signed_rank`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults is
#' the hand-written wrapper `sz_stats_bayesian_signed_rank()` in
#' `R/stats.R`, which calls this function.
#'
#' @param a Numeric vector.
#' @param b Numeric vector, same length as `a`.
#' @param rope Region of practical equivalence half-width (>= 0).
#' @param samples Number of Monte Carlo samples. Passed to R as a double
#'   (savvy has no unsigned integer scalar arg type) and cast to `u64`
#'   after checking it is non-negative and finite.
#' @param seed Master RNG seed, passed through unchanged (`u64` via `f64`
#'   cast) — the same `(a, b, rope, samples, seed)` always produces a
#'   bit-identical result, since R calls the exact same seeded Rust core as
#'   Python and Rust.
#' @returns A named list with `p_left`, `p_rope`, `p_right` (mirrors
#'   py-sezgi's `stats_bayesian_signed_rank()` dict keys exactly).
#' @noRd
`sz_stats_bayesian_signed_rank_raw` <- function(`a`, `b`, `rope`, `samples`, `seed`) {
  .Call(savvy_sz_stats_bayesian_signed_rank_raw__impl, `a`, `b`, `rope`, `samples`, `seed`)
}

#' Cliff's delta effect size for two independent (unpaired) samples.
#'
#' @param a Numeric vector.
#' @param b Numeric vector.
#' @returns A numeric scalar in `[-1, 1]`.
#' @export
`sz_stats_cliffs_delta` <- function(`a`, `b`) {
  .Call(savvy_sz_stats_cliffs_delta__impl, `a`, `b`)
}

#' Qualitative magnitude label for a Cliff's delta value (Romano et al. 2006
#' thresholds).
#'
#' @param delta A Cliff's delta value (as returned by
#'   `sz_stats_cliffs_delta()`).
#' @returns A character scalar: one of `"negligible"`, `"small"`,
#'   `"medium"`, `"large"`.
#' @export
`sz_stats_cliffs_magnitude` <- function(`delta`) {
  .Call(savvy_sz_stats_cliffs_magnitude__impl, `delta`)
}

#' Runs the Friedman test on a results matrix.
#'
#' @param m A numeric matrix, rows = problems, columns = algorithms, lower
#'   is better (e.g. built with `rbind()` or `matrix()`).
#' @returns A named list with `statistic`, `p_value`, `mean_ranks` (mirrors
#'   py-sezgi's `stats_friedman()` dict keys exactly).
#' @export
`sz_stats_friedman` <- function(`m`) {
  .Call(savvy_sz_stats_friedman__impl, `m`)
}

#' Computes a comprehensive statistical analysis package for algorithm
#' comparison (Friedman, Nemenyi CD, pairwise Wilcoxon+Holm, Cliff's delta,
#' Bayesian signed-rank, Plackett-Luce, and LaTeX tables; see
#' `sezgi_stats::paper_package`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults is
#' the hand-written wrapper `sz_stats_paper_package()` in `R/stats.R`, which
#' calls this function.
#'
#' @param algo_names Character vector of algorithm names.
#' @param problem_names Character vector of problem names.
#' @param m A numeric matrix, rows = problems (`length(problem_names)`),
#'   columns = algorithms (`length(algo_names)`), lower is better.
#' @param rope Region of practical equivalence half-width (>= 0) for the
#'   Bayesian signed-rank test.
#' @param samples Number of Monte Carlo samples per pair for the Bayesian
#'   signed-rank test (double, cast to `u64`; see
#'   `sz_stats_bayesian_signed_rank_raw()`).
#' @param seed Master RNG seed (double, cast to `u64`); per-pair seeds are
#'   `seed + pair_index` (wrapping), matching `sezgi_stats::paper_package`.
#' @returns A named list with `friedman` (nested list: `statistic`,
#'   `p_value`, `mean_ranks`), `nemenyi_cd`, `pairwise_wilcoxon_holm` (list
#'   of length-3 numeric vectors `c(i, j, adjusted_p)`, 0-based algorithm
#'   indices, i < j), `cliffs` (list of length-3 numeric vectors `c(i, j,
#'   delta)`), `bayes` (list of 3-element lists `list(i, j, bayes_result)`
#'   where `bayes_result` has `p_left`/`p_rope`/`p_right`),
#'   `plackett_luce` (nested list: `worths`, `p_best`, `iterations`),
#'   `latex_summary`, `latex_tests` (mirrors py-sezgi's
#'   `stats_paper_package()` dict keys exactly).
#' @noRd
`sz_stats_paper_package_raw` <- function(`algo_names`, `problem_names`, `m`, `rope`, `samples`, `seed`) {
  .Call(savvy_sz_stats_paper_package_raw__impl, `algo_names`, `problem_names`, `m`, `rope`, `samples`, `seed`)
}

#' Plackett-Luce maximum-likelihood ranking (Hunter 2004 MM algorithm; see
#' `sezgi_stats::plackett_luce`).
#'
#' @param rankings A `list` of integer (or integer-valued numeric) vectors,
#'   each a full ranking of the same `k` items as **1-based item ids**
#'   (R's natural indexing; e.g. `list(c(1, 2, 3), c(2, 1, 3))` for k = 3
#'   items, best first). Converted to 0-based indices before calling the
#'   Rust core, which expects a permutation of `0..k`.
#' @returns A named list with `worths`, `p_best`, `iterations` (mirrors
#'   py-sezgi's `stats_plackett_luce()` dict keys exactly).
#' @export
`sz_stats_plackett_luce` <- function(`rankings`) {
  .Call(savvy_sz_stats_plackett_luce__impl, `rankings`)
}

#' Wilcoxon signed-rank test for two paired samples (Pratt zero-handling and
#' tie correction; see `sezgi_stats::wilcoxon_signed_rank`).
#'
#' @param a Numeric vector.
#' @param b Numeric vector, same length as `a`.
#' @returns A named list with `w_statistic`, `z`, `p_value`, `n_effective`,
#'   `method` (`"exact"` or `"normal_approx"`; mirrors py-sezgi's
#'   `stats_wilcoxon()` dict keys exactly). `"exact"` is used when
#'   `n_effective <= 25` and there are no zero differences or tied `|d|`
#'   ranks; see `sezgi_stats::wilcoxon_signed_rank`'s doc comment for the
#'   full eligibility rule (the exact p-value formula is semver-pinned).
#' @export
`sz_stats_wilcoxon` <- function(`a`, `b`) {
  .Call(savvy_sz_stats_wilcoxon__impl, `a`, `b`)
}

### wrapper functions for EvalSession

`EvalSession_best` <- function(self) {
  function() {
    .Call(savvy_EvalSession_best__impl, `self`)
  }
}

`EvalSession_budget` <- function(self) {
  function() {
    .Call(savvy_EvalSession_budget__impl, `self`)
  }
}

`EvalSession_evals_used` <- function(self) {
  function() {
    .Call(savvy_EvalSession_evals_used__impl, `self`)
  }
}

`EvalSession_evaluate` <- function(self) {
  function(`x`) {
    .Call(savvy_EvalSession_evaluate__impl, `self`, `x`)
  }
}

`EvalSession_f_opt` <- function(self) {
  function() {
    .Call(savvy_EvalSession_f_opt__impl, `self`)
  }
}

`EvalSession_finish` <- function(self) {
  function() {
    invisible(.Call(savvy_EvalSession_finish__impl, `self`))
  }
}

`.savvy_wrap_EvalSession` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`best` <- `EvalSession_best`(ptr)
  e$`budget` <- `EvalSession_budget`(ptr)
  e$`evals_used` <- `EvalSession_evals_used`(ptr)
  e$`evaluate` <- `EvalSession_evaluate`(ptr)
  e$`f_opt` <- `EvalSession_f_opt`(ptr)
  e$`finish` <- `EvalSession_finish`(ptr)

  class(e) <- c("sezgi::EvalSession", "EvalSession", "savvy_sezgi__sealed")
  e
}


#' The ask/tell evaluation session -- see the module doc.
`EvalSession` <- new.env(parent = emptyenv())

### associated functions for EvalSession

`EvalSession`$`new` <- function(`fid`, `dim`, `instance`, `budget`, `algo_name`, `seed`, `log_dir` = NULL) {
  .savvy_wrap_EvalSession(.Call(savvy_EvalSession_new__impl, `fid`, `dim`, `instance`, `budget`, `algo_name`, `seed`, `log_dir`))
}


class(`EvalSession`) <- c("sezgi::EvalSession__bundle", "savvy_sezgi__sealed")

#' @export
`print.sezgi::EvalSession__bundle` <- function(x, ...) {
  cat('sezgi::EvalSession\n')
}

