# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib sezgi, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_sezgi__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_sezgi__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Version of the underlying sezgi Rust core.
#'
#' @returns A character scalar with the crate version string.
#' @export
`sezgi_version` <- function() {
  .Call(savvy_sezgi_version__impl)
}

#' Bayesian Plackett-Luce posterior via Gibbs sampling (Caron & Doucet
#' 2012 latent exponential-race augmentation; see
#' `sezgi_stats::bayesian_plackett_luce`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has
#' no way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults
#' is the hand-written wrapper `sz_bayesian_plackett_luce()` in
#' `R/stats.R`, which calls this function -- same raw/wrapper pattern as
#' `sz_stats_bayesian_signed_rank()` / `sz_stats_bayesian_signed_rank_raw()`.
#'
#' @param rankings A `list` of integer (or integer-valued numeric)
#'   vectors, each a full ranking of the same `k` items as **1-based item
#'   ids** (same convention as `sz_stats_plackett_luce()`; converted via
#'   the SAME `rankings_from_list()` helper). Best (rank 1) first.
#' @param samples Number of post-burn-in Gibbs iterations to record
#'   (double, cast to `u64`).
#' @param burn_in Number of initial Gibbs iterations to discard (double,
#'   cast to `u64`).
#' @param seed Master RNG seed, passed through unchanged (`u64` via `f64`
#'   cast) -- the same `(rankings, samples, burn_in, seed)` always
#'   produces a bit-identical result, since R calls the exact same seeded
#'   Rust core as Python and Rust.
#' @returns A named list with `mean_worths`, `ci_low`, `ci_high`,
#'   `p_best`, `samples` (mirrors py-sezgi's
#'   `stats_bayesian_plackett_luce()` dict keys exactly).
#' @noRd
`sz_bayesian_plackett_luce_raw` <- function(`rankings`, `samples`, `burn_in`, `seed`) {
  .Call(savvy_sz_bayesian_plackett_luce_raw__impl, `rankings`, `samples`, `burn_in`, `seed`)
}

#' Central-bias scan: run `spec_json` on paired centered/shifted BBOB
#' conditions and test whether its performance gap differs between them --
#' see [`sezgi_bias::central::central_bias_scan`].
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults (`fids = NULL`, `instances_shifted = NULL`,
#' `runs_per = 20`, `seed = 0`) is the hand-written wrapper
#' `sz_bias_central()` in `R/bias.R`, which calls this function. `fids`/
#' `instances_shifted` are the trailing `Option<RealSexp>` args (savvy
#' requires optional args to come last in a raw signature); `NULL` falls
#' back to `sezgi_bias::report`'s own `DEFAULT_CENTRAL_FIDS`/
#' `DEFAULT_CENTRAL_INSTANCES` (`[1, 4, 13]`/`[1, 2]`), same as py-sezgi's
#' `bias_central`.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim Problem dimension (BBOB requires >= 2, double, cast to `usize`).
#' @param budget Per-run evaluation budget (double, cast to `u64`).
#' @param runs_per Independent runs per `(fid, instance)` pair (double,
#'   cast to `u32`).
#' @param seed Master RNG seed, shared by both conditions (double, cast to
#'   `u64`).
#' @param fids Optional numeric vector of BBOB function ids; `NULL` uses
#'   the verified defaults `c(1, 4, 13)`. Every entry must be
#'   translation-invariant -- fids 5, 6, 20, 24 are rejected.
#' @param instances_shifted Optional numeric vector of BBOB instance
#'   numbers; `NULL` uses the verified defaults `c(1, 2)`.
#' @returns A named list with `gap_centered`, `gap_shifted`, `wilcoxon`,
#'   `effect`, `verdict`, `detail` (mirrors py-sezgi's
#'   `sezgi.bias.central()` dict keys exactly).
#'
#' # Errors
#' A savvy error for every [`sezgi_bias::BiasError`] case, including a fid
#' in `{5, 6, 20, 24}` (not translation-invariant).
#' @noRd
`sz_bias_central_raw` <- function(`spec_json`, `dim`, `budget`, `runs_per`, `seed`, `fids` = NULL, `instances_shifted` = NULL) {
  .Call(savvy_sz_bias_central_raw__impl, `spec_json`, `dim`, `budget`, `runs_per`, `seed`, `fids`, `instances_shifted`)
}

#' One-call bias report: runs both the structural and central bias scans
#' on `spec_json` and assembles a single report -- see
#' [`sezgi_bias::report::bias_report`].
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults (every optional knob `NULL`) is the hand-written
#' wrapper `sz_bias_report()` in `R/bias.R`, which calls this function.
#' Every `NULL` knob falls back to [`BiasReportConfig::new`]'s own
#' documented verified-method default (`structural_runs` -> 30,
#' `central_fids` -> `[1, 4, 13]`, `central_instances` -> `[1, 2]`,
#' `central_runs_per` -> 20), same as py-sezgi's `bias_report`.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim Shared dimensionality for both scans (double, cast to `usize`).
#' @param budget Shared per-run evaluation budget (double, cast to `u64`).
#' @param seed Shared master RNG seed (double, cast to `u64`).
#' @param structural_runs Optional double, cast to `u32`; `NULL` uses 30.
#' @param central_runs_per Optional double, cast to `u32`; `NULL` uses 20.
#' @param central_fids Optional numeric vector; `NULL` uses `c(1, 4, 13)`.
#' @param central_instances Optional numeric vector; `NULL` uses `c(1, 2)`.
#' @returns A named list with `structural`, `central`, `signature` (`NULL`
#'   today, since T6 is deferred and `BiasReport::signature` is always
#'   `None` -- see this module's own doc; when non-`NULL`, a two-element
#'   list `list(verdict = ..., detail = ...)`, same shape as `structural`'s/
#'   `central`'s own `verdict`/`detail`), `latex_summary` (never contains
#'   the literal `"NaN"`), `plot_data` (mirrors py-sezgi's
#'   `sezgi.bias.report()` dict keys exactly).
#' @noRd
`sz_bias_report_raw` <- function(`spec_json`, `dim`, `budget`, `seed`, `structural_runs` = NULL, `central_runs_per` = NULL, `central_fids` = NULL, `central_instances` = NULL) {
  .Call(savvy_sz_bias_report_raw__impl, `spec_json`, `dim`, `budget`, `seed`, `structural_runs`, `central_runs_per`, `central_fids`, `central_instances`)
}

#' Statistics-only structural-bias scan over EXTERNALLY-collected final
#' positions -- see [`scan_from_positions`]. Unlike [`sz_bias_structural_raw`]
#' (which drives an `AlgorithmSpec` through this crate's own engine, `runs`
#' times), this entry point runs NOTHING itself: it tests final positions
#' collected from ANY externally-authored algorithm -- e.g. a pure-R
#' `sz_algorithm`/`sz_algo_solve()` run, one run at a time, over
#' `sz_eval_session_f0()` (see `R/algo.R`) -- for departure from
#' uniformity. `dim` is inferred from the first row's length; every row
#' must have the SAME length. Mirrors py-sezgi's
#' `sezgi.bias.structural_positions()` 1:1, including sharing the same
#' dict/list-building helper ([`structural_result_list`] here,
#' `structural_result_to_dict` there) with the engine-driven scan, so the
#' two are interchangeable to any downstream consumer.
#'
#' This is the raw savvy-generated binding; the public R entry point is the
#' hand-written wrapper `sz_bias_structural_positions()` in `R/bias.R` --
#' there is only one required argument, so the wrapper adds no R-native
#' default, but keeps this file's raw/wrapper naming convention and gives
#' this raw (`@noRd`) binding a proper `@export` roxygen block.
#'
#' @param final_positions A numeric matrix (rows = independent runs' final
#'   positions, columns = dimension) or a `list` of numeric vectors, one
#'   per run. Must have at least 5 rows/elements (`scan_from_positions`'s
#'   own verified minimum run count), all the same length.
#' @returns Same named-list shape as `sz_bias_structural_raw()`'s return:
#'   `per_dim_ks`, `per_dim_ad`, `holm_rejections_ks`, `holm_rejections_ad`,
#'   `verdict`, `detail`, `final_positions`.
#'
#' # Errors
#' A savvy error if `final_positions` has fewer than 5 rows/elements, is
#' ragged (rows of differing length), or any row is empty (`dim == 0`).
#' @noRd
`sz_bias_structural_positions_raw` <- function(`final_positions`) {
  .Call(savvy_sz_bias_structural_positions_raw__impl, `final_positions`)
}

#' Structural-bias scan: run `spec_json` repeatedly on the f0
#' random-function null problem and test its final positions for departure
#' from uniformity -- see [`sezgi_bias::structural::structural_bias_scan`].
#'
#' This is the raw savvy-generated binding (required args only; savvy has
#' no way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults
#' (`runs = 30`, `seed = 0`) is the hand-written wrapper
#' `sz_bias_structural()` in `R/bias.R`, which calls this function -- same
#' raw/wrapper pattern as `sz_stats_bayesian_signed_rank()` /
#' `sz_stats_bayesian_signed_rank_raw()`.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim f0's domain dimensionality (>= 1, double, cast to `usize`).
#' @param budget Per-run evaluation budget (double, cast to `u64`).
#' @param runs Number of independent runs (double, cast to `u32`).
#' @param seed Master RNG seed (double, cast to `u64`).
#' @returns A named list with `per_dim_ks`, `per_dim_ad`,
#'   `holm_rejections_ks`, `holm_rejections_ad`, `verdict`, `detail`,
#'   `final_positions` (mirrors py-sezgi's `sezgi.bias.structural()` dict
#'   keys exactly).
#' @noRd
`sz_bias_structural_raw` <- function(`spec_json`, `dim`, `budget`, `runs`, `seed`) {
  .Call(savvy_sz_bias_structural_raw__impl, `spec_json`, `dim`, `budget`, `runs`, `seed`)
}

#' Direct, one-shot evaluation of a CEC 2014 (Liang, Qu & Suganthan 2013)
#' function at `x`, bypassing `sz_solve_bbob`-style budget/engine machinery
#' entirely -- binds [`Cec2014::new`] + [`Cec2014::evaluate_batch`] exactly.
#' Mirrors `sz_cec2022_evaluate` (M3-6 Task 10 -- see py-sezgi's
#' `sezgi.problems.cec2014_evaluate` for the identical binding on the Python
#' side). See [`Cec2014::new`]'s own doc for the exact `fid`/`dim` domain.
#'
#' @param fid CEC 2014 function id, `1..=30` (double, cast to `u32`).
#' @param dim Problem dimension, one of `10`, `30` (double, cast to
#'   `usize`).
#' @param x A numeric vector of exactly `dim` coordinates.
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error for `fid` outside `1..=30`, `dim` outside `{10,30}`, or
#' `length(x) != dim`.
#' @export
`sz_cec2014_evaluate` <- function(`fid`, `dim`, `x`) {
  .Call(savvy_sz_cec2014_evaluate__impl, `fid`, `dim`, `x`)
}

#' The report's pinned `F_i*` bias for a CEC 2014 function -- binds
#' [`Cec2014::f_star`] (`F_i* = 100*fid`). Does not depend on `dim`, so an
#' internal probe `dim = 10` is used purely to validate `fid`.
#'
#' @param fid CEC 2014 function id, `1..=30` (double, cast to `u32`).
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error if `fid` is outside `1..=30`.
#' @export
`sz_cec2014_f_star` <- function(`fid`) {
  .Call(savvy_sz_cec2014_f_star__impl, `fid`)
}

#' Direct, one-shot evaluation of a CEC 2017 (Awad, Ali, Liang, Qu &
#' Suganthan 2016) function at `x`, bypassing `sz_solve_bbob`-style
#' budget/engine machinery entirely -- binds [`Cec2017::new`] +
#' [`Cec2017::evaluate_batch`] exactly. Mirrors `sz_cec2014_evaluate` (M3-6
#' Task 10 -- see py-sezgi's `sezgi.problems.cec2017_evaluate` for the
#' identical binding on the Python side). See [`Cec2017::new`]'s own doc for
#' the exact `fid`/`dim` domain.
#'
#' @param fid CEC 2017 function id, `1` or `3..=30` (double, cast to `u32`);
#'   `fid = 2` ("Sum of Different Powers") was officially withdrawn from the
#'   suite.
#' @param dim Problem dimension, one of `10`, `30` (double, cast to
#'   `usize`).
#' @param x A numeric vector of exactly `dim` coordinates.
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error for `fid` outside `{1} union {3..=30}`, `dim` outside
#' `{10,30}`, or `length(x) != dim`. `fid = 2` raises a dedicated error --
#' the Rust [`sezgi_problems::Cec2017Error::Withdrawn`] message is surfaced
#' VERBATIM, distinct from an ordinary out-of-range `fid`.
#' @export
`sz_cec2017_evaluate` <- function(`fid`, `dim`, `x`) {
  .Call(savvy_sz_cec2017_evaluate__impl, `fid`, `dim`, `x`)
}

#' The report's pinned `F_i*` bias for a CEC 2017 function -- binds
#' [`Cec2017::f_star`] (`F_i* = 100*fid`, the fid-gapped C dispatch bias, not
#' the report's contiguous renumbering -- see `Cec2017::new`'s own module
#' doc). Does not depend on `dim`, so an internal probe `dim = 10` is used
#' purely to validate `fid`.
#'
#' @param fid CEC 2017 function id, `1` or `3..=30` (double, cast to `u32`).
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error if `fid` is outside `{1} union {3..=30}` (`fid = 2`
#' included, via the [`sezgi_problems::Cec2017Error::Withdrawn`] message).
#' @export
`sz_cec2017_f_star` <- function(`fid`) {
  .Call(savvy_sz_cec2017_f_star__impl, `fid`)
}

#' Direct, one-shot evaluation of a CEC 2022 function at `x`, bypassing
#' `sz_solve_bbob`-style budget/engine machinery entirely -- binds
#' [`Cec2022::new`] + [`Cec2022::evaluate_batch`] exactly. See
#' `Cec2022::new`'s own doc for the exact `fid`/`dim` domain.
#'
#' @param fid CEC 2022 function id, `1..=12` (double, cast to `u32`).
#' @param dim Problem dimension, one of `2`, `10`, `20` (double, cast to
#'   `usize`); `dim = 2` is additionally rejected for a hybrid function
#'   (`fid` 6-8).
#' @param x A numeric vector of exactly `dim` coordinates.
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error for `fid` outside `1..=12`, `dim` outside `{2,10,20}`,
#' `dim = 2` for a hybrid function, or `length(x) != dim`.
#' @export
`sz_cec2022_evaluate` <- function(`fid`, `dim`, `x`) {
  .Call(savvy_sz_cec2022_evaluate__impl, `fid`, `dim`, `x`)
}

#' The report's pinned `F_i*` bias for a CEC 2022 function -- binds
#' [`Cec2022::f_star`] (module doc section 1.2's table). `f_star` does not
#' depend on `dim`, so an internal probe `dim = 10` is used purely to
#' validate `fid` (every `fid` in `1..=12` accepts `dim = 10`, hybrids
#' included).
#'
#' @param fid CEC 2022 function id, `1..=12` (double, cast to `u32`).
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error if `fid` is outside `1..=12`.
#' @export
`sz_cec2022_f_star` <- function(`fid`) {
  .Call(savvy_sz_cec2022_f_star__impl, `fid`)
}

#' Exports the IOH archive at `log_root` as a COCO/BBOB "old format"
#' archive rooted at `out_dir` -- see `sezgi_bench::coco_export`. Returns
#' the list of written file paths (as strings), sorted for determinism.
#'
#' BBOB-only: COCO's "old format" IS the BBOB archive format and has no
#' CEC counterpart, so this errors (naming the offending suite) if
#' `log_root` holds any non-BBOB scenario, rather than silently merging it
#' into a `bbob`-labeled archive. A mixed BBOB+CEC tree must be filtered
#' to its BBOB records before exporting.
#'
#' @param log_root Path to the IOH archive directory (as passed to
#'   `sz_run_experiment(..., log_dir = ...)`).
#' @param out_dir Directory to write the COCO/BBOB archive under.
#' @returns A character vector of written file paths, sorted.
#' @export
`sz_coco_export` <- function(`log_root`, `out_dir`) {
  .Call(savvy_sz_coco_export__impl, `log_root`, `out_dir`)
}

#' ECDF/anytime curve(s) over the IOH archive at `log_root` -- see
#' `sezgi_bench::ecdf`/`sezgi_bench::ecdf_per_algo`.
#'
#' This is the raw savvy-generated binding (required args only; savvy has
#' no way to express a non-`NULL` default for a required argument in the
#' generated signature -- same raw/wrapper pattern as
#' `sz_run_experiment()`). The public R entry point with R-native defaults
#' (`per_algo = TRUE`) is the hand-written wrapper `sz_ecdf()` in
#' `R/anytime.R`, which calls this function.
#'
#' @param log_root Path to the IOH archive directory (as passed to
#'   `sz_run_experiment(..., log_dir = ...)`).
#' @param per_algo `TRUE` returns a named list, one `list(evals=,
#'   proportion=)` entry per distinct algo in the archive, named by algo
#'   (first-appearance order); `FALSE` returns a single pooled
#'   `list(evals=, proportion=)` over every scenario. Grouping (in both
#'   modes) is by algo only, not `(algo, suite)`: a mixed-suite tree pools
#'   both suites' runs into one algo's curve -- read a per-suite tree or
#'   filter `scenarios` by suite first for a suite-specific curve.
#' @param targets Optional numeric vector of precision targets; `NULL`
#'   uses `sezgi_bench::default_targets` (the COCO-convention 51-value
#'   set).
#' @returns A named list (see `per_algo`).
#' @noRd
`sz_ecdf_raw` <- function(`log_root`, `per_algo`, `targets` = NULL) {
  .Call(savvy_sz_ecdf_raw__impl, `log_root`, `per_algo`, `targets`)
}

#' Direct, one-shot constraint-row evaluation, mirroring `sz_mo_evaluate`'s
#' calling convention exactly (same [`mo_problem_from_str`] mapping, same
#' [`genotype_from_flat`] decoding) -- binds
#' [`sezgi_core::mo::MoProblem::evaluate_constraints_batch`].
#'
#' This is the raw savvy-generated binding, same raw/wrapper pattern as
#' `sz_mo_evaluate()` / `sz_mo_evaluate_raw()` above -- the public R entry
#' point is the hand-written wrapper `sz_mo_evaluate_constraints()` in
#' `R/mo.R`.
#'
#' @param problem Same mapping as `sz_nsga2_raw`.
#' @param x A numeric vector, the decision vector to evaluate.
#' @param dim Optional decision-space dimensionality -- same rule as
#'   `sz_nsga2_raw`.
#' @param m Optional number of objectives -- same rule as `sz_nsga2_raw`.
#' @param k Optional WFG position-related-parameter count; wfg-only.
#' @param l Optional WFG distance-related-parameter count; wfg-only.
#' @returns A numeric vector (`g_1..g_ncon`, `g_j >= 0` meaning SATISFIED --
#'   see [`sezgi_core::mo::MoProblem::evaluate_constraints_batch`]'s own doc
#'   for the pinned sign convention), or `NULL` for an unconstrained
#'   problem (every zdt/wfg problem, and dtlz1-7).
#'
#' # Errors
#' Same as `sz_mo_evaluate_raw`.
#' @noRd
`sz_mo_evaluate_constraints_raw` <- function(`problem`, `x`, `dim` = NULL, `m` = NULL, `k` = NULL, `l` = NULL) {
  .Call(savvy_sz_mo_evaluate_constraints_raw__impl, `problem`, `x`, `dim`, `m`, `k`, `l`)
}

#' Direct, one-shot objective evaluation of a decision vector `x` against
#' any `sz_mo_*` problem string, bypassing `sz_nsga2`'s population/budget
#' machinery entirely -- binds [`sezgi_core::mo::MoProblem::evaluate_batch`]
#' for a single individual. Same `problem`/`dim`/`m`/`k`/`l` mapping as
#' `sz_nsga2_raw`, via [`mo_problem_from_str`].
#'
#' `# sezgi decision:` (M3-7 Task 11) added purely so this binding's OWN
#' test suite can pin exact fixture values (zdt5's all-ones/all-zeros hand
#' fixtures, dtlz8/9's hand fixtures, the committed
#' `wfg_reference_values.json` points) directly from R -- mirroring
#' py-sezgi's own `mo.evaluate` (added for the identical reason, M3-7 Task
#' 10) and the existing `sz_cec2022_evaluate`/`sz_cec2014_evaluate`/
#' `sz_cec2017_evaluate` one-shot-evaluation convention already established
#' in this crate.
#'
#' `x`: for an all-Float problem, its raw decision values; for zdt5 (the
#' only all-Binary problem reachable here), each entry is read as a bit
#' (`!= 0.0` -> `TRUE`) -- see [`genotype_from_flat`]'s own doc.
#'
#' This is the raw savvy-generated binding (`problem`/`x` required,
#' `dim`/`m`/`k`/`l` trailing since they are all optional). The public R
#' entry point with R-native argument order (`problem, dim, x, m, k, l`) is
#' the hand-written wrapper `sz_mo_evaluate()` in `R/mo.R`, which calls this
#' function -- same raw/wrapper pattern as `sz_nsga2()` / `sz_nsga2_raw()`.
#'
#' @param problem Same mapping as `sz_nsga2_raw`.
#' @param x A numeric vector, the decision vector to evaluate.
#' @param dim Optional decision-space dimensionality -- same rule as
#'   `sz_nsga2_raw`.
#' @param m Optional number of objectives -- same rule as `sz_nsga2_raw`.
#' @param k Optional WFG position-related-parameter count; wfg-only.
#' @param l Optional WFG distance-related-parameter count; wfg-only.
#' @returns A numeric vector, length equal to the problem's own objective
#'   count.
#'
#' # Errors
#' Same problem-construction errors as `sz_nsga2_raw`/`sz_mo_pareto_front`,
#' plus a savvy error if `length(x)` does not match the problem's own
#' dimension.
#' @noRd
`sz_mo_evaluate_raw` <- function(`problem`, `x`, `dim` = NULL, `m` = NULL, `k` = NULL, `l` = NULL) {
  .Call(savvy_sz_mo_evaluate_raw__impl, `problem`, `x`, `dim`, `m`, `k`, `l`)
}

#' General-M exact hypervolume (While, Bradstreet & Barone 2012, the WFG
#' algorithm; `M == 2` delegates internally to the SAME
#' [`sezgi_stats::hypervolume_2d`]) -- binds [`sezgi_stats::hypervolume`]
#' (M3-7 Task 8/11). Unlike `sz_mo_hypervolume_2d`, `front`/`ref_point` may
#' have any number `M >= 1` of objectives.
#'
#' `ref_point` is REQUIRED, with no default: `sezgi_stats::moo_indicators`'s
#' own module doc, "Choosing a reference point: explicit-always, contested
#' in the literature" section, deliberately never picks one for the caller.
#' One common convention from that literature (also critiqued by Ishibuchi,
#' Imada, Setoguchi & Nojima 2018, "How to Specify a Reference Point in
#' Hypervolume Calculation for Fair Performance Comparison", GECCO
#' Companion) is the analytic front's nadir point (the componentwise worst
#' value across the front) scaled by `1.1` -- a caller-supplied choice,
#' never defaulted here.
#'
#' @param front A numeric matrix, rows = points, any number of columns --
#'   see this module's own doc, "Container-idiom decisions".
#' @param ref_point A numeric vector, same length as `front`'s column
#'   count.
#' @returns A numeric scalar. An EMPTY `front` is NOT an error -- it
#'   returns `0.0` (the algorithm's own base case).
#'
#' # Errors
#' A savvy error for any [`sezgi_stats::StatsError`] (`ref_point` empty, a
#' `front` row with a different number of objectives than `ref_point`, or a
#' non-finite value), or if `front` is not a matrix.
#' @export
`sz_mo_hypervolume` <- function(`front`, `ref_point`) {
  .Call(savvy_sz_mo_hypervolume__impl, `front`, `ref_point`)
}

#' Exact 2-objective hypervolume (Zitzler & Thiele 1999 S-metric,
#' reference-point variant; minimization) -- binds
#' [`sezgi_stats::hypervolume_2d`] exactly. See that function's doc for the
#' pinned definition.
#'
#' @param front A numeric matrix, rows = points, 2 columns (`f1`, `f2`) --
#'   R-idiomatic (unlike py-sezgi's `list[[f1,f2],...]`); see this module's
#'   own doc, "Container-idiom decisions". Build with `rbind()`/`matrix()`.
#' @param ref_point A 2-element numeric vector.
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error if `ref_point` does not have exactly 2 values, if `front`
#' is not a matrix, or for any [`sezgi_stats::StatsError`] (empty front, a
#' non-2-objective row, or a non-finite value).
#' @export
`sz_mo_hypervolume_2d` <- function(`front`, `ref_point`) {
  .Call(savvy_sz_mo_hypervolume_2d__impl, `front`, `ref_point`)
}

#' Inverted Generational Distance (Ishibuchi et al. 2015, eq. 12, `p = 1`)
#' -- binds [`sezgi_stats::igd`] exactly. Any (equal, consistent) number of
#' objectives across both `front` and `reference_front`.
#'
#' @param front A numeric matrix, rows = points -- see this module's own
#'   doc, "Container-idiom decisions".
#' @param reference_front A numeric matrix, rows = points, same column
#'   count as `front`.
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error if either argument is not a matrix, or for any
#' [`sezgi_stats::StatsError`] (an empty `front`/`reference_front`, a
#' dimension mismatch, or a non-finite value).
#' @export
`sz_mo_igd` <- function(`front`, `reference_front`) {
  .Call(savvy_sz_mo_igd__impl, `front`, `reference_front`)
}

#' A deterministic `n`-point sample of the analytic Pareto front in
#' OBJECTIVE space, if known -- binds [`sezgi_core::mo::MoProblem::pareto_front`].
#' Same `problem`/`dim`/`m`/`k`/`l` mapping as `sz_nsga2_raw` (see this
#' module's own doc).
#'
#' This is the raw savvy-generated binding (`problem`/`n` required,
#' `dim`/`m`/`k`/`l` trailing since they are all optional). The public R
#' entry point with R-native argument order is the hand-written wrapper
#' `sz_mo_pareto_front()` in `R/mo.R`, which calls this function -- same
#' raw/wrapper pattern as `sz_nsga2()` / `sz_nsga2_raw()`.
#'
#' @param problem Same mapping as `sz_nsga2_raw`.
#' @param n Number of front points to sample (double, cast to `usize`).
#' @param dim Optional decision-space dimensionality (double, cast to
#'   `usize`) -- same rule as `sz_nsga2_raw`.
#' @param m Optional number of objectives (double, cast to `usize`) --
#'   same rule as `sz_nsga2_raw`.
#' @param k Optional WFG position-related-parameter count; wfg-only.
#' @param l Optional WFG distance-related-parameter count; wfg-only.
#' @returns A `list` of `n` numeric vectors (see this module's own doc,
#'   "Container-idiom decisions"), or `NULL` when the problem has no known
#'   analytic front sample (e.g. DTLZ5/DTLZ6 with `m > 3`, or WFG1/WFG2
#'   unconditionally) -- mirrors py-sezgi's `sezgi.mo.pareto_front()`
#'   return exactly.
#'
#' # Errors
#' Same as `sz_nsga2_raw`'s problem-construction errors.
#' @noRd
`sz_mo_pareto_front_raw` <- function(`problem`, `n`, `dim` = NULL, `m` = NULL, `k` = NULL, `l` = NULL) {
  .Call(savvy_sz_mo_pareto_front_raw__impl, `problem`, `n`, `dim`, `m`, `k`, `l`)
}

#' Reads a "sezgi-moa v1" archive file written by `sz_nsga2(..., log_dir =,
#' label =)` (M3-7 Task 9/11) -- binds [`sezgi_bench::read_moa`]. Returns a
#' named list:
#' - `algo` (character): the logging algorithm name -- always `"nsga2"`
#'   today (`nsga2_run_logged`'s own fixed `NSGA2_ALGO_NAME`).
#' - `problem` (character): the `label` `sz_nsga2` was called with. **Kept
#'   as the literal on-disk header key name** (`crates/bench/src/mo_archive.rs`'s
#'   own format grammar: the header line is `problem <label>`, not
#'   `label <label>`) rather than renamed here to `"label"` -- this binding
#'   stays a thin, direct mirror of `MoArchiveRun`'s own field names, so a
#'   reader cross-checking against the Rust struct (or the Python binding,
#'   M3-7 Task 10) sees the SAME key everywhere.
#' - `m`, `seed`, `budget` (double, whole-number-valued -- R has no native
#'   integer64).
#' - `kind` (character): `"float"` or `"binary"`.
#' - `records` (list, in file/eval order): each entry a named list with
#'   `eval_index` (double), `objectives` (numeric vector), `genotype`
#'   (numeric vector for `kind = "float"`, `logical` vector for
#'   `kind = "binary"` -- see this module's own doc, "Container-idiom
#'   decisions").
#' - `archive` (list of numeric vectors): the reconstructed nondominated
#'   archive at evaluation budget `at`, via `MoArchiveRun::archive_at`.
#'
#' `# sezgi decision:` `at = NULL` (the default) resolves to the file's own
#' logged `budget` header field (the full run's final archive) -- mirrors
#' py-sezgi's own `mo.read_moa(path, at=None)` default exactly.
#'
#' This is directly `@export`ed (no hand-written wrapper needed): `at` is
#' the only optional parameter and trails `path`, so savvy already emits
#' `at = NULL` in the generated R signature -- same pattern as
#' `sz_mo_hypervolume_2d`/`sz_mo_igd`.
#'
#' @param path Path to a sezgi-moa v1 file.
#' @param at Optional evaluation budget (double, cast to `u64`) at which to
#'   reconstruct the archive; `NULL` (default) uses the file's own logged
#'   `budget`.
#' @returns A named list -- see this function's own doc above.
#'
#' # Errors
#' A savvy error for any [`sezgi_bench::MoArchiveError`] (missing file, a
#' malformed header, or a malformed record line).
#' @export
`sz_mo_read_moa` <- function(`path`, `at` = NULL) {
  .Call(savvy_sz_mo_read_moa__impl, `path`, `at`)
}

#' NSGA-II run (Deb, Pratap, Agarwal & Meyarivan 2002) -- binds
#' [`sezgi_components::nsga2::nsga2_run`] (or, when `log_dir` is given,
#' [`sezgi_bench::nsga2_run_logged`] -- see this module's own doc). See this
#' module's own doc for the `problem`/`dim`/`m`/`k`/`l` mapping.
#'
#' This is the raw savvy-generated binding: every `Option`-typed parameter
#' (savvy's own "optional args last" requirement) trails the required ones
#' in `dim, m, p_m, p_m_bin, k, l, log_dir, label` order. The public R entry
#' point with R-native argument order and defaults is the hand-written
#' wrapper `sz_nsga2()` in `R/mo.R`, which calls this function -- same
#' raw/wrapper pattern as `sz_bias_structural()` / `sz_bias_structural_raw()`.
#'
#' @param problem One of `"zdt1"`..`"zdt6"`, `"dtlz1"`..`"dtlz9"`, or
#'   `"wfg1"`..`"wfg9"`.
#' @param pop_size Population size (double, cast to `usize`). Must be
#'   `>= 4` and a multiple of 4 (KanGAL's double-permutation tournament
#'   pairing requires it -- NOT merely "even, >= 4").
#' @param budget Total evaluation budget (double, cast to `u64`).
#' @param seed Master RNG seed (double, cast to `u64`).
#' @param eta_c SBX distribution index. Paper default: `20.0`.
#' @param eta_m Polynomial-mutation distribution index. Paper default:
#'   `20.0`.
#' @param p_c SBX crossover probability. Paper default: `0.9`.
#' @param p_c_bin Binary-genotype crossover probability. Default `0.9`
#'   (mirrors `p_c`'s own default; only consulted for an all-Binary space,
#'   i.e. zdt5).
#' @param dim Optional decision-space dimensionality (double, cast to
#'   `usize`). REQUIRED (may be `NULL`, but the argument itself must be
#'   supplied) for zdt1-4/6 and dtlz1-9; REJECTED (must be `NULL`) for
#'   zdt5 and wfg1-9.
#' @param m Optional number of objectives (double, cast to `usize`).
#'   REQUIRED for dtlz/wfg problems; must be `NULL` for zdt problems.
#' @param p_m Optional per-variable mutation probability. `NULL` resolves
#'   on the Rust side to `1 / n_variables` (the paper's own default), never
#'   re-derived here.
#' @param p_m_bin Optional per-bit binary mutation probability. `NULL`
#'   resolves on the Rust side to `1 / l` (the paper's own binary-coded
#'   default); only consulted for an all-Binary space.
#' @param k Optional WFG position-related-parameter count. `NULL` resolves
#'   to the toolkit's own recommended default; wfg-only.
#' @param l Optional WFG distance-related-parameter count. `NULL` resolves
#'   to `20`; wfg-only.
#' @param log_dir Optional sezgi-moa v1 log directory. When given, `label`
#'   is required and the run additionally streams to
#'   `<log_dir>/<label>-s<seed>.moa`.
#' @param label Optional sezgi-moa run label; required iff `log_dir` is
#'   given.
#' @returns A named list with `individuals`, `objectives`, `front0`,
#'   `evals_used`, and (present only for a constrained problem) `violations`
#'   -- see this module's own doc.
#'
#' # Errors
#' A savvy error for an unrecognized `problem` string, a `dim`/`m`/`k`/`l`
#' given where the problem does not accept it (or missing where required --
#' see `mo_problem_from_str`'s own doc), a `log_dir` given without `label`,
#' or any [`sezgi_components::nsga2::Nsga2Error`] / `MoRunLoggedError`
#' (including `pop_size` failing the `>= 4 && pop_size % 4 == 0` check).
#' @noRd
`sz_nsga2_raw` <- function(`problem`, `pop_size`, `budget`, `seed`, `eta_c`, `eta_m`, `p_c`, `p_c_bin`, `dim` = NULL, `m` = NULL, `p_m` = NULL, `p_m_bin` = NULL, `k` = NULL, `l` = NULL, `log_dir` = NULL, `label` = NULL) {
  .Call(savvy_sz_nsga2_raw__impl, `problem`, `pop_size`, `budget`, `seed`, `eta_c`, `eta_m`, `p_c`, `p_c_bin`, `dim`, `m`, `p_m`, `p_m_bin`, `k`, `l`, `log_dir`, `label`)
}

#' Builds one `sezgi_stats::PaperPackage` PER DISTINCT BUDGET present in a
#' `sz_run_experiment()` data.frame's columns, in ascending budget order --
#' see `sezgi_bench::reporting::per_budget_packages`. Per Piotrowski et al.
#' (2025), algorithm rankings can flip across budgets, so this makes
#' multi-budget reporting the default rather than a single, arbitrarily
#' chosen budget's report.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults is the hand-written wrapper `sz_per_budget_packages()`
#' in `R/experiment.R`, which extracts these columns from a data.frame and
#' calls this function.
#'
#' @param algo Character vector (the `algo` column).
#' @param fid,dim,instance,seed,budget_col,best_f,f_opt,evals Numeric
#'   vectors (the correspondingly-named columns).
#' @param suite Character vector (the `suite` column) -- see
#'   `records_from_columns`'s doc comment for the backward-compat default
#'   the R-native wrapper applies when `df` has no `suite` column.
#' @param rope Region of practical equivalence half-width (>= 0) for the
#'   Bayesian signed-rank test, forwarded to every budget's package.
#' @param samples Number of Monte Carlo samples per pair (double, cast to
#'   `u64`).
#' @param seed Master RNG seed (double, cast to `u64`), forwarded to every
#'   budget's package.
#' @param aggregate `"mean"` or `"median"`.
#' @returns A named list, one entry per distinct budget in ascending order,
#'   named by the budget (as a string); each value has exactly the shape
#'   `sz_stats_paper_package_raw()` returns.
#' @noRd
`sz_per_budget_packages_raw` <- function(`algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `suite`, `best_f`, `f_opt`, `evals`, `rope`, `samples`, `master_seed`, `aggregate`) {
  .Call(savvy_sz_per_budget_packages_raw__impl, `algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `suite`, `best_f`, `f_opt`, `evals`, `rope`, `samples`, `master_seed`, `aggregate`)
}

#' Builds an Artificial Bee Colony spec (Karaboga 2005, TR-06 / Karaboga &
#' Basturk 2007, Journal of Global Optimization -- a labeled metaphor
#' preset; see `crates/components/src/abc.rs`'s module doc for the full
#' provenance extraction against the author's own `ABCorig.m` plus the
#' official `Python_ABC` port, the pop<->food-source convention
#' resolution, the fitness-transform monotonicity proof, and the
#' phase-design adjudication -- a SINGLE stage, not two symmetric stages
#' like `tlbo`: `gen/abc-employed` + the new `replace/abc-trial-greedy`,
#' plus the new `adapter/abc-onlooker-scout` folding the onlooker AND
#' scout phases together) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (food-source count `SN`, NOT Karaboga's
#'   colony size `NP=2*SN`). Canonical is 20.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_abc` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_abc__impl, `pop_size`, `budget`)
}

#' Builds an Ant Lion Optimizer spec (Mirjalili 2015, Advances in
#' Engineering Software -- a labeled metaphor preset; see
#' `crates/components/src/alo.rs`'s module doc for the full provenance
#' extraction against the author's own `ALO.m`/`Random_walk_around_
#' antlion.m`/`RouletteWheelSelection.m`, the faithful-full-walk cost
#' decision, and the elitism design adjudication -- the antlion population
#' itself is the persisted memory via `replace/mu-plus-lambda`, no
#' blackboard state needed) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (ant/antlion count). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_alo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_alo__impl, `pop_size`, `budget`)
}

#' Builds a Bat Algorithm spec (Yang, X.-S. 2010, NICSO -- a labeled
#' metaphor preset, see `crates/components/src/ba.rs`'s module doc for the
#' tier note, citation, the verified `bat_algorithm.m` loop structure, the
#' verified fixed-loudness/pulse-rate finding, the two composing
#' sign-inversion deltas in the frequency draw and velocity term, and the
#' design adjudication for the new `replace/bat-loudness-greedy`
#' acceptance-coupled replacer) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of bats). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_bat` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_bat__impl, `pop_size`, `budget`)
}

#' Builds a (mu/mu_w,lambda)-CMA-ES algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (lambda).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cmaes` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_cmaes__impl, `pop_size`, `budget`)
}

#' Builds a CMA-ES with IPOP-style stagnation restarts algorithm spec as
#' JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (determines the initial population size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cmaes_ipop` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_cmaes_ipop__impl, `dim`, `budget`)
}

#' Builds a Cuckoo Search algorithm spec (Yang & Deb 2009 -- a labeled
#' metaphor preset, see `crates/components/src/cs.rs`'s module doc for the
#' tier note, citation and pinned draw order) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (nest count). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_cuckoo_search` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_cuckoo_search__impl, `pop_size`, `budget`)
}

#' Builds a DE/best/1/bin algorithm spec (uniform init, clamp boundary,
#' one-to-one-greedy replacement) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_de_best_1` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_de_best_1__impl, `pop_size`, `budget`)
}

#' Builds a DE/rand/1/bin algorithm spec (uniform init, clamp boundary,
#' one-to-one-greedy replacement) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_de_rand_1` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_de_rand_1__impl, `pop_size`, `budget`)
}

#' Builds a (mu/mu_w,lambda)-ES algorithm spec (mutation step drawn from
#' `dist`) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL`/string default in the generated signature).
#' The public R entry point with R-native defaults is the hand-written
#' wrapper `sz_preset_es_mu_plus_lambda()` in `R/presets.R`, which calls this
#' function -- same raw/wrapper pattern as `sz_run_experiment()` /
#' `sz_run_experiment_raw()` and `sz_stats_bayesian_signed_rank()` /
#' `sz_stats_bayesian_signed_rank_raw()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @param dist Mutation distribution: one of `"uniform"`, `"gaussian"`,
#'   `"cauchy"`, `"levy"`, `"student_t"`, `"laplace"`.
#' @param mean Gaussian mean (used only when `dist = "gaussian"`).
#' @param sigma Gaussian std-dev (used only when `dist = "gaussian"`).
#' @param loc Cauchy/Laplace location (used only when `dist` is `"cauchy"`
#'   or `"laplace"`).
#' @param scale Cauchy/Laplace scale (used only when `dist` is `"cauchy"`
#'   or `"laplace"`).
#' @param alpha Levy stability parameter (used only when `dist = "levy"`).
#' @param nu Student-t degrees of freedom (used only when `dist =
#'   "student_t"`).
#' @returns A character scalar with the algorithm spec as JSON.
#' @noRd
`sz_preset_es_mu_plus_lambda_raw` <- function(`pop_size`, `budget`, `dist`, `mean`, `sigma`, `loc`, `scale`, `alpha`, `nu`) {
  .Call(savvy_sz_preset_es_mu_plus_lambda_raw__impl, `pop_size`, `budget`, `dist`, `mean`, `sigma`, `loc`, `scale`, `alpha`, `nu`)
}

#' Builds a Firefly Algorithm (Yang, X.-S., *Nature-Inspired Metaheuristic
#' Algorithms*, 2nd ed., Luniver Press, 2010 -- a labeled metaphor preset,
#' see `crates/components/src/fa.rs`'s module doc for the tier note,
#' citation, the verified `fa_ndim.m`/`ffa_move.m` loop structure, the
#' floored attractiveness formula, the closed-form `alpha` decay, and the
#' hybrid in-place-self/live-distance/frozen-target double-loop semantics)
#' spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of fireflies). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_firefly` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_firefly__impl, `pop_size`, `budget`)
}

#' Builds a Flower Pollination Algorithm spec (Yang, X.-S. 2012, UCNC -- a
#' labeled metaphor preset, see `crates/components/src/fpa.rs`'s module doc
#' for the tier note, citation, the verified `fpa_demo.m` loop structure,
#' the switch-branch orientation delta, the global-step sign delta reusing
#' `cs.rs`'s `cs_dim_step` verbatim, the local-step self-selection-not-
#' excluded finding, and the min_pop adjustment from 3 down to 2) as JSON,
#' ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of flowers). Canonical is 25.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_fpa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_fpa__impl, `pop_size`, `budget`)
}

#' Builds a permutation-space GA spec (tournament selection, order
#' crossover, swap mutation -- `gen/ga-perm` + `replace/mu-plus-lambda`) as
#' JSON, ready to pass to `sz_solve_tsp()`. Binds
#' [`sezgi_components::presets::ga_perm`] exactly -- same preset py-sezgi's
#' `sezgi.presets.ga_perm` binds (M3-3 Task 9).
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_ga_perm` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_ga_perm__impl, `pop_size`, `budget`)
}

#' Builds a real-coded GA (SBX crossover, polynomial mutation) algorithm spec
#' as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_ga_real` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_ga_real__impl, `pop_size`, `budget`)
}

#' Builds a Grasshopper Optimisation Algorithm spec (Saremi, Mirjalili &
#' Lewis 2017 -- a labeled metaphor preset, see
#' `crates/components/src/goa.rs`'s module doc for the tier note, citation,
#' the IMPLEMENTER-VERIFY distance-normalization resolution and the
#' zero-RNG-draw arithmetic-order pin) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (swarm size). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_goa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_goa__impl, `pop_size`, `budget`)
}

#' Builds a Gravitational Search Algorithm spec (Rashedi, Nezamabadi-pour &
#' Saryazdi 2009, Information Sciences -- a labeled metaphor preset, and the
#' wave's LAST stateful/blackboard algorithm; see
#' `crates/components/src/gsa.rs`'s module doc for the full provenance
#' extraction against the author's own `GSA.m`/`Gconstant.m`/
#' `massCalculation.m`/`Gfield.m`/`move.m`, the verified `M_i`-free force
#' delta, and the confirmation that GSA's own `Fbest`/`Lbest` never feed
#' back into the mechanism) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (agent count). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_gsa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_gsa__impl, `pop_size`, `budget`)
}

#' Builds a Grey Wolf Optimizer algorithm spec (Mirjalili, Mirjalili & Lewis
#' 2014 -- a labeled metaphor preset, see `crates/components/src/gwo.rs`'s
#' module doc for the tier note and citations) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (pack size). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_gwo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_gwo__impl, `pop_size`, `budget`)
}

#' Builds a Harmony Search algorithm spec (Geem, Kim & Loganathan 2001 -- a
#' labeled metaphor preset, see `crates/components/src/hs.rs`'s module doc
#' for the tier note and citations) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (Harmony Memory Size, HMS). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_harmony_search` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_harmony_search__impl, `pop_size`, `budget`)
}

#' Builds a Harris Hawks Optimization spec (Heidari, Mirjalili, Faris,
#' Aljarah, Mafarja & Chen 2019, Future Generation Computer Systems -- a
#' labeled metaphor preset, and the wave's most structurally complex one: a
#' multi-branch escape-energy tree whose progressive rapid-dive
#' sub-branches evaluate mid-`generate()`. See
#' `crates/components/src/hho.rs`'s module doc for the full provenance
#' extraction against the paper author's own `HHO.m`, the hard/soft
#' besiege mapping delta, the mean(X)/random-hawk in-place semantics, and
#' the prominent in-generator-evaluation eval-accounting design decision)
#' as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (hawk count). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_hho` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_hho__impl, `pop_size`, `budget`)
}

#' Builds a JAYA spec (Rao 2016 -- a labeled metaphor preset, see
#' `crates/components/src/jaya.rs`'s module doc for the tier note,
#' citation, the primary-paper-verified worked-example reproduction, the
#' shared-per-dimension-per-generation `r1`/`r2` draw finding and the
#' greedy-replacement delta vs mealpy's misleadingly-named `OriginalJA`) as
#' JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (candidate count). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_jaya` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_jaya__impl, `pop_size`, `budget`)
}

#' Builds a jDE algorithm spec (self-adaptive F/CR DE) as JSON, ready to pass
#' to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_jde` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_jde__impl, `pop_size`, `budget`)
}

#' Builds an L-SHADE algorithm spec (population linearly reduced from
#' `18 * dim`) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (determines the initial population size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_lshade` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_lshade__impl, `dim`, `budget`)
}

#' Builds an MFO (Moth-Flame Optimization; Mirjalili 2015 -- a labeled
#' metaphor preset, see `crates/components/src/mfo.rs`'s module doc for the
#' tier note, citation, the verified `MFO.m` loop structure, the two subtle
#' draw/index deltas found vs the plan's sketch, and the blackboard
#' flame-memory design) spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of search agents). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_mfo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_mfo__impl, `pop_size`, `budget`)
}

#' Builds a Nelder-Mead simplex algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param dim Problem dimension (population size is fixed to `dim + 1`).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_nelder_mead` <- function(`dim`, `budget`) {
  .Call(savvy_sz_preset_nelder_mead__impl, `dim`, `budget`)
}

#' Builds a PSO (Clerc-Kennedy constriction) algorithm spec as JSON, ready to
#' pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (swarm size).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_pso` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_pso__impl, `pop_size`, `budget`)
}

#' Builds a random search algorithm spec as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (resampled uniformly each generation).
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_random_search` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_random_search__impl, `pop_size`, `budget`)
}

#' Builds a simulated annealing (Metropolis, geometric cooling) algorithm
#' spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_sa` <- function(`budget`) {
  .Call(savvy_sz_preset_sa__impl, `budget`)
}

#' Builds a Sine Cosine Algorithm spec (Mirjalili 2016 -- a labeled
#' metaphor preset, see `crates/components/src/sca.rs`'s module doc for the
#' tier note, citation, the `SCA.m`-verified pinned draw order and the
#' mealpy-`OriginalSCA` replacer delta) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of search agents). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_sca` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_sca__impl, `pop_size`, `budget`)
}

#' Builds a SHADE algorithm spec as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_shade` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_shade__impl, `pop_size`, `budget`)
}

#' Builds an SSA (Salp Swarm Algorithm; Mirjalili et al. 2017 -- a labeled
#' metaphor preset, see `crates/components/src/ssa.rs`'s module doc for the
#' tier note, citation, the verified `SSA.m` half-population leader/follower
#' split, the leader sign-branch pin, the verified in-place follower-chain
#' semantics, and the persisted-food-vs-current-pop-best delta) spec as
#' JSON, ready to pass to `sz_solve_bbob()`.
#'
#' @param pop_size Population size (number of salps). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_ssa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_ssa__impl, `pop_size`, `budget`)
}

#' Builds a Teaching-Learning-Based Optimization spec (Rao, Savsani &
#' Vakharia 2011, Computer-Aided Design -- a labeled metaphor preset, and
#' sezgi's FIRST multi-stage preset: two `[[stages]]` (teacher, then
#' learner) run in sequence every generation. See
#' `crates/components/src/tlbo.rs`'s module doc for the full provenance
#' extraction against Yarpiz's `tlbo.m` -- explicitly labeled third-party,
#' not Rao's own code -- the per-learner teaching-factor finding, the
#' unconditionally-distinct partner-selection finding, the min_pop
#' adjustment from 3 down to 2, and the "parameter-free" framing's
#' Črepinšek/Liu/Mernik (2012) counterpoint) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (class size). Canonical is 30.
#' @param budget Evaluation budget. A full generation costs `2 * pop_size`
#'   evaluations (both stages evaluate).
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_tlbo` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_tlbo__impl, `pop_size`, `budget`)
}

#' Builds a Whale Optimization Algorithm spec (Mirjalili & Lewis 2016 -- a
#' labeled metaphor preset, see `crates/components/src/woa.rs`'s module doc
#' for the tier note and citations) as JSON, ready to pass to
#' `sz_solve_bbob()`.
#'
#' @param pop_size Population size (school size). Canonical is 30.
#' @param budget Evaluation budget.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
`sz_preset_woa` <- function(`pop_size`, `budget`) {
  .Call(savvy_sz_preset_woa__impl, `pop_size`, `budget`)
}

#' Reconstructs `RunRecord`s from an on-disk IOH archive at `log_root` (as
#' written by `sz_run_experiment(..., log_dir = ...)`), one record per
#' `(run, budget)` pair -- see `sezgi_bench::ioh_records`'s doc comment for
#' the exact `best_f`/`evals_used` semantics and the curtailed-view-vs-
#' independent-run distinction for budgets smaller than a run's logged
#' budget.
#'
#' Returns the SAME data.frame shape `sz_run_experiment()` returns (via
#' [`records_to_data_frame`]), so `sz_results_matrix()`/
#' `sz_per_budget_packages()` accept it unchanged.
#'
#' @param log_root Path to the IOH archive directory (as passed to
#'   `sz_run_experiment(..., log_dir = ...)`).
#' @param budgets Numeric vector of evaluation budgets to reconstruct
#'   records at.
#' @returns A data.frame with the same columns as `sz_run_experiment()`.
#' @export
`sz_read_ioh_records` <- function(`log_root`, `budgets`) {
  .Call(savvy_sz_read_ioh_records__impl, `log_root`, `budgets`)
}

#' Builds a `sezgi_stats`-shaped results matrix for one `budget` from a
#' `sz_run_experiment()` data.frame's columns -- see
#' `sezgi_bench::reporting::results_matrix`.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults is the hand-written wrapper `sz_results_matrix()` in
#' `R/experiment.R`, which extracts these columns from a data.frame and
#' calls this function.
#'
#' @param algo Character vector (the `algo` column).
#' @param fid,dim,instance,seed,budget_col,best_f,f_opt,evals Numeric
#'   vectors (the correspondingly-named columns; `budget_col` avoids a name
#'   clash with the scalar `budget` argument below).
#' @param budget Only rows with this budget are used.
#' @param aggregate `"mean"` or `"median"`.
#' @param suite Character vector (the `suite` column) -- see
#'   `records_from_columns`'s doc comment for the backward-compat default
#'   the R-native wrapper applies when `df` has no `suite` column.
#' @returns A named list with `algo_names` (character vector),
#'   `problem_labels` (character vector, `f{fid}d{dim}i{instance}` for the
#'   BBOB suite, `{short}-f{fid}d{dim}i{instance}` for any other suite),
#'   and `matrix` (numeric matrix, rows = problems, columns = algorithms).
#' @noRd
`sz_results_matrix_raw` <- function(`algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `suite`, `best_f`, `f_opt`, `evals`, `budget`, `aggregate`) {
  .Call(savvy_sz_results_matrix_raw__impl, `algo`, `fid`, `dim`, `instance`, `seed`, `budget_col`, `suite`, `best_f`, `f_opt`, `evals`, `budget`, `aggregate`)
}

#' Runs an [`ExperimentSpec`] (parsed from `spec_toml`) and returns its
#' `RunRecord`s as a data.frame. This mirrors py-sezgi's `run_experiment`
#' exactly (see `py-sezgi/src/lib.rs`): `journal=None` runs via
#' `run_experiment_parallel`/`run_experiment_sequential` (chosen by
#' `parallel`); `journal=Some(path)` runs via `run_experiment_with_checkpoint`,
#' which resumes from -- and appends to -- an existing journal file at
#' `path`.
#'
#' This is the raw savvy-generated binding; the public R entry point with
#' R-native defaults (`parallel = TRUE`) is the hand-written wrapper
#' `sz_run_experiment()` in `R/experiment.R`, which calls this function.
#'
#' @param spec_toml Experiment spec as TOML.
#' @param parallel Whether to run in parallel via rayon.
#' @param journal Optional path to a checkpoint journal file.
#' @param threads Optional rayon thread-pool size. `usize` is not a
#'   supported savvy scalar arg type, so this comes in as `i32` and is cast;
#'   negative values are rejected explicitly (savvy has no unsigned integer
#'   scalar type to enforce this at the signature level).
#' @param log_dir Optional directory to log every run this call actually
#'   EXECUTES in IOH-profiler format (via `run_experiment_logged` when
#'   there is no `journal`, or via `run_experiment_with_checkpoint`'s own
#'   `log_dir` pass-through when there is -- see that function's doc
#'   comment: a run resumed from the journal was executed in a PRIOR
#'   process and is never re-logged).
#' @returns A data.frame with one row per run.
#'
#' The journal's spec hash is computed by `run_experiment_with_checkpoint`
#' from `spec` (the already-parsed `ExperimentSpec`), not from the raw
#' `spec_toml` text, so whitespace/comment-only edits to `spec_toml` never
#' invalidate a journal -- see `crates/bench/src/checkpoint.rs`.
#'
#' @noRd
`sz_run_experiment_raw` <- function(`spec_toml`, `parallel`, `journal` = NULL, `threads` = NULL, `log_dir` = NULL) {
  .Call(savvy_sz_run_experiment_raw__impl, `spec_toml`, `parallel`, `journal`, `threads`, `log_dir`)
}

#' Runs an algorithm spec on a BBOB problem and returns the result.
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_de_rand_1()`).
#' @param fid BBOB function id (>= 1).
#' @param dim Problem dimension (>= 1).
#' @param instance BBOB instance id (>= 1).
#' @param master_seed Master RNG seed.
#' @param run_id Run id (mixed into the seed for independent replicate streams).
#' @returns A named list with `best_f` (double), `evals` (double), and
#'   `best_x` (double vector) -- the best EVALUATED point (paired with
#'   `best_f`). For most algorithms this always lies within the declared
#'   domain. It is not guaranteed to for every algorithm: some (e.g. HHO)
#'   charge raw, pre-boundary-repair trial points against the budget before
#'   boundary repair, and such a point can become the reported best if it
#'   happens to be the run's own minimum.
#' @export
`sz_solve_bbob` <- function(`spec_json`, `fid`, `dim`, `instance`, `master_seed`, `run_id`) {
  .Call(savvy_sz_solve_bbob__impl, `spec_json`, `fid`, `dim`, `instance`, `master_seed`, `run_id`)
}

#' Runs an algorithm spec on a CEC 2014 (Liang, Qu & Suganthan 2013)
#' function via [`Cec2014::new`] and returns the result -- M3-6 Task 10,
#' mirroring `sz_solve_cec2022` exactly (`Engine::from_spec` + `engine.run`
#' + result conversion): same `best_f`/`evals`/`best_x` shape. See
#' [`Cec2014::new`]'s own doc for the exact `fid`/`dim` domain.
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_shade()`).
#' @param fid CEC 2014 function id, `1..=30` (double, cast to `u32`).
#' @param dim Problem dimension, one of `10`, `30` (double, cast to
#'   `usize`).
#' @param master_seed Master RNG seed.
#' @param run_id Run id (mixed into the seed for independent replicate streams).
#' @returns A named list with `best_f` (double), `evals` (double), and
#'   `best_x` (double vector) -- the best EVALUATED point (paired with
#'   `best_f`). Same caveat as `sz_solve_bbob()`: not every algorithm's
#'   reported best is guaranteed to lie within the declared domain.
#'
#' # Errors
#' A savvy error for `fid` outside `1..=30`, `dim` outside `{10,30}`, any
#' [`sezgi_core::spec`] parse error, or any [`sezgi_core::engine`] run error.
#' @export
`sz_solve_cec2014` <- function(`spec_json`, `fid`, `dim`, `master_seed`, `run_id`) {
  .Call(savvy_sz_solve_cec2014__impl, `spec_json`, `fid`, `dim`, `master_seed`, `run_id`)
}

#' Runs an algorithm spec on a CEC 2017 (Awad, Ali, Liang, Qu & Suganthan
#' 2016) function via [`Cec2017::new`] and returns the result -- M3-6 Task
#' 10, mirroring `sz_solve_cec2014` exactly. See [`Cec2017::new`]'s own doc
#' for the exact `fid`/`dim` domain.
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_shade()`).
#' @param fid CEC 2017 function id, `1` or `3..=30` (double, cast to `u32`);
#'   `fid = 2` was officially withdrawn from the suite.
#' @param dim Problem dimension, one of `10`, `30` (double, cast to
#'   `usize`).
#' @param master_seed Master RNG seed.
#' @param run_id Run id (mixed into the seed for independent replicate streams).
#' @returns A named list with `best_f` (double), `evals` (double), and
#'   `best_x` (double vector) -- the best EVALUATED point (paired with
#'   `best_f`). Same caveat as `sz_solve_bbob()`: not every algorithm's
#'   reported best is guaranteed to lie within the declared domain.
#'
#' # Errors
#' A savvy error for `fid` outside `{1} union {3..=30}`, `dim` outside
#' `{10,30}`, any [`sezgi_core::spec`] parse error, or any
#' [`sezgi_core::engine`] run error. `fid = 2` raises a dedicated error --
#' the Rust [`sezgi_problems::Cec2017Error::Withdrawn`] message is surfaced
#' VERBATIM.
#' @export
`sz_solve_cec2017` <- function(`spec_json`, `fid`, `dim`, `master_seed`, `run_id`) {
  .Call(savvy_sz_solve_cec2017__impl, `spec_json`, `fid`, `dim`, `master_seed`, `run_id`)
}

#' Runs an algorithm spec on a CEC 2022 (Kumar, Price, Mohamed, Hadi &
#' Suganthan 2021) function via [`Cec2022::new`] and returns the result --
#' M3-5 Task 4, closing the M3-3 gap (`docs/DECISIONS.md`'s M3-3 record,
#' ruling (g)): r-sezgi previously bound only direct evaluation
#' (`sz_cec2022_evaluate`/`sz_cec2022_f_star`), with no `solve()`-integrated
#' path, unlike py-sezgi's `sezgi.problems.cec2022(...)` + `sezgi.solve()`.
#' Mirrors `sz_solve_bbob`/`sz_solve_tsp` exactly (`Engine::from_spec` +
#' `engine.run` + result conversion): same `best_f`/`evals`/`best_x` shape,
#' not py-sezgi's own `solve()` dict shape (`best_f`/`best_x`/`evals_used`/
#' `iterations`) -- the established r-sezgi `sz_solve_*` convention governs
#' here too. See `Cec2022::new`'s own doc for the exact `fid`/`dim` domain.
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_shade()`).
#' @param fid CEC 2022 function id, `1..=12` (double, cast to `u32`).
#' @param dim Problem dimension, one of `2`, `10`, `20` (double, cast to
#'   `usize`); `dim = 2` is additionally rejected for a hybrid function
#'   (`fid` 6-8).
#' @param master_seed Master RNG seed.
#' @param run_id Run id (mixed into the seed for independent replicate streams).
#' @returns A named list with `best_f` (double), `evals` (double), and
#'   `best_x` (double vector) -- the best EVALUATED point (paired with
#'   `best_f`). Same caveat as `sz_solve_bbob()`: not every algorithm's
#'   reported best is guaranteed to lie within the declared domain.
#'
#' # Errors
#' A savvy error for `fid` outside `1..=12`, `dim` outside `{2,10,20}`,
#' `dim = 2` for a hybrid function, any [`sezgi_core::spec`] parse error, or
#' any [`sezgi_core::engine`] run error.
#' @export
`sz_solve_cec2022` <- function(`spec_json`, `fid`, `dim`, `master_seed`, `run_id`) {
  .Call(savvy_sz_solve_cec2022__impl, `spec_json`, `fid`, `dim`, `master_seed`, `run_id`)
}

#' Runs an algorithm spec on a TSPLIB VENDORED instance (`"berlin52"`,
#' `"eil51"`, `"st70"` -- via [`Tsp::vendored`]; UNLIKE `sz_tsp_load()`/
#' `sz_tsp_tour_length()` in `problems.rs`, raw TSPLIB text is not accepted
#' here -- mirrors py-sezgi's `sezgi.problems.tsp(name)`, which is likewise
#' vendored-only) and returns the result. Same output shape as
#' `sz_solve_bbob()` (`best_f`/`evals`/`best_x`), not py-sezgi's own
#' `solve()` dict shape (`best_f`/`best_x`/`evals_used`/`iterations`) -- the
#' established r-sezgi `sz_solve_*` convention governs here, not py-sezgi's
#' key names (see `problems.rs`'s module doc, "Index-convention decision",
#' for the general 1-based-vs-0-based rule this function's `best_x` also
#' follows).
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_ga_perm()`).
#' @param name A vendored TSPLIB instance name.
#' @param master_seed Master RNG seed.
#' @param run_id Run id (mixed into the seed for independent replicate streams).
#' @returns A named list with `best_f` (double), `evals` (double), and
#'   `best_x` (double vector -- a 1-based permutation of `1:n_cities`, the
#'   best EVALUATED tour, paired with `best_f`).
#'
#' # Errors
#' A savvy error if `name` is not one of the three vendored instances, for
#' any [`sezgi_core::spec`] parse error, or any [`sezgi_core::engine`] run
#' error.
#' @export
`sz_solve_tsp` <- function(`spec_json`, `name`, `master_seed`, `run_id`) {
  .Call(savvy_sz_solve_tsp__impl, `spec_json`, `name`, `master_seed`, `run_id`)
}

#' Bayesian signed-rank test with a region of practical equivalence (ROPE)
#' (Dirichlet-weighted Monte Carlo; see `sezgi_stats::bayesian_signed_rank`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults is
#' the hand-written wrapper `sz_stats_bayesian_signed_rank()` in
#' `R/stats.R`, which calls this function.
#'
#' @param a Numeric vector.
#' @param b Numeric vector, same length as `a`.
#' @param rope Region of practical equivalence half-width (>= 0).
#' @param samples Number of Monte Carlo samples. Passed to R as a double
#'   (savvy has no unsigned integer scalar arg type) and cast to `u64`
#'   after checking it is non-negative and finite.
#' @param seed Master RNG seed, passed through unchanged (`u64` via `f64`
#'   cast) — the same `(a, b, rope, samples, seed)` always produces a
#'   bit-identical result, since R calls the exact same seeded Rust core as
#'   Python and Rust.
#' @returns A named list with `p_left`, `p_rope`, `p_right` (mirrors
#'   py-sezgi's `stats_bayesian_signed_rank()` dict keys exactly).
#' @noRd
`sz_stats_bayesian_signed_rank_raw` <- function(`a`, `b`, `rope`, `samples`, `seed`) {
  .Call(savvy_sz_stats_bayesian_signed_rank_raw__impl, `a`, `b`, `rope`, `samples`, `seed`)
}

#' Cliff's delta effect size for two independent (unpaired) samples.
#'
#' @param a Numeric vector.
#' @param b Numeric vector.
#' @returns A numeric scalar in `[-1, 1]`.
#' @export
`sz_stats_cliffs_delta` <- function(`a`, `b`) {
  .Call(savvy_sz_stats_cliffs_delta__impl, `a`, `b`)
}

#' Qualitative magnitude label for a Cliff's delta value (Romano et al. 2006
#' thresholds).
#'
#' @param delta A Cliff's delta value (as returned by
#'   `sz_stats_cliffs_delta()`).
#' @returns A character scalar: one of `"negligible"`, `"small"`,
#'   `"medium"`, `"large"`.
#' @export
`sz_stats_cliffs_magnitude` <- function(`delta`) {
  .Call(savvy_sz_stats_cliffs_magnitude__impl, `delta`)
}

#' Runs the Friedman test on a results matrix.
#'
#' @param m A numeric matrix, rows = problems, columns = algorithms, lower
#'   is better (e.g. built with `rbind()` or `matrix()`).
#' @returns A named list with `statistic`, `p_value`, `mean_ranks` (mirrors
#'   py-sezgi's `stats_friedman()` dict keys exactly).
#' @export
`sz_stats_friedman` <- function(`m`) {
  .Call(savvy_sz_stats_friedman__impl, `m`)
}

#' Computes a comprehensive statistical analysis package for algorithm
#' comparison (Friedman, Nemenyi CD, pairwise Wilcoxon+Holm, Cliff's delta,
#' Bayesian signed-rank, Plackett-Luce, and LaTeX tables; see
#' `sezgi_stats::paper_package`).
#'
#' This is the raw savvy-generated binding (required args only; savvy has no
#' way to express a non-`NULL` default for a required argument in the
#' generated signature). The public R entry point with R-native defaults is
#' the hand-written wrapper `sz_stats_paper_package()` in `R/stats.R`, which
#' calls this function.
#'
#' @param algo_names Character vector of algorithm names.
#' @param problem_names Character vector of problem names.
#' @param m A numeric matrix, rows = problems (`length(problem_names)`),
#'   columns = algorithms (`length(algo_names)`), lower is better.
#' @param rope Region of practical equivalence half-width (>= 0) for the
#'   Bayesian signed-rank test.
#' @param samples Number of Monte Carlo samples per pair for the Bayesian
#'   signed-rank test (double, cast to `u64`; see
#'   `sz_stats_bayesian_signed_rank_raw()`).
#' @param seed Master RNG seed (double, cast to `u64`); per-pair seeds are
#'   `seed + pair_index` (wrapping), matching `sezgi_stats::paper_package`.
#' @returns A named list with `friedman` (nested list: `statistic`,
#'   `p_value`, `mean_ranks`), `nemenyi_cd`, `pairwise_wilcoxon_holm` (list
#'   of length-3 numeric vectors `c(i, j, adjusted_p)`, 0-based algorithm
#'   indices, i < j), `cliffs` (list of length-3 numeric vectors `c(i, j,
#'   delta)`), `bayes` (list of 3-element lists `list(i, j, bayes_result)`
#'   where `bayes_result` has `p_left`/`p_rope`/`p_right`),
#'   `plackett_luce` (nested list: `worths`, `p_best`, `iterations`),
#'   `latex_summary`, `latex_tests` (mirrors py-sezgi's
#'   `stats_paper_package()` dict keys exactly).
#' @noRd
`sz_stats_paper_package_raw` <- function(`algo_names`, `problem_names`, `m`, `rope`, `samples`, `seed`) {
  .Call(savvy_sz_stats_paper_package_raw__impl, `algo_names`, `problem_names`, `m`, `rope`, `samples`, `seed`)
}

#' Plackett-Luce maximum-likelihood ranking (Hunter 2004 MM algorithm; see
#' `sezgi_stats::plackett_luce`).
#'
#' @param rankings A `list` of integer (or integer-valued numeric) vectors,
#'   each a full ranking of the same `k` items as **1-based item ids**
#'   (R's natural indexing; e.g. `list(c(1, 2, 3), c(2, 1, 3))` for k = 3
#'   items, best first). Converted to 0-based indices before calling the
#'   Rust core, which expects a permutation of `0..k`.
#' @returns A named list with `worths`, `p_best`, `iterations` (mirrors
#'   py-sezgi's `stats_plackett_luce()` dict keys exactly).
#' @export
`sz_stats_plackett_luce` <- function(`rankings`) {
  .Call(savvy_sz_stats_plackett_luce__impl, `rankings`)
}

#' Wilcoxon signed-rank test for two paired samples (Pratt zero-handling and
#' tie correction; see `sezgi_stats::wilcoxon_signed_rank`).
#'
#' @param a Numeric vector.
#' @param b Numeric vector, same length as `a`.
#' @returns A named list with `w_statistic`, `z`, `p_value`, `n_effective`,
#'   `method` (`"exact"` or `"normal_approx"`; mirrors py-sezgi's
#'   `stats_wilcoxon()` dict keys exactly). `"exact"` is used when
#'   `n_effective <= 25` and there are no zero differences or tied `|d|`
#'   ranks; see `sezgi_stats::wilcoxon_signed_rank`'s doc comment for the
#'   full eligibility rule (the exact p-value formula is semver-pinned).
#' @export
`sz_stats_wilcoxon` <- function(`a`, `b`) {
  .Call(savvy_sz_stats_wilcoxon__impl, `a`, `b`)
}

#' Loads a TSPLIB `EUC_2D` instance, either a vendored instance name
#' (`"berlin52"`, `"eil51"`, `"st70"`) or raw TSPLIB file text (see
#' [`load_tsp`]).
#'
#' @param name_or_text A vendored instance name, or raw TSPLIB `.tsp` file
#'   text.
#' @returns A named list with `name` (character scalar), `n_cities` (double),
#'   `coords` (an `n_cities` x 2 numeric matrix, row `i` is city `i`'s
#'   `(x, y)` coordinate pair -- see this module's own doc, "Index-convention
#'   decision"), `known_optimum` (double, or `NULL` for an instance parsed
#'   from raw text rather than a vendored name).
#'
#' # Errors
#' A savvy error for any [`TspError`] (unknown vendored name that also fails
#' to parse as TSPLIB text, malformed TSPLIB text, unsupported
#' `EDGE_WEIGHT_TYPE`, ...).
#' @export
`sz_tsp_load` <- function(`name_or_text`) {
  .Call(savvy_sz_tsp_load__impl, `name_or_text`)
}

#' Closed-tour length of a 1-based `tour` (a permutation of `1:n_cities` --
#' see this module's own doc, "Index-convention decision") on the instance
#' named/parsed by `name_or_text` (see [`load_tsp`]), via
#' [`Tsp::evaluate_batch`]'s `nint`-rounded `EUC_2D` sum (`tsp.rs`'s module
#' doc).
#'
#' UNLIKE `Tsp::evaluate_batch` itself (which returns `f64::INFINITY` for a
#' malformed genotype, since genotype validity is normally the engine's
#' `SearchSpace::validate` job, not `Tsp`'s own) -- this binding validates
#' `tour` itself (exact length, every entry in `1..=n_cities`, no repeats)
#' and raises a precise error instead, since a `tour` coming directly from R
#' has no engine-side validation gate in front of it.
#'
#' @param name_or_text A vendored instance name, or raw TSPLIB `.tsp` file
#'   text (same as `sz_tsp_load`).
#' @param tour A numeric vector, a permutation of `1:n_cities` (1-based).
#' @returns A numeric scalar.
#'
#' # Errors
#' A savvy error for any [`TspError`] resolving `name_or_text`, or if `tour`
#' is not a permutation of `1:n_cities` (wrong length, an out-of-range
#' entry, or a repeated entry).
#' @export
`sz_tsp_tour_length` <- function(`name_or_text`, `tour`) {
  .Call(savvy_sz_tsp_tour_length__impl, `name_or_text`, `tour`)
}

### wrapper functions for EvalSession

`EvalSession_best` <- function(self) {
  function() {
    .Call(savvy_EvalSession_best__impl, `self`)
  }
}

`EvalSession_bounds` <- function(self) {
  function() {
    .Call(savvy_EvalSession_bounds__impl, `self`)
  }
}

`EvalSession_budget` <- function(self) {
  function() {
    .Call(savvy_EvalSession_budget__impl, `self`)
  }
}

`EvalSession_dim` <- function(self) {
  function() {
    .Call(savvy_EvalSession_dim__impl, `self`)
  }
}

`EvalSession_evals_used` <- function(self) {
  function() {
    .Call(savvy_EvalSession_evals_used__impl, `self`)
  }
}

`EvalSession_evaluate` <- function(self) {
  function(`x`) {
    .Call(savvy_EvalSession_evaluate__impl, `self`, `x`)
  }
}

`EvalSession_f_opt` <- function(self) {
  function() {
    .Call(savvy_EvalSession_f_opt__impl, `self`)
  }
}

`EvalSession_finish` <- function(self) {
  function() {
    invisible(.Call(savvy_EvalSession_finish__impl, `self`))
  }
}

`.savvy_wrap_EvalSession` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`best` <- `EvalSession_best`(ptr)
  e$`bounds` <- `EvalSession_bounds`(ptr)
  e$`budget` <- `EvalSession_budget`(ptr)
  e$`dim` <- `EvalSession_dim`(ptr)
  e$`evals_used` <- `EvalSession_evals_used`(ptr)
  e$`evaluate` <- `EvalSession_evaluate`(ptr)
  e$`f_opt` <- `EvalSession_f_opt`(ptr)
  e$`finish` <- `EvalSession_finish`(ptr)

  class(e) <- c("sezgi::EvalSession", "EvalSession", "savvy_sezgi__sealed")
  e
}


#' The ask/tell evaluation session -- see the module doc.
`EvalSession` <- new.env(parent = emptyenv())

### associated functions for EvalSession

`EvalSession`$`new` <- function(`fid`, `dim`, `instance`, `budget`, `algo_name`, `seed`, `log_dir` = NULL) {
  .savvy_wrap_EvalSession(.Call(savvy_EvalSession_new__impl, `fid`, `dim`, `instance`, `budget`, `algo_name`, `seed`, `log_dir`))
}

`EvalSession`$`new_cec2014` <- function(`fid`, `dim`, `budget`, `algo_name`, `seed`, `log_dir` = NULL) {
  .savvy_wrap_EvalSession(.Call(savvy_EvalSession_new_cec2014__impl, `fid`, `dim`, `budget`, `algo_name`, `seed`, `log_dir`))
}

`EvalSession`$`new_cec2017` <- function(`fid`, `dim`, `budget`, `algo_name`, `seed`, `log_dir` = NULL) {
  .savvy_wrap_EvalSession(.Call(savvy_EvalSession_new_cec2017__impl, `fid`, `dim`, `budget`, `algo_name`, `seed`, `log_dir`))
}

`EvalSession`$`new_cec2022` <- function(`fid`, `dim`, `budget`, `algo_name`, `seed`, `log_dir` = NULL) {
  .savvy_wrap_EvalSession(.Call(savvy_EvalSession_new_cec2022__impl, `fid`, `dim`, `budget`, `algo_name`, `seed`, `log_dir`))
}

`EvalSession`$`new_f0` <- function(`dim`, `f0_seed`, `budget`) {
  .savvy_wrap_EvalSession(.Call(savvy_EvalSession_new_f0__impl, `dim`, `f0_seed`, `budget`))
}


class(`EvalSession`) <- c("sezgi::EvalSession__bundle", "savvy_sezgi__sealed")

#' @export
`print.sezgi::EvalSession__bundle` <- function(x, ...) {
  cat('sezgi::EvalSession\n')
}

