# Hand-written wrapper (NOT generated by savvy-cli). `sz_ecdf_raw()` is the
# savvy-generated binding, defined in R/000-wrappers.R; this wrapper gives it
# an R-native default argument (`per_algo = TRUE`) -- savvy has no way to
# express a non-NULL default for a required argument in the generated
# signature -- same pattern as `sz_run_experiment()` / `sz_run_experiment_raw()`
# in R/experiment.R.

#' ECDF/anytime curve(s) over an on-disk IOH archive.
#'
#' Mirrors py-sezgi's `ecdf()`. See `crates/bench/src/anytime.rs` for the
#' full PINNED definitions (`default_targets`, the ECDF denominator
#' convention, `hit_time`).
#'
#' @param log_root Path to the IOH archive directory (as passed to
#'   `sz_run_experiment(..., log_dir = ...)`).
#' @param targets Optional numeric vector of precision targets; `NULL`
#'   (default) uses the COCO-convention 51-value default target set.
#' @param per_algo `TRUE` (default) returns a named list, one
#'   `list(evals=, proportion=)` entry per distinct algo in the archive,
#'   named by algo (first-appearance order); `FALSE` returns a single
#'   pooled `list(evals=, proportion=)` over every scenario.
#' @returns A named list (see `per_algo`).
#' @export
sz_ecdf <- function(log_root, targets = NULL, per_algo = TRUE) {
  sz_ecdf_raw(log_root, per_algo, targets)
}
