# Hand-written wrappers (NOT generated by savvy-cli). `sz_bias_structural_raw()` /
# `sz_bias_central_raw()` / `sz_bias_report_raw()` are the savvy-generated
# bindings, defined in R/000-wrappers.R; these wrappers give them R-native
# default arguments (savvy has no way to express a non-NULL default for a
# required argument in the generated signature) -- same raw/wrapper pattern
# as `sz_run_experiment()` / `sz_run_experiment_raw()` in R/experiment.R and
# `sz_stats_bayesian_signed_rank()` / `sz_stats_bayesian_signed_rank_raw()`
# in R/stats.R.
#
# Mirrors py-sezgi's `sezgi.bias.structural()` / `.central()` / `.report()`
# 1:1 by key name -- see py-sezgi/src/lib.rs's "Bias-scanning bindings"
# section doc for the full field-by-field provenance (crates/bias's own
# `structural`/`central`/`report` modules are the ultimate source).

#' Structural-bias scan: run an algorithm spec repeatedly on the f0
#' random-function null problem and test its final positions for departure
#' from uniformity (BIAS-toolbox method; Kononova et al. 2015 / Vermetten et
#' al. 2022). See `crates/bias/src/structural.rs` for the full method
#' provenance.
#'
#' @param spec_json Algorithm spec as JSON (e.g. from `sz_preset_random_search()`).
#' @param dim f0's domain dimensionality (>= 1).
#' @param budget Per-run evaluation budget (overrides the spec's own budget).
#' @param runs Number of independent runs. Default 30 -- the BIAS toolbox's
#'   own verified minimum/default (`sezgi_bias::structural::DEFAULT_RUNS`).
#' @param seed Master RNG seed, mixed into both f0's own RNG and the
#'   engine's `master_seed`.
#' @returns A named list with `per_dim_ks` (list of `list(d=, p_value=,
#'   n=)`, length `dim`), `per_dim_ad` (list of `list(a2=, p_value=, n=)`,
#'   same length/order), `holm_rejections_ks`, `holm_rejections_ad`,
#'   `verdict` (`"no_evidence"` or `"evidence"`), `detail` (`NULL` iff
#'   `verdict == "no_evidence"`, else a character scalar), `final_positions`
#'   (list of `runs` numeric vectors, each length `dim`) -- mirrors
#'   py-sezgi's `sezgi.bias.structural()` dict keys exactly.
#' @export
sz_bias_structural <- function(spec_json, dim, budget, runs = 30, seed = 0) {
  sz_bias_structural_raw(spec_json, dim, budget, runs, seed)
}

#' Central-bias scan: run an algorithm spec on paired centered/shifted BBOB
#' conditions and test whether its performance gap differs between them
#' (Kudela's center-bias-exploitation method). See
#' `crates/bias/src/central.rs` for the full method provenance.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim Problem dimension (BBOB requires `dim >= 2`).
#' @param budget Per-run evaluation budget (overrides the spec's own budget).
#' @param fids Optional numeric vector of BBOB function ids. `NULL`
#'   (default) uses the verified defaults `c(1, 4, 13)`. Every entry must be
#'   translation-invariant -- fids 5, 6, 20, 24 are rejected with an error
#'   (their `x_opt` participates directly in the objective formula, not
#'   just as a coordinate shift).
#' @param instances_shifted Optional numeric vector of BBOB instance
#'   numbers. `NULL` (default) uses the verified defaults `c(1, 2)`.
#' @param runs_per Independent runs per `(fid, instance)` pair. Default 20
#'   -- Kudela's own verified run count.
#' @param seed Master RNG seed, shared by both conditions (a paired design;
#'   see `crates/bias/src/central.rs`'s "Pairing rationale").
#' @returns A named list with `gap_centered`, `gap_shifted` (numeric
#'   vectors, same length/order -- index `i` in both is one matched pair),
#'   `wilcoxon` (named list: `w_statistic`, `z`, `p_value`, `n_effective`,
#'   `method`), `effect` (Cliff's delta, `gap_shifted` vs `gap_centered`),
#'   `verdict`, `detail` -- mirrors py-sezgi's `sezgi.bias.central()` dict
#'   keys exactly.
#' @export
sz_bias_central <- function(spec_json, dim, budget, fids = NULL, instances_shifted = NULL,
                             runs_per = 20, seed = 0) {
  sz_bias_central_raw(spec_json, dim, budget, runs_per, seed, fids, instances_shifted)
}

#' One-call bias report: runs both the structural and central bias scans on
#' one algorithm spec and assembles a single report with a ready-to-paste
#' LaTeX summary table. See `crates/bias/src/report.rs` for the full
#' assembly/LaTeX-rendering details.
#'
#' T6 (the Rajwar-Deep signature-bias test) is DEFERRED in the underlying
#' `sezgi-bias` crate itself -- the method could not be pinned from
#' accessible sources (no reachable source fully specifies its statistical
#' procedure). There is no `sz_bias_signature()`; the returned list's
#' `signature` element is mapped through properly (not hardcoded), so it is
#' `NULL` today only because the crate's own result is always `NULL` today --
#' see below -- and `latex_summary` renders an honest "not run" row for it
#' instead of a fabricated result.
#'
#' @param spec_json Algorithm spec as JSON.
#' @param dim Shared dimensionality for both scans (BBOB requires `dim >= 2`).
#' @param budget Shared per-run evaluation budget for both scans.
#' @param seed Shared master RNG seed for both scans.
#' @param structural_runs Optional; `NULL` (default) uses the structural
#'   scan's own verified default (30).
#' @param central_fids Optional numeric vector; `NULL` (default) uses
#'   `c(1, 4, 13)`.
#' @param central_instances Optional numeric vector; `NULL` (default) uses
#'   `c(1, 2)`.
#' @param central_runs_per Optional; `NULL` (default) uses 20.
#' @returns A named list with `structural` (same shape as
#'   `sz_bias_structural()`'s return), `central` (same shape as
#'   `sz_bias_central()`'s return), `signature` (`NULL` today, see above;
#'   when non-`NULL`, a two-element list `list(verdict = ..., detail =
#'   ...)`, same shape as `structural`'s/`central`'s own `verdict`/`detail`),
#'   `latex_summary` (character scalar, never contains the literal
#'   `"NaN"`), `plot_data` (named list: `final_positions`, `gap_centered`,
#'   `gap_shifted` -- the same raw vectors already inside `structural`/
#'   `central`) -- mirrors py-sezgi's `sezgi.bias.report()` dict keys
#'   exactly.
#' @export
sz_bias_report <- function(spec_json, dim, budget, seed = 0, structural_runs = NULL,
                            central_fids = NULL, central_instances = NULL,
                            central_runs_per = NULL) {
  sz_bias_report_raw(spec_json, dim, budget, seed, structural_runs, central_runs_per,
                      central_fids, central_instances)
}

#' Statistics-only structural-bias scan over externally-collected final
#' positions -- the bias bridge for algorithms authored OUTSIDE this
#' package's own spec/engine (M3-5 Task 6), e.g. a pure-R
#' \code{\link{sz_algorithm}} driven by \code{\link{sz_algo_solve}} over
#' \code{\link{sz_eval_session_f0}}, one run at a time. Runs the SAME KS/AD/
#' Holm battery as \code{\link{sz_bias_structural}} over caller-supplied
#' `final_positions` instead of driving an algorithm spec through the
#' engine itself -- see \code{crates/bias/src/structural.rs}'s
#' `scan_from_positions` for the full method provenance. Mirrors py-sezgi's
#' `sezgi.bias.structural_positions()` 1:1.
#'
#' @param final_positions A numeric matrix (rows = independent runs' final
#'   positions, columns = dimension) or a \code{list} of numeric vectors,
#'   one per run -- the same two shapes \code{EvalSession$evaluate()}
#'   itself accepts. Must have at least 5 rows/elements (the BIAS toolbox's
#'   own verified minimum run count), all the same length (dimension); a
#'   shorter/longer row (ragged input) is rejected.
#' @returns Same named-list shape as \code{\link{sz_bias_structural}}'s
#'   return: `per_dim_ks`, `per_dim_ad`, `holm_rejections_ks`,
#'   `holm_rejections_ad`, `verdict` (`"no_evidence"` or `"evidence"`),
#'   `detail` (`NULL` iff `verdict == "no_evidence"`), `final_positions`.
#' @export
sz_bias_structural_positions <- function(final_positions) {
  sz_bias_structural_positions_raw(final_positions)
}
