# Hand-written wrappers (NOT generated by savvy-cli). `sz_nsga2_raw()` /
# `sz_mo_pareto_front_raw()` / `sz_mo_evaluate_raw()` /
# `sz_mo_evaluate_constraints_raw()` are the savvy-generated bindings,
# defined in R/000-wrappers.R; these wrappers give them R-native default
# arguments and R-native argument order (savvy has no way to express a
# non-NULL default for a required argument in the generated signature, and
# every `Option`-typed raw parameter must trail every non-`Option` one) --
# same raw/wrapper pattern as `sz_bias_structural()` / `sz_bias_structural_raw()`
# in R/bias.R.
#
# `sz_mo_hypervolume_2d()` / `sz_mo_hypervolume()` / `sz_mo_igd()` /
# `sz_mo_read_moa()` have no non-NULL default arguments, so they are
# exported directly from `mo.rs` (no wrapper needed here) -- same pattern as
# `sz_stats_friedman()` / `sz_stats_cliffs_delta()`.
#
# Mirrors py-sezgi's `sezgi.mo` module (M3-2 Task 9, extended M3-7 Task 10)
# 1:1 by dict key name -- see `r-sezgi/src/rust/src/mo.rs`'s module doc for
# the full field-by-field provenance and container-idiom decisions
# (list-of-vectors for `individuals`/`objectives`/`sz_mo_pareto_front`'s
# return, matrix for `sz_mo_hypervolume_2d`/`sz_mo_hypervolume`/
# `sz_mo_igd`'s `front`/`reference_front` inputs, 1-based `front0`,
# present-only-when-constrained `violations`, logical vector for a binary
# `sz_mo_read_moa` genotype record).

#' NSGA-II (Deb, Pratap, Agarwal & Meyarivan 2002) run on a ZDT/DTLZ/WFG
#' multi-objective test problem. See `crates/components/src/nsga2.rs` for
#' the full algorithm provenance.
#'
#' @param problem One of `"zdt1"`, `"zdt2"`, `"zdt3"`, `"zdt4"`, `"zdt5"`
#'   (binary-coded, fixed 80-bit layout), `"zdt6"`, `"dtlz1"`..`"dtlz9"`
#'   (`"dtlz8"`/`"dtlz9"` are constrained), or `"wfg1"`..`"wfg9"`.
#' @param dim Decision-space dimensionality. REQUIRED (may be `NULL`, but
#'   the argument itself must be supplied) for zdt1-4/6 and dtlz1-9;
#'   REJECTED (must be `NULL`) for zdt5 (fixed 80-bit layout) and wfg1-9
#'   (dimension is derived from `k`/`l`).
#' @param m Number of objectives. REQUIRED for dtlz/wfg problems; must be
#'   `NULL` (default, and the only valid value) for zdt problems, which are
#'   always 2-objective by construction -- passing `m` for a zdt problem is
#'   an error, not a silently-ignored argument.
#' @param pop_size Population size. Must be `>= 4` and a multiple of 4
#'   (KanGAL's double-permutation tournament pairing requires it -- NOT
#'   merely "even, >= 4"; `pop_size = 6` is rejected the same as
#'   `pop_size = 7`).
#' @param budget Total evaluation budget (init + every generation).
#' @param seed Master RNG seed. Default `0`.
#' @param eta_c SBX distribution index. Default `20.0` (Deb et al. 2002,
#'   Sec. IV.A's own experimental setting).
#' @param eta_m Polynomial-mutation distribution index. Default `20.0`.
#' @param p_c SBX crossover probability. Default `0.9`.
#' @param p_m Per-variable mutation probability. `NULL` (default) resolves
#'   on the Rust side to `1 / n_variables` (the paper's own default), never
#'   re-derived here.
#' @param p_c_bin Binary-genotype crossover probability (M3-7). Default
#'   `0.9`, mirroring `p_c`'s own default (the paper gives no verified
#'   binary-specific default) -- only consulted when `problem` builds an
#'   all-Binary space (zdt5 today).
#' @param p_m_bin Optional per-bit binary mutation probability. `NULL`
#'   (default) resolves on the Rust side to `1 / l` (`l` = the space's total
#'   bit count, the paper's own stated binary-coded default) -- only
#'   consulted for an all-Binary space.
#' @param p_c_cat Categorical-genotype crossover probability (post-M3-8
#'   deferral cleanup). Default `0.9`, mirroring `p_c_bin`'s own default (no
#'   paper/reference precedent exists for Categorical) -- only consulted
#'   when `problem` builds a `Mixed` space containing a `Block::Categorical`
#'   block. No `problem` string accepted here builds one today (zdt1-6,
#'   dtlz1-9, wfg1-9 are all-Float or, for zdt5, all-Binary), so this is
#'   currently validated but inert against every reachable problem --
#'   exposed anyway for symmetry with `p_c_bin`/`p_m_bin`.
#' @param p_m_cat Optional per-gene Categorical mutation probability
#'   (post-M3-8 deferral cleanup). `NULL` (default) resolves on the Rust
#'   side to `1 / n_cat` (`n_cat` = the space's total flattened
#'   `Block::Categorical` dimension), mirroring `p_m`/`p_m_bin`'s own
#'   `NULL`-resolves-to-a-formula design -- only consulted for a `Mixed`
#'   space containing a Categorical block (currently unreachable through
#'   this catalog -- see `p_c_cat` above).
#' @param k Optional WFG position-related-parameter count. `NULL` (default)
#'   resolves to the toolkit's own recommended value (`k = 4` for `m = 2`,
#'   `k = 2*(m-1)` for `m >= 3`); wfg-only, an error for any other problem
#'   family.
#' @param l Optional WFG distance-related-parameter count. `NULL` (default)
#'   resolves to `20`; wfg-only.
#' @param log_dir Optional sezgi-moa v1 log directory (M3-7 archive-first
#'   run logging). When given, `label` is required and the run additionally
#'   streams every feasible archive insertion to
#'   `<log_dir>/<label>-s<seed>.moa` -- see `sz_mo_read_moa()`. Omitting
#'   `log_dir` runs exactly as before (byte-identical to the unlogged path).
#' @param label Optional sezgi-moa run label; REQUIRED iff `log_dir` is
#'   given, otherwise ignored.
#' @returns A named list with `individuals` (list of numeric vectors, one
#'   per final-population member, each length `dim` -- flattened across
#'   every block; a `Block::Binary` block's bits are flattened to
#'   `0.0`/`1.0`, e.g. zdt5's own path), `objectives` (list of numeric
#'   vectors, parallel to `individuals`, each length equal to the problem's
#'   objective count), `front0` (numeric vector of 1-based positions, R
#'   convention, into `individuals`/`objectives` for the final population's
#'   non-dominated set -- NOTE: py-sezgi's `front0` is 0-based; this binding
#'   converts), `evals_used` (double), and (present ONLY for a constrained
#'   problem -- dtlz8/dtlz9 today) `violations` (numeric vector, `<= 0.0`,
#'   `0.0` = feasible, parallel to `individuals`/`objectives`) -- mirrors
#'   py-sezgi's `sezgi.mo.nsga2()` dict keys exactly.
#' @examples
#' r <- sz_nsga2("zdt1", dim = 5, pop_size = 8, budget = 40, seed = 1)
#' length(r$front0)
#' @export
sz_nsga2 <- function(problem, dim, m = NULL, pop_size, budget, seed = 0,
                      eta_c = 20.0, eta_m = 20.0, p_c = 0.9, p_m = NULL,
                      p_c_bin = 0.9, p_m_bin = NULL, p_c_cat = 0.9, p_m_cat = NULL,
                      k = NULL, l = NULL, log_dir = NULL, label = NULL) {
  sz_nsga2_raw(problem, pop_size, budget, seed, eta_c, eta_m, p_c, p_c_bin, p_c_cat,
               dim, m, p_m, p_m_bin, p_m_cat, k, l, log_dir, label)
}

#' A deterministic `n`-point sample of the analytic Pareto front in
#' OBJECTIVE space, if known. See `MoProblem::pareto_front` in
#' `crates/core/src/mo.rs`.
#'
#' @param problem Same `problem`/`dim`/`m`/`k`/`l` mapping as `sz_nsga2()`.
#' @param dim Decision-space dimensionality -- same rule as `sz_nsga2()`.
#' @param n Number of front points to sample.
#' @param m Number of objectives -- same rule as `sz_nsga2()`.
#' @param k Optional WFG position-related-parameter count; wfg-only.
#' @param l Optional WFG distance-related-parameter count; wfg-only.
#' @returns A `list` of `n` numeric vectors (mirrors `sz_nsga2()`'s
#'   `objectives`/`individuals` container convention -- a list, not a
#'   matrix), or `NULL` when the problem has no known analytic front sample
#'   at this `m` (verified cases: DTLZ5/DTLZ6 with `m > 3`; WFG1/WFG2
#'   unconditionally) -- mirrors py-sezgi's `sezgi.mo.pareto_front()` return
#'   exactly.
#' @export
sz_mo_pareto_front <- function(problem, dim, n, m = NULL, k = NULL, l = NULL) {
  sz_mo_pareto_front_raw(problem, n, dim, m, k, l)
}

#' Direct, one-shot objective evaluation of a decision vector `x` against
#' any `sz_mo_*` problem string, bypassing `sz_nsga2()`'s population/budget
#' machinery entirely. Added (M3-7) so fixture-value tests can pin an exact
#' `x` (`sz_nsga2()`'s randomly-initialized population cannot), mirroring
#' the existing `sz_cec2022_evaluate()`/`sz_cec2014_evaluate()`/
#' `sz_cec2017_evaluate()` one-shot-evaluation convention.
#'
#' @param problem Same mapping as `sz_nsga2()`.
#' @param dim Decision-space dimensionality -- same rule as `sz_nsga2()`.
#' @param x A numeric vector, the decision vector to evaluate. For zdt5 (the
#'   only all-Binary problem reachable here), each entry is read as a bit
#'   (`!= 0.0` -> `TRUE`) -- the same `0.0`/`1.0` convention `sz_nsga2()`'s
#'   own `individuals` uses.
#' @param m Number of objectives -- same rule as `sz_nsga2()`.
#' @param k Optional WFG position-related-parameter count; wfg-only.
#' @param l Optional WFG distance-related-parameter count; wfg-only.
#' @returns A numeric vector, length equal to the problem's own objective
#'   count.
#' @export
sz_mo_evaluate <- function(problem, dim, x, m = NULL, k = NULL, l = NULL) {
  sz_mo_evaluate_raw(problem, x, dim, m, k, l)
}

#' The matching one-shot constraint-row evaluation for `sz_mo_evaluate()`,
#' same calling convention.
#'
#' @param problem Same mapping as `sz_nsga2()`.
#' @param dim Decision-space dimensionality -- same rule as `sz_nsga2()`.
#' @param x A numeric vector, the decision vector to evaluate.
#' @param m Number of objectives -- same rule as `sz_nsga2()`.
#' @param k Optional WFG position-related-parameter count; wfg-only.
#' @param l Optional WFG distance-related-parameter count; wfg-only.
#' @returns A numeric vector (`g_1..g_ncon`, `g_j >= 0` meaning SATISFIED),
#'   or `NULL` for an unconstrained problem (every zdt/wfg problem, and
#'   dtlz1-7).
#' @export
sz_mo_evaluate_constraints <- function(problem, dim, x, m = NULL, k = NULL, l = NULL) {
  sz_mo_evaluate_constraints_raw(problem, x, dim, m, k, l)
}
