# Hand-written wrappers (NOT generated by savvy-cli). `sz_nsga2_raw()` /
# `sz_mo_pareto_front_raw()` are the savvy-generated bindings, defined in
# R/000-wrappers.R; these wrappers give them R-native default arguments
# (savvy has no way to express a non-NULL default for a required argument in
# the generated signature) -- same raw/wrapper pattern as
# `sz_bias_structural()` / `sz_bias_structural_raw()` in R/bias.R.
#
# `sz_mo_hypervolume_2d()` / `sz_mo_igd()` have no default arguments, so
# they are exported directly from `mo.rs` (no wrapper needed here) -- same
# pattern as `sz_stats_friedman()` / `sz_stats_cliffs_delta()`.
#
# Mirrors py-sezgi's `sezgi.mo.nsga2()` / `.pareto_front()` 1:1 by dict key
# name -- see `r-sezgi/src/rust/src/mo.rs`'s module doc for the full
# field-by-field provenance and container-idiom decisions (crates/components's
# own `nsga2` module and crates/problems's `zdt`/`dtlz` modules are the
# ultimate source).

#' NSGA-II (Deb, Pratap, Agarwal & Meyarivan 2002) run on a ZDT/DTLZ
#' multi-objective test problem. See `crates/components/src/nsga2.rs` for
#' the full algorithm provenance.
#'
#' @param problem One of `"zdt1"`, `"zdt2"`, `"zdt3"`, `"zdt4"`, `"zdt6"`
#'   (ZDT5 is a binary-coded problem, out of scope) or `"dtlz1"`..`"dtlz7"`.
#' @param dim Decision-space dimensionality (>= 2 for zdt; >= `m` for dtlz).
#' @param m Number of objectives. REQUIRED for dtlz problems; must be `NULL`
#'   (default, and the only valid value) for zdt problems, which are always
#'   2-objective by construction -- passing `m` for a zdt problem is an
#'   error, not a silently-ignored argument.
#' @param pop_size Population size. Must be `>= 4` and a multiple of 4
#'   (KanGAL's double-permutation tournament pairing requires it -- NOT
#'   merely "even, >= 4"; `pop_size = 6` is rejected the same as
#'   `pop_size = 7`).
#' @param budget Total evaluation budget (init + every generation).
#' @param seed Master RNG seed. Default `0`.
#' @param eta_c SBX distribution index. Default `20.0` (Deb et al. 2002,
#'   Sec. IV.A's own experimental setting).
#' @param eta_m Polynomial-mutation distribution index. Default `20.0`.
#' @param p_c SBX crossover probability. Default `0.9`.
#' @param p_m Per-variable mutation probability. `NULL` (default) resolves
#'   on the Rust side to `1 / n_variables` (the paper's own default), never
#'   re-derived here.
#' @returns A named list with `individuals` (list of numeric vectors, one
#'   per final-population member, each length `dim`, flattened across every
#'   Float block -- e.g. ZDT4 has two blocks concatenated into one flat
#'   row), `objectives` (list of numeric vectors, parallel to `individuals`,
#'   each length equal to the problem's objective count), `front0` (numeric
#'   vector of 1-based positions, R convention, into `individuals`/
#'   `objectives` for the final population's non-dominated set -- NOTE:
#'   py-sezgi's `front0` is 0-based; this binding converts), `evals_used`
#'   (double) -- mirrors py-sezgi's `sezgi.mo.nsga2()` dict keys exactly.
#' @export
sz_nsga2 <- function(problem, dim, m = NULL, pop_size, budget, seed = 0,
                      eta_c = 20.0, eta_m = 20.0, p_c = 0.9, p_m = NULL) {
  sz_nsga2_raw(problem, dim, pop_size, budget, seed, eta_c, eta_m, p_c, m, p_m)
}

#' A deterministic `n`-point sample of the analytic Pareto front in
#' OBJECTIVE space, if known. See `MoProblem::pareto_front` in
#' `crates/core/src/mo.rs`.
#'
#' @param problem Same `problem`/`m` mapping as `sz_nsga2()`.
#' @param dim Decision-space dimensionality.
#' @param m Number of objectives. REQUIRED for dtlz, must be `NULL`
#'   (default) for zdt -- same rule as `sz_nsga2()`.
#' @param n Number of front points to sample.
#' @returns A `list` of `n` numeric vectors (mirrors `sz_nsga2()`'s
#'   `objectives`/`individuals` container convention -- a list, not a
#'   matrix), or `NULL` when the problem has no known analytic front sample
#'   at this `m` (verified case: DTLZ5/DTLZ6 with `m > 3`) -- mirrors
#'   py-sezgi's `sezgi.mo.pareto_front()` return exactly.
#' @export
sz_mo_pareto_front <- function(problem, dim, m = NULL, n) {
  sz_mo_pareto_front_raw(problem, dim, n, m)
}
