# Hand-written wrapper (NOT generated by savvy-cli). `sz_preset_es_mu_plus_lambda_raw()`
# is the savvy-generated binding, defined in R/000-wrappers.R; this wrapper
# gives it R-native default arguments (savvy has no way to express a
# non-NULL/string default in the generated signature) -- same pattern as
# `sz_run_experiment()` / `sz_run_experiment_raw()` in R/experiment.R and
# `sz_stats_bayesian_signed_rank()` / `sz_stats_bayesian_signed_rank_raw()`
# in R/stats.R.

#' Builds a (mu/mu_w,lambda)-ES algorithm spec (mutation step drawn from
#' `dist`) as JSON, ready to pass to `sz_solve_bbob()`.
#'
#' Mirrors py-sezgi's `sezgi.presets.es_mu_plus_lambda()`.
#'
#' @param pop_size Population size.
#' @param budget Evaluation budget.
#' @param dist Mutation distribution: one of `"uniform"`, `"gaussian"`,
#'   `"cauchy"`, `"levy"`, `"student_t"`, `"laplace"`. Default `"gaussian"`.
#'   An unrecognized value raises an error naming it and the recognized set.
#' @param mean Gaussian mean (used only when `dist = "gaussian"`). Default 0.
#' @param sigma Gaussian std-dev (used only when `dist = "gaussian"`).
#'   Default 0.5.
#' @param loc Cauchy/Laplace location (used only when `dist` is `"cauchy"`
#'   or `"laplace"`). Default 0.
#' @param scale Cauchy/Laplace scale (used only when `dist` is `"cauchy"`
#'   or `"laplace"`). Default 1.
#' @param alpha Levy stability parameter (used only when `dist = "levy"`).
#'   Default 1.5.
#' @param nu Student-t degrees of freedom (used only when `dist =
#'   "student_t"`). Default 3.
#' @returns A character scalar with the algorithm spec as JSON.
#' @export
sz_preset_es_mu_plus_lambda <- function(pop_size, budget, dist = "gaussian",
                                         mean = 0, sigma = 0.5, loc = 0, scale = 1,
                                         alpha = 1.5, nu = 3) {
  sz_preset_es_mu_plus_lambda_raw(pop_size, budget, dist, mean, sigma, loc, scale, alpha, nu)
}
