# Hand-written wrapper (NOT generated by savvy-cli). `EvalSession$new()` is
# the savvy-generated constructor for the stateful `EvalSession` R object
# (see `src/rust/src/session.rs`), defined in `R/000-wrappers.R`; this
# wrapper gives it R-native default arguments (`algo_name = "custom"`,
# `seed = 0`) -- savvy has no way to express a non-NULL default for a
# required argument in the generated signature -- same raw/wrapper pattern
# as `sz_run_experiment()` / `sz_run_experiment_raw()` in `R/experiment.R`.

#' Start an ask/tell evaluation session over a BBOB problem.
#'
#' The session is the sole keeper of evaluation, tamper-proof counting,
#' best-tracking and (optionally) IOH logging, driven entirely by candidate
#' points an EXTERNAL algorithm supplies -- the spec's engine-inside-out
#' promise. Mirrors py-sezgi's `sezgi.EvalSession`.
#'
#' The returned object is a reference (external-pointer) handle, not a
#' value: assigning it to another variable (e.g. \code{s2 <- s}) does NOT
#' copy the session -- both names alias the SAME mutable session, so a
#' \code{$evaluate()} through either one advances the same counter and
#' best. This is standard R external-pointer/environment behavior (the
#' object literally IS an \code{environment}), not something specific to
#' this package.
#'
#' The returned object exposes:
#' \itemize{
#'   \item \code{$evaluate(x)} -- batch-evaluates `x` (a numeric matrix with
#'     rows = points and `dim` columns, or a `list` of `dim`-length numeric
#'     vectors) and returns a numeric vector of `f` values, one per point.
#'     All-or-nothing: on any error (dimension mismatch, a non-finite
#'     coordinate, or a batch that would cross the remaining budget) nothing
#'     is counted.
#'   \item \code{$evals_used()} -- number of evaluations counted so far.
#'   \item \code{$budget()} -- the session's total evaluation budget.
#'   \item \code{$best()} -- \code{list(x = <numeric vector>, f = <numeric
#'     scalar>)} for the best evaluation seen so far, or \code{NULL} if
#'     nothing has been evaluated yet.
#'   \item \code{$f_opt()} -- the problem's known optimum value, or
#'     \code{NULL} if it has none (e.g. an f0 session -- see
#'     \code{\link{sz_eval_session_f0}}).
#'   \item \code{$dim()} -- the search space's dimensionality.
#'   \item \code{$bounds()} -- a length-2 numeric vector \code{c(lo, hi)},
#'     the uniform bounds of this session's continuous space (errors for a
#'     non-uniform/non-float space; unreachable through any constructor
#'     this package exposes today).
#'   \item \code{$finish()} -- flushes the IOH log (if enabled) and marks
#'     the session finished; every method call afterward, including a
#'     second \code{$finish()}, raises an error containing
#'     \code{"session finished"}.
#' }
#'
#' \code{$dim()}, \code{$bounds()}, and every method above except
#' \code{$f_opt()} behave identically regardless of which constructor built
#' the session (\code{sz_eval_session()}, \code{\link{sz_eval_session_cec2022}},
#' or \code{\link{sz_eval_session_f0}}).
#'
#' @param fid BBOB function id (>= 1).
#' @param dim Problem dimension (>= 1).
#' @param instance BBOB instance id (>= 1).
#' @param budget Evaluation budget (non-negative whole number). A fractional
#'   value is REJECTED (M2d-3: `f64_to_u64` now errors with "expected a
#'   whole number" instead of truncating toward zero), matching py-sezgi's
#'   `budget: u64` parameter, whose type makes pyo3 reject a fractional
#'   Python value outright at the FFI boundary.
#' @param log_dir Optional directory: when given, IOH-profiler logging is
#'   wired up in the constructor, before any evaluation is possible
#'   (constructor-only, like `sezgi.EvalSession`). Default `NULL`
#'   (no logging).
#' @param algo_name Algorithm label recorded in the IOH archive (only
#'   meaningful when `log_dir` is given). Default `"custom"`.
#' @param seed Caller-declared reproducibility label recorded in the IOH
#'   archive meta only -- the session itself never draws random numbers, so
#'   this is purely documentation of the CALLER's RNG seed. Default `0`.
#' @returns An `EvalSession` object (see above).
#' @export
sz_eval_session <- function(fid, dim, instance, budget, log_dir = NULL,
                             algo_name = "custom", seed = 0) {
  # The savvy-generated constructor's `fid`/`dim`/`instance` are `i32` and
  # (unlike its `f64` args) reject a plain R double outright ("must be
  # integer, not double") -- so this wrapper coerces them, giving
  # `sz_eval_session()` the same "just pass a number" ergonomics as
  # py-sezgi's `sezgi.EvalSession(fid=1, dim=3, ...)`.
  EvalSession$new(as.integer(fid), as.integer(dim), as.integer(instance),
                   budget, algo_name, seed, log_dir)
}

#' Start an ask/tell evaluation session over a CEC 2022 problem.
#'
#' The generic-session counterpart to \code{\link{sz_eval_session}} (which
#' is BBOB-only): builds a session over \code{sz_cec2022_evaluate}'s same
#' \code{Cec2022} problem, with IOH logging allowed (unlike
#' \code{\link{sz_eval_session_f0}}, whose problem has no known optimum for
#' a log archive to record). Session metadata (\code{suite =
#' "sezgi-cec2022"}, \code{name = "cec2022-f<fid>"}, \code{instance = 1},
#' \code{f_opt} = the function's known optimum) matches py-sezgi's
#' \code{EvalSession.for_problem} exactly for a CEC 2022 problem handle, so
#' an IOH record produced by an R session and one produced by an equivalent
#' Python session reconstruct to the identical \code{(suite, fid, name,
#' instance)} key and \code{f_opt}.
#'
#' See \code{\link{sz_eval_session}} for the full list of methods the
#' returned object exposes (identical here, including \code{$dim()} /
#' \code{$bounds()}).
#'
#' @param fid CEC 2022 function id (\code{1..=12}).
#' @param dim Problem dimension, one of \code{2}, \code{10}, \code{20}
#'   (\code{dim = 2} is additionally rejected for a hybrid function,
#'   \code{fid} 6-8).
#' @param budget Evaluation budget (non-negative whole number).
#' @param log_dir Optional directory: when given, IOH-profiler logging is
#'   wired up in the constructor, before any evaluation is possible.
#'   Default \code{NULL} (no logging).
#' @param algo_name Algorithm label recorded in the IOH archive (only
#'   meaningful when \code{log_dir} is given). Default \code{"custom"}.
#' @param seed Caller-declared reproducibility label recorded in the IOH
#'   archive meta only. Default \code{0}.
#' @returns An `EvalSession` object (see \code{\link{sz_eval_session}}).
#' @export
sz_eval_session_cec2022 <- function(fid, dim, budget, log_dir = NULL,
                                     algo_name = "custom", seed = 0) {
  # `EvalSession$new_cec2022()`'s `fid`/`dim` are `i32` -- same integer
  # coercion `sz_eval_session()` applies above.
  EvalSession$new_cec2022(as.integer(fid), as.integer(dim), budget,
                           algo_name, seed, log_dir)
}

#' Start an ask/tell evaluation session over the f0 BIAS-toolbox null
#' problem.
#'
#' f0 (\code{sezgi_bias::F0Random} on the Rust side) has no landscape at
#' all: every evaluation is an independent U(0,1) draw over the domain
#' \verb{[0,1]^dim}, uncorrelated with the point being queried. It exists
#' purely as a probe for an algorithm's OWN structural bias -- see
#' \code{\link{sz_bias_structural}}.
#'
#' Deliberately has NO \code{log_dir}/\code{algo_name}/\code{seed} (log)
#' arguments: f0 has no known optimum, and IOH logging requires one (see
#' \code{\link{sz_eval_session}}'s \code{log_dir} for the BBOB/CEC-2022
#' case). \code{$f_opt()} on the returned session always returns
#' \code{NULL}.
#'
#' See \code{\link{sz_eval_session}} for the full list of methods the
#' returned object exposes (identical here, including \code{$dim()} /
#' \code{$bounds()}, which returns \code{c(0, 1)}).
#'
#' @param dim f0's domain dimensionality (>= 1); the space is
#'   \verb{[0,1]^dim}.
#' @param f0_seed Seed for f0's own RNG stream -- distinct from any engine
#'   RNG seed.
#' @param budget Evaluation budget (non-negative whole number).
#' @returns An `EvalSession` object (see \code{\link{sz_eval_session}}).
#' @export
sz_eval_session_f0 <- function(dim, f0_seed, budget) {
  EvalSession$new_f0(as.integer(dim), f0_seed, budget)
}
