# Hand-written wrapper (NOT generated by savvy-cli). `EvalSession$new()` is
# the savvy-generated constructor for the stateful `EvalSession` R object
# (see `src/rust/src/session.rs`), defined in `R/000-wrappers.R`; this
# wrapper gives it R-native default arguments (`algo_name = "custom"`,
# `seed = 0`) -- savvy has no way to express a non-NULL default for a
# required argument in the generated signature -- same raw/wrapper pattern
# as `sz_run_experiment()` / `sz_run_experiment_raw()` in `R/experiment.R`.

#' Start an ask/tell evaluation session over a BBOB problem.
#'
#' The session is the sole keeper of evaluation, tamper-proof counting,
#' best-tracking and (optionally) IOH logging, driven entirely by candidate
#' points an EXTERNAL algorithm supplies -- the spec's engine-inside-out
#' promise. Mirrors py-sezgi's `sezgi.EvalSession`.
#'
#' The returned object is a reference (external-pointer) handle, not a
#' value: assigning it to another variable (e.g. \code{s2 <- s}) does NOT
#' copy the session -- both names alias the SAME mutable session, so a
#' \code{$evaluate()} through either one advances the same counter and
#' best. This is standard R external-pointer/environment behavior (the
#' object literally IS an \code{environment}), not something specific to
#' this package.
#'
#' The returned object exposes:
#' \itemize{
#'   \item \code{$evaluate(x)} -- batch-evaluates `x` (a numeric matrix with
#'     rows = points and `dim` columns, or a `list` of `dim`-length numeric
#'     vectors) and returns a numeric vector of `f` values, one per point.
#'     All-or-nothing: on any error (dimension mismatch, a non-finite
#'     coordinate, or a batch that would cross the remaining budget) nothing
#'     is counted.
#'   \item \code{$evals_used()} -- number of evaluations counted so far.
#'   \item \code{$budget()} -- the session's total evaluation budget.
#'   \item \code{$best()} -- \code{list(x = <numeric vector>, f = <numeric
#'     scalar>)} for the best evaluation seen so far, or \code{NULL} if
#'     nothing has been evaluated yet.
#'   \item \code{$f_opt()} -- the problem's known optimum value.
#'   \item \code{$finish()} -- flushes the IOH log (if enabled) and marks
#'     the session finished; every method call afterward, including a
#'     second \code{$finish()}, raises an error containing
#'     \code{"session finished"}.
#' }
#'
#' @param fid BBOB function id (>= 1).
#' @param dim Problem dimension (>= 1).
#' @param instance BBOB instance id (>= 1).
#' @param budget Evaluation budget (non-negative). Truncated toward zero if
#'   fractional (`as.integer`-style, via Rust's `f64 as u64` cast) rather
#'   than rejected -- an asymmetry with py-sezgi, whose `budget: u64`
#'   parameter type makes pyo3 reject a fractional Python value outright at
#'   the FFI boundary before this package's own cast ever runs. Not changed
#'   here; `f64_to_u64`'s strictness is owned by a later task.
#' @param log_dir Optional directory: when given, IOH-profiler logging is
#'   wired up in the constructor, before any evaluation is possible
#'   (constructor-only, like `sezgi.EvalSession`). Default `NULL`
#'   (no logging).
#' @param algo_name Algorithm label recorded in the IOH archive (only
#'   meaningful when `log_dir` is given). Default `"custom"`.
#' @param seed Caller-declared reproducibility label recorded in the IOH
#'   archive meta only -- the session itself never draws random numbers, so
#'   this is purely documentation of the CALLER's RNG seed. Default `0`.
#' @returns An `EvalSession` object (see above).
#' @export
sz_eval_session <- function(fid, dim, instance, budget, log_dir = NULL,
                             algo_name = "custom", seed = 0) {
  # The savvy-generated constructor's `fid`/`dim`/`instance` are `i32` and
  # (unlike its `f64` args) reject a plain R double outright ("must be
  # integer, not double") -- so this wrapper coerces them, giving
  # `sz_eval_session()` the same "just pass a number" ergonomics as
  # py-sezgi's `sezgi.EvalSession(fid=1, dim=3, ...)`.
  EvalSession$new(as.integer(fid), as.integer(dim), as.integer(instance),
                   budget, algo_name, seed, log_dir)
}
