# Hand-written wrappers (NOT generated by savvy-cli). `sz_stats_bayesian_signed_rank_raw()`
# and `sz_stats_paper_package_raw()` are the savvy-generated bindings, defined
# in R/000-wrappers.R; these wrappers give them R-native default arguments
# (savvy has no way to express a non-NULL default for a required argument in
# the generated signature) -- same pattern as `sz_run_experiment()` /
# `sz_run_experiment_raw()` in R/experiment.R.

#' Bayesian signed-rank test with a region of practical equivalence (ROPE).
#'
#' Mirrors py-sezgi's `stats_bayesian_signed_rank()`. Dirichlet-weighted
#' Monte Carlo scheme (Benavoli et al. 2017 simplification); see
#' `crates/stats/src/bayesian.rs` for the full algorithm and determinism
#' guarantees. The same `(a, b, rope, samples, seed)` always produces a
#' bit-identical result -- R calls the exact same seeded Rust core as Python
#' and Rust.
#'
#' @param a Numeric vector.
#' @param b Numeric vector, same length as `a`.
#' @param rope Region of practical equivalence half-width (>= 0). Default 0.
#' @param samples Number of Monte Carlo samples. Default 20000.
#' @param seed Master RNG seed. Default 1.
#' @returns A named list with `p_left`, `p_rope`, `p_right`.
#' @export
sz_stats_bayesian_signed_rank <- function(a, b, rope = 0, samples = 20000, seed = 1) {
  sz_stats_bayesian_signed_rank_raw(a, b, rope, samples, seed)
}

#' Comprehensive statistical analysis package for algorithm comparison.
#'
#' Mirrors py-sezgi's `stats_paper_package()`: Friedman test, Nemenyi
#' critical difference, all-pairs Wilcoxon signed-rank with Holm adjustment,
#' Cliff's delta, Bayesian signed-rank, Plackett-Luce ranking, and LaTeX
#' summary/pairwise-comparison tables. See `crates/stats/src/report.rs`.
#'
#' @param algo_names Character vector of algorithm names.
#' @param problem_names Character vector of problem names.
#' @param m A numeric matrix, rows = problems (`length(problem_names)`),
#'   columns = algorithms (`length(algo_names)`), lower is better.
#' @param rope Region of practical equivalence half-width (>= 0) for the
#'   Bayesian signed-rank test. Default 0.
#' @param samples Number of Monte Carlo samples per pair for the Bayesian
#'   signed-rank test. Default 20000.
#' @param seed Master RNG seed; per-pair seeds are `seed + pair_index`
#'   (wrapping). Default 1.
#' @returns A named list with `friedman`, `nemenyi_cd`,
#'   `pairwise_wilcoxon_holm`, `cliffs`, `bayes`, `plackett_luce`,
#'   `latex_summary`, `latex_tests` -- see `sz_stats_paper_package_raw()`
#'   for the full field-by-field shape.
#' @export
sz_stats_paper_package <- function(algo_names, problem_names, m, rope = 0, samples = 20000, seed = 1) {
  sz_stats_paper_package_raw(algo_names, problem_names, m, rope, samples, seed)
}

#' Bayesian Plackett-Luce posterior via Gibbs sampling.
#'
#' Mirrors py-sezgi's `stats.bayesian_plackett_luce()`. Caron & Doucet
#' (2012) latent exponential-race Gibbs augmentation under independent
#' `Gamma(1, 1)` priors; see `crates/stats/src/bayesian.rs` for the full
#' PINNED sampler and determinism guarantees. The same `(rankings, samples,
#' burn_in, seed)` always produces a bit-identical result -- R calls the
#' exact same seeded Rust core as Python and Rust.
#'
#' @param rankings A `list` of integer (or integer-valued numeric) vectors,
#'   each a full ranking of the same `k` items as **1-based item ids**
#'   (same convention as `sz_stats_plackett_luce()`; converted to 0-based
#'   indices via the SAME converter). Best (rank 1) first.
#' @param samples Number of post-burn-in Gibbs iterations to record.
#'   Default 2000.
#' @param burn_in Number of initial Gibbs iterations to discard. Default
#'   500.
#' @param seed Master RNG seed. Default 1.
#' @returns A named list with `mean_worths`, `ci_low`, `ci_high`, `p_best`,
#'   `samples`.
#' @export
sz_bayesian_plackett_luce <- function(rankings, samples = 2000, burn_in = 500, seed = 1) {
  sz_bayesian_plackett_luce_raw(rankings, samples, burn_in, seed)
}
