#!/usr/bin/env Rscript
# tools/cran_authors.R PKG_DIR
#
# Generates inst/AUTHORS and LICENSE.note inside an r-sezgi package tree,
# crediting every Rust crate the compiled extension links against. CRAN's
# "Using Rust" policy requires authorship/copyright of all Rust code
# (including dependencies) to be traceable from DESCRIPTION; DESCRIPTION
# carries a `ctb` entry pointing here ("see inst/AUTHORS file for details").
#
# Source of crate metadata (name, version, authors, license), tried in
# order, first match wins:
#   1. PKG_DIR/src/rust/vendor/*/Cargo.toml       -- an already-extracted
#      `cargo vendor` tree, if one happens to be present.
#   2. PKG_DIR/src/rust/vendor.tar.xz              -- extracted to a
#      temporary directory and read from there. This is the path actually
#      used by tools/make-cran-tree.sh, which removes src/rust/vendor/
#      right after tarring it and calls this script afterwards.
#   3. `cargo metadata` run against PKG_DIR/src/rust/Cargo.toml            --
#      used when neither of the above exists, i.e. the --no-vendor release
#      mode (r-universe: the build has network access and vendoring only
#      adds a redundant local copy of what cargo will fetch anyway).
#      Requires the jsonlite package and a `cargo` on PATH.
#
# In all three cases, only registry dependencies are credited here (path
# dependencies -- the package's own embedded sezgi-* crates -- are already
# covered by DESCRIPTION's Authors@R).

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) {
  stop("usage: cran_authors.R PKG_DIR", call. = FALSE)
}
pkg_dir <- normalizePath(args[[1]], mustWork = TRUE)
rust_dir <- file.path(pkg_dir, "src", "rust")

# ---------------------------------------------------------------------------
# Step 1: collect one record per crate: list(name=, version=, authors=chr[],
# license=chr).
# ---------------------------------------------------------------------------

# Parse the [package] table of a single (already-vendored, registry-
# normalized) Cargo.toml. This is a targeted parse, not a general TOML
# reader: registry manifests are auto-generated by `cargo publish` and have
# a predictable shape (one key per line, string/array values only for the
# fields we need), so line-oriented regexes are sufficient and avoid a TOML
# parser dependency.
parse_registry_manifest <- function(path) {
  lines <- readLines(path, warn = FALSE, encoding = "UTF-8")

  # Isolate the [package] table: from the "[package]" header to the next
  # top-level "[...]" header (or end of file).
  pkg_start <- which(lines == "[package]")
  if (length(pkg_start) == 0) {
    return(NULL)
  }
  next_headers <- which(grepl("^\\[", lines) & seq_along(lines) > pkg_start[1])
  pkg_end <- if (length(next_headers) == 0) length(lines) else next_headers[1] - 1
  block <- paste(lines[pkg_start[1]:pkg_end], collapse = "\n")

  extract1 <- function(key) {
    m <- regmatches(block, regexpr(sprintf('(?m)^%s\\s*=\\s*"([^"]*)"', key), block, perl = TRUE))
    if (length(m) == 0) return(NA_character_)
    sub(sprintf('^%s\\s*=\\s*"([^"]*)"', key), "\\1", m, perl = TRUE)
  }

  name <- extract1("name")
  version <- extract1("version")
  license <- extract1("license")

  authors <- character(0)
  m <- regmatches(block, regexpr("(?m)^authors\\s*=\\s*\\[[^]]*\\]", block, perl = TRUE))
  if (length(m) == 1) {
    items <- regmatches(m, gregexpr('"([^"]*)"', m, perl = TRUE))[[1]]
    authors <- gsub('^"|"$', "", items)
    # Registry manifests append "<email>" to author names; keep the name only.
    authors <- trimws(sub("\\s*<[^>]*>\\s*$", "", authors))
  }

  list(name = name, version = version, authors = authors,
       license = if (is.na(license)) "" else license)
}

crates_from_dir <- function(vendor_dir) {
  manifests <- sort(Sys.glob(file.path(vendor_dir, "*", "Cargo.toml")))
  recs <- lapply(manifests, parse_registry_manifest)
  Filter(Negate(is.null), recs)
}

crates_from_cargo_metadata <- function(manifest_path) {
  if (!requireNamespace("jsonlite", quietly = TRUE)) {
    stop("cargo_metadata fallback needs the jsonlite package", call. = FALSE)
  }
  if (Sys.which("cargo") == "") {
    stop("cargo_metadata fallback needs cargo on PATH", call. = FALSE)
  }
  out <- system2("cargo",
                  c("metadata", "--format-version", "1", "--locked",
                    "--manifest-path", shQuote(manifest_path)),
                  stdout = TRUE, stderr = FALSE)
  meta <- jsonlite::fromJSON(paste(out, collapse = "\n"), simplifyVector = FALSE)
  recs <- list()
  for (p in meta$packages) {
    # `source` is NULL for path/workspace members (the package's own
    # sezgi-* crates); only registry dependencies need crediting here.
    if (is.null(p$source)) next
    authors <- character(0)
    if (!is.null(p$authors) && length(p$authors) > 0) {
      authors <- trimws(sub("\\s*<[^>]*>\\s*$", "", unlist(p$authors)))
    }
    recs[[length(recs) + 1]] <- list(
      name = p$name, version = p$version, authors = authors,
      license = if (is.null(p$license)) "" else p$license
    )
  }
  recs[order(vapply(recs, `[[`, "", "name"))]
}

vendor_dir <- file.path(rust_dir, "vendor")
vendor_tarball <- file.path(rust_dir, "vendor.tar.xz")

if (dir.exists(vendor_dir)) {
  message("cran_authors.R: reading crate metadata from ", vendor_dir)
  crates <- crates_from_dir(vendor_dir)
} else if (file.exists(vendor_tarball)) {
  message("cran_authors.R: reading crate metadata from ", vendor_tarball)
  tmp <- tempfile("cran_authors_vendor_")
  dir.create(tmp)
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  utils::untar(vendor_tarball, exdir = tmp)
  crates <- crates_from_dir(file.path(tmp, "vendor"))
} else {
  message("cran_authors.R: no vendor tree found, falling back to `cargo metadata` (",
          rust_dir, ")")
  crates <- crates_from_cargo_metadata(file.path(rust_dir, "Cargo.toml"))
}

if (length(crates) == 0) {
  stop("cran_authors.R: found zero dependency crates to credit -- refusing ",
       "to overwrite inst/AUTHORS / LICENSE.note with an empty file",
       call. = FALSE)
}

# Two or more source-package versions of the same crate name can vendor
# side-by-side (e.g. two major versions of `syn` pulled in transitively);
# de-duplicate on name+version so each is credited exactly once.
key <- vapply(crates, function(c) paste(c$name, c$version), "")
crates <- crates[!duplicated(key)]
crates <- crates[order(vapply(crates, `[[`, "", "name"))]

# ---------------------------------------------------------------------------
# Step 2: render inst/AUTHORS, following the format of the (also savvy-
# based) CRAN package `string2path`, the reference implementation named in
# CRAN's own "Using Rust" document.
# ---------------------------------------------------------------------------

authors_lines <- c("The authors of the dependency Rust crates:", "")
for (c in crates) {
  authors_lines <- c(authors_lines, sprintf("%s (version %s):", c$name, c$version))
  for (a in c$authors) {
    authors_lines <- c(authors_lines, sprintf("  %s", a))
  }
  if (length(c$authors) == 0) authors_lines <- c(authors_lines, "  ")
  authors_lines <- c(authors_lines, "")
}
authors_lines <- authors_lines[-length(authors_lines)]  # drop trailing blank line

inst_dir <- file.path(pkg_dir, "inst")
dir.create(inst_dir, showWarnings = FALSE, recursive = TRUE)
writeLines(authors_lines, file.path(inst_dir, "AUTHORS"))

# ---------------------------------------------------------------------------
# Step 3: render LICENSE.note. Any crate whose license expression names more
# than the plain MIT / Apache-2.0 pair gets flagged with a footnote, mirroring
# string2path's treatment of `unicode-ident` (which additionally carries the
# Unicode-3.0 license for its Unicode Character Database-derived tables; that
# license does not apply to the compiled code, only to test/data assets that
# are not part of the shipped binary).
is_footnote_license <- function(license) {
  grepl("Unicode", license, fixed = TRUE)
}

footnoted <- Filter(function(c) is_footnote_license(c$license), crates)

note_lines <- c(
  "This package contains the Rust source code of the dependencies in",
  "src/rust/vendor.tar.xz (present in the CRAN release tarball; omitted",
  "when built directly from the git repository, where the sources are",
  "instead compiled from the crates.io versions pinned in",
  "src/rust/Cargo.lock).",
  "",
  "The authorships and the licenses are listed below. In summary, all",
  "libraries are distributed under the MIT license, the Apache-2.0",
  "license, or a MIT/Apache-2.0 dual license."
)
if (length(footnoted) > 0) {
  note_lines <- c(note_lines, "", sprintf("See the note%s below the crate list.",
                                            if (length(footnoted) > 1) "s" else ""))
}
note_lines <- c(note_lines, "", "===============================", "")

for (i in seq_along(crates)) {
  c <- crates[[i]]
  note_lines <- c(note_lines,
                   sprintf("Name:    %s", c$name),
                   sprintf("Files:   vendor/%s/*", c$name),
                   sprintf("Authors: %s", paste(c$authors, collapse = ", ")),
                   sprintf("License: %s", c$license))
  if (i < length(crates)) {
    note_lines <- c(note_lines, "", "------------------------------", "")
  }
}

if (length(footnoted) > 0) {
  note_lines <- c(note_lines, "", "===============================", "")
  for (c in footnoted) {
    note_lines <- c(note_lines, sprintf(
      "Note: %s's license expression (%s) includes a Unicode license",
      c$name, c$license))
    note_lines <- c(note_lines,
      "clause. That clause covers Unicode Character Database-derived",
      "tables/tests bundled in the crate's source, not the code actually",
      "compiled into this package's shared library. See the crate's own",
      sprintf("repository (https://crates.io/crates/%s) for details.", c$name),
      "")
  }
  note_lines <- note_lines[-length(note_lines)]
}

writeLines(note_lines, file.path(pkg_dir, "LICENSE.note"))

message(sprintf("cran_authors.R: wrote inst/AUTHORS and LICENSE.note for %d crates",
                 length(crates)))
