name: Test R-universe
on:
  workflow_dispatch:
  push:
    tags: ["v*"]
jobs:
  build:
    name: R-universe testing
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}
      subdir: r-sezgi
